name: forcad
channels:
  - conda-forge
  - defaults
dependencies:
  # Fortran compilers
  - gfortran
  # - ifx_linux-64
  # - ifx_win-64
  # - intel-fortran-rt
  # - flang
  # - lfortran

  # Build tools
  - fpm
  # - cmake
  # - ninja
  # - meson

  # Visualization
  - pyvista
  # - paraview
  # - gmsh
  # - freecad

  # Formatting and linting
  - fortls
  # - fprettify
  # - findent

  # Documentation
  - ford
  - graphviz

  # Version control
  # - git
