name: forcad
channels:
  - conda-forge
  - defaults
dependencies:
  # Fortran compilers
  - gfortran
  # - ifx_linux-64  # [linux]
  # - ifx_win-64    # [win]
  # - flang
  # - lfortran

  # Build tools
  - fpm
  # - cmake
  # - meson
  # - ninja

  # Visualization
  - pyvista
  # - paraview
  # - gmsh
  # - freecad

  # Formatting and linting
  - fortls
  - fprettify
  - findent

  # Documentation
  - ford

  # Version control
  # - git
