name       = "forcad"
description= "A parallel Fortran library for geometric modeling using NURBS"
version    = "VERSION"
license    = "BSD 3-Clause License"
author     = "Seyed Ali Ghasemi"
maintainer = "info@gha3mi.com"
homepage   = "https://github.com/gha3mi/forcad"
copyright  = "Copyright 2026, Seyed Ali Ghasemi"
categories = ["graphics"]
keywords   = ["Fortran", "CAD","NURBS", "b-spline","bezier","rational bezier","geometry"]

[build]
auto-executables = false
auto-tests       = true
auto-examples    = false
module-naming    = false

[install]
library = true

[fortran]
implicit-typing   = false
implicit-external = false
source-form       = "free"

[preprocess]
[preprocess.cpp]

[dependencies]
openmp = "*"
forIGES = {git="https://github.com/rweed/forIGES.git"}
fordebug = {git="https://github.com/gha3mi/fordebug.git", preprocess.cpp.macros=["NOPURE_DEBUG"], tag="v0.2.1"}

[dev-dependencies]
forunittest = {git="https://github.com/gha3mi/forunittest", tag="v0.3.2"}

[[example]]
name       = "curve_basic"
source-dir = "example"
main       = "curve_basic.f90"

[[example]]
name       = "surface_basic"
source-dir = "example"
main       = "surface_basic.f90"

[[example]]
name       = "volume_basic"
source-dir = "example"
main       = "volume_basic.f90"

[[example]]
name       = "curve_shape_c"
source-dir = "example"
main       = "curve_shape_c.f90"

[[example]]
name       = "surface_shape_c"
source-dir = "example"
main       = "surface_shape_c.f90"

[[example]]
name       = "volume_shape_c"
source-dir = "example"
main       = "volume_shape_c.f90"

[[example]]
name       = "curve_circle"
source-dir = "example"
main       = "curve_circle.f90"

[[example]]
name       = "curve_half_circle"
source-dir = "example"
main       = "curve_half_circle.f90"

[[example]]
name       = "surface_half_ring"
source-dir = "example"
main       = "surface_half_ring.f90"

[[example]]
name       = "volume_half_ring"
source-dir = "example"
main       = "volume_half_ring.f90"

[[example]]
name       = "volume_hexahedron"
source-dir = "example"
main       = "volume_hexahedron.f90"

[[example]]
name       = "surface_ring"
source-dir = "example"
main       = "surface_ring.f90"

[[example]]
name       = "volume_ring"
source-dir = "example"
main       = "volume_ring.f90"

[[example]]
name       = "surface_tetragon"
source-dir = "example"
main       = "surface_tetragon.f90"

[[example]]
name       = "curve_knot_clamped"
source-dir = "example"
main       = "curve_knot_clamped.f90"

[[example]]
name       = "surface_knot_clamped"
source-dir = "example"
main       = "surface_knot_clamped.f90"

[[example]]
name       = "volume_knot_clamped"
source-dir = "example"
main       = "volume_knot_clamped.f90"

[[example]]
name       = "curve_knot_periodic"
source-dir = "example"
main       = "curve_knot_periodic.f90"

[[example]]
name       = "surface_knot_periodic"
source-dir = "example"
main       = "surface_knot_periodic.f90"

[[example]]
name       = "volume_knot_periodic"
source-dir = "example"
main       = "volume_knot_periodic.f90"

[[example]]
name       = "curve_knot_repeated"
source-dir = "example"
main       = "curve_knot_repeated.f90"

[[example]]
name       = "surface_knot_repeated"
source-dir = "example"
main       = "surface_knot_repeated.f90"

[[example]]
name       = "volume_knot_repeated"
source-dir = "example"
main       = "volume_knot_repeated.f90"

[[example]]
name       = "curve_knot_unclamped"
source-dir = "example"
main       = "curve_knot_unclamped.f90"

[[example]]
name       = "surface_knot_unclamped"
source-dir = "example"
main       = "surface_knot_unclamped.f90"

[[example]]
name       = "volume_knot_unclamped"
source-dir = "example"
main       = "volume_knot_unclamped.f90"

[[example]]
name       = "surface_extrude"
source-dir = "example"
main       = "surface_extrude.f90"

[[example]]
name       = "volume_extrude"
source-dir = "example"
main       = "volume_extrude.f90"

[[example]]
name       = "surface_loft"
source-dir = "example"
main       = "surface_loft.f90"

[[example]]
name       = "volume_loft"
source-dir = "example"
main       = "volume_loft.f90"

[[example]]
name       = "surface_revolve"
source-dir = "example"
main       = "surface_revolve.f90"

[[example]]
name       = "volume_revolve"
source-dir = "example"
main       = "volume_revolve.f90"

[[example]]
name       = "surface_sweep"
source-dir = "example"
main       = "surface_sweep.f90"

[[example]]
name       = "volume_sweep"
source-dir = "example"
main       = "volume_sweep.f90"

[[example]]
name       = "curve_refine"
source-dir = "example"
main       = "curve_refine.f90"

[[example]]
name       = "surface_refine"
source-dir = "example"
main       = "surface_refine.f90"

[[example]]
name       = "volume_refine"
source-dir = "example"
main       = "volume_refine.f90"

[[example]]
name       = "curve_transform"
source-dir = "example"
main       = "curve_transform.f90"

[[example]]
name       = "surface_transform"
source-dir = "example"
main       = "surface_transform.f90"

[[example]]
name       = "volume_transform"
source-dir = "example"
main       = "volume_transform.f90"

[[example]]
name       = "curve_basis"
source-dir = "example"
main       = "curve_basis.f90"

[[example]]
name       = "surface_basis"
source-dir = "example"
main       = "surface_basis.f90"

[[example]]
name       = "volume_basis"
source-dir = "example"
main       = "volume_basis.f90"

[[example]]
name       = "curve_derivatives"
source-dir = "example"
main       = "curve_derivatives.f90"

[[example]]
name       = "surface_derivatives"
source-dir = "example"
main       = "surface_derivatives.f90"

[[example]]
name       = "volume_derivatives"
source-dir = "example"
main       = "volume_derivatives.f90"

[[example]]
name       = "curve_ansatz"
source-dir = "example"
main       = "curve_ansatz.f90"

[[example]]
name       = "surface_ansatz"
source-dir = "example"
main       = "surface_ansatz.f90"

[[example]]
name       = "volume_ansatz"
source-dir = "example"
main       = "volume_ansatz.f90"

[[example]]
name       = "curve_connectivity"
source-dir = "example"
main       = "curve_connectivity.f90"

[[example]]
name       = "surface_connectivity"
source-dir = "example"
main       = "surface_connectivity.f90"

[[example]]
name       = "volume_connectivity"
source-dir = "example"
main       = "volume_connectivity.f90"

[[example]]
name       = "curve_cmp_length"
source-dir = "example"
main       = "curve_cmp_length.f90"

[[example]]
name       = "surface_cmp_area"
source-dir = "example"
main       = "surface_cmp_area.f90"

[[example]]
name       = "volume_cmp_volume"
source-dir = "example"
main       = "volume_cmp_volume.f90"

[[example]]
name       = "curve_nearest"
source-dir = "example"
main       = "curve_nearest.f90"

[[example]]
name       = "surface_nearest"
source-dir = "example"
main       = "surface_nearest.f90"

[[example]]
name       = "volume_nearest"
source-dir = "example"
main       = "volume_nearest.f90"

[[example]]
name       = "curve_fit_bspline"
source-dir = "example"
main       = "curve_fit_bspline.f90"

[[example]]
name       = "surface_fit_bspline"
source-dir = "example"
main       = "surface_fit_bspline.f90"

[[example]]
name       = "volume_fit_bspline"
source-dir = "example"
main       = "volume_fit_bspline.f90"

[[example]]
name       = "curve_fit_nurbs"
source-dir = "example"
main       = "curve_fit_nurbs.f90"

[[example]]
name       = "surface_fit_nurbs"
source-dir = "example"
main       = "surface_fit_nurbs.f90"

[[example]]
name       = "volume_fit_nurbs"
source-dir = "example"
main       = "volume_fit_nurbs.f90"

[[example]]
name       = "curve_multipatch"
source-dir = "example"
main       = "curve_multipatch.f90"

[[example]]
name       = "surface_multipatch_grid"
source-dir = "example"
main       = "surface_multipatch_grid.f90"

[[example]]
name       = "surface_multipatch_mixed"
source-dir = "example"
main       = "surface_multipatch_mixed.f90"

[[example]]
name       = "surface_multipatch"
source-dir = "example"
main       = "surface_multipatch.f90"

[[example]]
name       = "volume_multipatch"
source-dir = "example"
main       = "volume_multipatch.f90"

[[example]]
name       = "surface_multipatch_c1_helix"
source-dir = "example"
main       = "surface_multipatch_c1_helix.f90"

[[example]]
name       = "surface_multipatch_c1_ribbon"
source-dir = "example"
main       = "surface_multipatch_c1_ribbon.f90"

[[example]]
name       = "volume_multipatch_c2_chassis"
source-dir = "example"
main       = "volume_multipatch_c2_chassis.f90"

[[example]]
name       = "surface_multipatch_c2_dome"
source-dir = "example"
main       = "surface_multipatch_c2_dome.f90"

[[example]]
name       = "surface_multipatch_cn_shell"
source-dir = "example"
main       = "surface_multipatch_cn_shell.f90"

[[example]]
name       = "volume_multipatch_cn_sweep"
source-dir = "example"
main       = "volume_multipatch_cn_sweep.f90"

[[example]]
name       = "curve_multipatch_gn"
source-dir = "example"
main       = "curve_multipatch_gn.f90"

[[example]]
name       = "surface_multipatch_gn"
source-dir = "example"
main       = "surface_multipatch_gn.f90"

[[example]]
name       = "volume_multipatch_gn"
source-dir = "example"
main       = "volume_multipatch_gn.f90"

[[example]]
name       = "curve_iga_beam_c1"
source-dir = "example"
main       = "curve_iga_beam_c1.f90"

[[example]]
name       = "surface_iga_elasticity_beam"
source-dir = "example"
main       = "surface_iga_elasticity_beam.f90"

[[example]]
name       = "surface_iga_heat_annulus"
source-dir = "example"
main       = "surface_iga_heat_annulus.f90"

[[example]]
name       = "volume_iga_heat_transient"
source-dir = "example"
main       = "volume_iga_heat_transient.f90"

[[example]]
name       = "surface_iga_plate_c1"
source-dir = "example"
main       = "surface_iga_plate_c1.f90"

[[example]]
name       = "surface_iga_poisson"
source-dir = "example"
main       = "surface_iga_poisson.f90"
[example.dependencies]
fortime = {git="https://github.com/gha3mi/fortime.git"}

[[example]]
name       = "volume_iga_poisson"
source-dir = "example"
main       = "volume_iga_poisson.f90"
[example.dependencies]
fortime = {git="https://github.com/gha3mi/fortime.git"}

[[example]]
name       = "volume_iga_c1"
source-dir = "example"
main       = "volume_iga_c1.f90"

[[example]]
name       = "volume_import"
source-dir = "example"
main       = "volume_import.f90"

[[example]]
name       = "volume_pipe_bend"
source-dir = "example"
main       = "volume_pipe_bend.f90"

[[example]]
name       = "volume_pipe_helix"
source-dir = "example"
main       = "volume_pipe_helix.f90"

[[example]]
name       = "volume_pipe_toroidal"
source-dir = "example"
main       = "volume_pipe_toroidal.f90"

[[example]]
name       = "volume_twist_taper"
source-dir = "example"
main       = "volume_twist_taper.f90"

[[example]]
name       = "surface_plate_hole_quarter"
source-dir = "example"
main       = "surface_plate_hole_quarter.f90"

[[example]]
name       = "volume_plate_hole_quarter"
source-dir = "example"
main       = "volume_plate_hole_quarter.f90"

[[example]]
name       = "surface_plate_hole_full"
source-dir = "example"
main       = "surface_plate_hole_full.f90"

[[example]]
name       = "volume_plate_hole_full"
source-dir = "example"
main       = "volume_plate_hole_full.f90"

[[example]]
name       = "surface_plate_hole_half"
source-dir = "example"
main       = "surface_plate_hole_half.f90"

[[example]]
name       = "volume_plate_hole_half"
source-dir = "example"
main       = "volume_plate_hole_half.f90"

[[example]]
name       = "volume_multipatch_beam"
source-dir = "example"
main       = "volume_multipatch_beam.f90"

[[example]]
name       = "volume_multipatch_bracket"
source-dir = "example"
main       = "volume_multipatch_bracket.f90"

[[example]]
name       = "surface_multipatch_bridge"
source-dir = "example"
main       = "surface_multipatch_bridge.f90"

[[example]]
name       = "surface_multipatch_canopy"
source-dir = "example"
main       = "surface_multipatch_canopy.f90"

[[example]]
name       = "surface_multipatch_courtyard"
source-dir = "example"
main       = "surface_multipatch_courtyard.f90"

[[example]]
name       = "volume_multipatch_elbow"
source-dir = "example"
main       = "volume_multipatch_elbow.f90"

[[example]]
name       = "volume_multipatch_frame"
source-dir = "example"
main       = "volume_multipatch_frame.f90"

[[example]]
name       = "volume_multipatch_gear"
source-dir = "example"
main       = "volume_multipatch_gear.f90"

[[example]]
name       = "volume_multipatch_housing"
source-dir = "example"
main       = "volume_multipatch_housing.f90"

[[example]]
name       = "volume_multipatch_impeller"
source-dir = "example"
main       = "volume_multipatch_impeller.f90"

[[example]]
name       = "volume_multipatch_joint"
source-dir = "example"
main       = "volume_multipatch_joint.f90"

[[example]]
name       = "volume_multipatch_manifold"
source-dir = "example"
main       = "volume_multipatch_manifold.f90"

[[example]]
name       = "volume_multipatch_mount"
source-dir = "example"
main       = "volume_multipatch_mount.f90"

[[example]]
name       = "surface_multipatch_pavilion"
source-dir = "example"
main       = "surface_multipatch_pavilion.f90"

[[example]]
name       = "volume_multipatch_perforated"
source-dir = "example"
main       = "volume_multipatch_perforated.f90"

[[example]]
name       = "volume_multipatch_screw_rotor"
source-dir = "example"
main       = "volume_multipatch_screw_rotor.f90"

[[example]]
name       = "surface_multipatch_tower"
source-dir = "example"
main       = "surface_multipatch_tower.f90"

[[example]]
name       = "volume_multipatch_turbine_blade"
source-dir = "example"
main       = "volume_multipatch_turbine_blade.f90"

[[example]]
name       = "volume_multipatch_volute"
source-dir = "example"
main       = "volume_multipatch_volute.f90"

[[example]]
name       = "surface_ppm_half_ring_colormap"
source-dir = "example"
main       = "surface_ppm_half_ring_colormap.f90"
[example.dependencies]
forimage    = {git="https://github.com/gha3mi/forimage.git"}
forcolormap = {git="https://github.com/vmagnin/forcolormap.git"}
fortime     = {git="https://github.com/gha3mi/fortime.git"}

[[example]]
name       = "surface_ppm_ring_colormap"
source-dir = "example"
main       = "surface_ppm_ring_colormap.f90"
[example.dependencies]
forimage    = {git="https://github.com/gha3mi/forimage.git"}
forcolormap = {git="https://github.com/vmagnin/forcolormap.git"}
fortime     = {git="https://github.com/gha3mi/fortime.git"}

[[example]]
name       = "surface_ppm_tetragon_colormap"
source-dir = "example"
main       = "surface_ppm_tetragon_colormap.f90"
[example.dependencies]
forimage    = {git="https://github.com/gha3mi/forimage.git"}
forcolormap = {git="https://github.com/vmagnin/forcolormap.git"}
fortime     = {git="https://github.com/gha3mi/fortime.git"}

[[example]]
name       = "logo"
source-dir = "logo"
main       = "logo.f90"

[[example]]
name       = "nearest_surface_benchmark"
source-dir = "benchmark"
main       = "nearest_surface.f90"
[example.dependencies]
fortime = {git="https://github.com/gha3mi/fortime.git"}


[extra.ford]
project             = "ForCAD"
year                = "2023-2026"
summary             = '<p style="text-align: center"><img alt="ForCAD" src="https://github.com/gha3mi/forcad/raw/main/logo/logo.png" style="max-width: 100%; height: auto;"></p>'
project_github      = "https://github.com/gha3mi/forcad"
author              = "Seyed Ali Ghasemi"
email               = "info@gha3mi.com"
github              = "https://github.com/gha3mi"
license             = "BSD 3-Clause"
src_dir             = ["src", "example", "test"]
page_dir            = "docs/ford/pages"
output_dir          = "docs/ford/api"
source              = true
incl_src            = true
graph               = true
coloured_edges      = true
search              = true
print_creation_date = true
sort                = "permission-alpha"
display             = ["public", "private", "protected"]
favicon             = "logo/logo.png"


[extra.fortitude.check]
ignore = ["S001", "S061", "S081", "C003", "C061", "C051", "E001"]
per-file-ignores = { "src/forcad_nurbs_curve.F90" = ["C143", "C191"], "src/forcad_nurbs_surface.F90" = ["C143", "C191"], "src/forcad_nurbs_volume.F90" = ["C143", "C191"] }









# [features]
# test-common.preprocess.cpp.macros = ["FOR_DEBUG"]

# # gfortran
# test-debug.gfortran.linux.flags     = "-Wno-maybe-uninitialized -ftree-parallelize-loops=8"
# test-debug.gfortran.macos.flags     = "-O0 -g -fcheck=bounds -fcheck=array-temps -fbacktrace -Wno-maybe-uninitialized -ftree-parallelize-loops=8"
# test-debug.gfortran.windows.flags   = "-O0 -g -fcheck=bounds -fcheck=array-temps -fbacktrace -Wno-maybe-uninitialized -ftree-parallelize-loops=8"
# test-release.gfortran.linux.flags   = "-O3 -ftree-parallelize-loops=8 -march=native"
# test-release.gfortran.macos.flags   = "-O3 -ftree-parallelize-loops=8 -march=native"
# test-release.gfortran.windows.flags = "-O3 -ftree-parallelize-loops=8 -march=native"

# # ifx
# test-debug.ifx.linux.flags     = "-O0 -g -fopenmp-target-do-concurrent"
# test-debug.ifx.windows.flags   = "/Od /debug:full /Qopenmp-target-do-concurrent"
# test-release.ifx.linux.flags   = "-O3 -fopenmp-target-do-concurrent"
# test-release.ifx.windows.flags = "/O3 /Qopenmp-target-do-concurrent"

# # nvfortran
# test-debug.nvfortran.linux.flags   = "-O0 -g -stdpar=multicore,gpu -Minfo=stdpar,accel"
# test-release.nvfortran.linux.flags = "-O4 -stdpar=multicore,gpu -gpu=nordc -gpu=ccall -Mvect=simd -Mcache_align -Minline -Mconcur -Mlre -Mflushz -Mdaz"

# # flang-new
# test-debug.flang-new.linux.flags     = "-O0 -g -cpp"
# test-debug.flang-new.macos.flags     = "-O0 -g -cpp"
# test-debug.flang-new.windows.flags   = "-O0 -g -cpp"
# test-release.flang-new.linux.flags   = "-O3 -cpp"
# test-release.flang-new.macos.flags   = "-O3 -cpp"
# test-release.flang-new.windows.flags = "-O3 -cpp"

# [profiles]
# test-debug   = ["debug",   "test-common", "test-debug"  ]
# test-release = ["release", "test-common", "test-release"]