ansatz – ForCAD
ansatz Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
42 statements
Source File
private pure subroutine ansatz(this, ie, ig, Tgc, dTgc_dXg, dV, ngauss)
Type Bound
nurbs_volume
Arguments
Type Intent Optional Attributes Name
class(nurbs_volume), intent(inout) :: this
integer, intent(in) :: ie
integer, intent(in) :: ig
real(kind=rk), intent(out), allocatable :: Tgc(:)
real(kind=rk), intent(out), allocatable :: dTgc_dXg(:,:)
real(kind=rk), intent(out) :: dV
integer, intent(in), optional :: ngauss(3)
Calls
Called by
Call graph
ansatz calls gauss_leg, ndgrid, unique, derivative, set, cmp_elem, det, inv
gauss_leg calls gauss_legendre_1d, gauss_legendre_2d, gauss_legendre_3d
ndgrid calls ndgrid2, ndgrid3
unique calls unique_integer, unique_real
cmp_elem calls unique, elemconn_cn, get_multiplicity
inv calls det, inv, eye, solve
elemconn_cn calls cmp_elemconn_cn_l, cmp_elemconn_cn_s, cmp_elemconn_cn_v
derivative_scalar calls compute_dtgc, is_rational
derivative_vector calls ndgrid, compute_dtgc, is_rational
gauss_legendre_1d calls gauss_legendre
gauss_legendre_2d calls ndgrid, kron, gauss_legendre
gauss_legendre_3d calls ndgrid, kron, gauss_legendre
get_multiplicity calls compute_multiplicity
set1 calls cmp_degree, cmp_nc, set
set2 calls cmp_nc, compute_knot_vector, set
set3 calls cmp_degree, set
set4 calls set
compute_dtgc calls compute_dtgc_bspline_3d_scalar, compute_dtgc_bspline_3d_vector, compute_dtgc_nurbs_3d_scalar, compute_dtgc_nurbs_3d_vector
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
kron calls kron3, kron_t1_t1, kron_t1_t2
cmp_degree calls get_multiplicity, set
cmp_nc calls compute_multiplicity, set
compute_knot_vector calls repelem
compute_dtgc_bspline_3d_scalar calls kron, basis_bspline_der
compute_dtgc_bspline_3d_vector calls kron, basis_bspline_der
compute_dtgc_nurbs_3d_scalar calls kron, basis_bspline_der
compute_dtgc_nurbs_3d_vector calls kron, basis_bspline_der
basis_bspline_der calls basis_bspline_der_a, basis_bspline_der_b
cmp_volume calls ansatz
poisson_iga_solver_3d calls ansatz
compute_volume calls cmp_volume
test_nurbs_volume calls cmp_volume