ansatz – ForCAD
ansatz Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
37 statements
Source File
private pure subroutine ansatz(this, ie, ig, Tgc, dTgc_dXg, dL, ngauss)
Type Bound
nurbs_curve
Arguments
Type Intent Optional Attributes Name
class(nurbs_curve), intent(inout) :: this
integer, intent(in) :: ie
integer, intent(in) :: ig
real(kind=rk), intent(out), allocatable :: Tgc(:)
real(kind=rk), intent(out), allocatable :: dTgc_dXg(:,:)
real(kind=rk), intent(out) :: dL
integer, intent(in), optional :: ngauss
Calls
Called by
Call graph
ansatz calls dyad, gauss_leg, unique, derivative, set, cmp_elem
dyad calls dyad_t1_t1
gauss_leg calls gauss_legendre_1d, gauss_legendre_2d, gauss_legendre_3d
unique calls unique_integer, unique_real
cmp_elem calls unique, elemconn_cn, get_multiplicity
elemconn_cn calls cmp_elemconn_cn_l, cmp_elemconn_cn_s, cmp_elemconn_cn_v
derivative_scalar calls compute_dtgc, is_rational
derivative_vector calls compute_dtgc, is_rational
gauss_legendre_1d calls gauss_legendre
gauss_legendre_2d calls kron, ndgrid, gauss_legendre
gauss_legendre_3d calls kron, ndgrid, gauss_legendre
get_multiplicity calls compute_multiplicity
set1a calls cmp_degree, set
set1 calls cmp_degree, set
set2 calls cmp_nc, compute_knot_vector, set
set3 calls cmp_degree, set
set4 calls set
compute_dtgc calls compute_dtgc_bspline_1d_scalar, compute_dtgc_bspline_1d_vector, compute_dtgc_nurbs_1d_scalar, compute_dtgc_nurbs_1d_vector
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
kron calls kron3, kron_t1_t1, kron_t1_t2
ndgrid calls ndgrid2, ndgrid3
cmp_degree calls get_multiplicity
cmp_nc calls compute_multiplicity
compute_knot_vector calls repelem
compute_dtgc_bspline_1d_scalar calls basis_bspline_der
compute_dtgc_bspline_1d_vector calls basis_bspline_der
compute_dtgc_nurbs_1d_scalar calls basis_bspline_der
compute_dtgc_nurbs_1d_vector calls basis_bspline_der
basis_bspline_der calls basis_bspline_der_a, basis_bspline_der_b
cmp_length calls ansatz
compute_length calls cmp_length
test_nurbs_curve calls cmp_length