ansatz – ForCAD
ansatz Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
33 statements
Source File
private pure subroutine ansatz(this, ie, ig, Tgc, dTgc_dXg, dA)
Type Bound
nurbs_surface
Arguments
Type Intent Optional Attributes Name
class(nurbs_surface), intent(inout) :: this
integer, intent(in) :: ie
integer, intent(in) :: ig
real(kind=rk), intent(out), allocatable :: Tgc(:)
real(kind=rk), intent(out), allocatable :: dTgc_dXg(:,:)
real(kind=rk), intent(out) :: dA
Calls
Called by
Call graph
ansatz calls gauss_leg, ndgrid, unique, derivative, set, cmp_elem, det, inv
gauss_leg calls gauss_legendre_1d, gauss_legendre_2d, gauss_legendre_3d
ndgrid calls ndgrid2, ndgrid3
unique calls unique_integer, unique_real
cmp_elem calls unique, elemconn_cn, get_multiplicity
inv calls det, inv
elemconn_cn calls cmp_elemconn_cn_l, cmp_elemconn_cn_s, cmp_elemconn_cn_v
derivative_scalar calls compute_dtgc, is_rational
derivative_vector calls ndgrid, compute_dtgc, is_rational
gauss_legendre_1d calls gauss_legendre
gauss_legendre_2d calls ndgrid, gauss_legendre, kron
gauss_legendre_3d calls ndgrid, gauss_legendre, kron
get_multiplicity calls compute_multiplicity
set1 calls cmp_degree, cmp_nc
set2 calls cmp_nc, compute_knot_vector
set3 calls cmp_degree
compute_dtgc calls compute_dtgc_bspline_2d_scalar, compute_dtgc_bspline_2d_vector, compute_dtgc_nurbs_2d_scalar, compute_dtgc_nurbs_2d_vector
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
cmp_degree calls get_multiplicity
cmp_nc calls compute_multiplicity
compute_knot_vector calls repelem
compute_dtgc_bspline_2d_scalar calls kron, basis_bspline_der
compute_dtgc_bspline_2d_vector calls kron, basis_bspline_der
compute_dtgc_nurbs_2d_scalar calls kron, basis_bspline_der
compute_dtgc_nurbs_2d_vector calls kron, basis_bspline_der
basis_bspline_der calls basis_bspline_der_a, basis_bspline_der_b
cmp_area calls ansatz
compute_area calls cmp_area
test_nurbs_surface calls cmp_area