basis_scalar – ForCAD
basis_scalar Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
10 statements
Source File
private pure subroutine basis_scalar(this, Xt, Tgc)
Type Bound
nurbs_surface
Arguments
Type Intent Optional Attributes Name
class(nurbs_surface), intent(inout) :: this
real(kind=rk), intent(in) :: Xt(:)
real(kind=rk), intent(out), allocatable :: Tgc(:)
Calls
Called by
Call graph
basis_scalar calls compute_tgc, is_rational
compute_tgc calls compute_tgc_bspline_2d_scalar, compute_tgc_bspline_2d_vector, compute_tgc_nurbs_2d_scalar, compute_tgc_nurbs_2d_vector
compute_tgc_bspline_2d_scalar calls basis_bspline, kron
compute_tgc_bspline_2d_vector calls basis_bspline, kron
compute_tgc_nurbs_2d_scalar calls basis_bspline, kron
compute_tgc_nurbs_2d_vector calls basis_bspline, kron
test_nurbs_surface calls basis