basis_vector – ForCAD
basis_vector Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
30 statements
Source File
private pure subroutine basis_vector(this, res, Xt, Tgc)
Type Bound
nurbs_curve
Arguments
Type Intent Optional Attributes Name
class(nurbs_curve), intent(inout) :: this
integer, intent(in), optional :: res
real(kind=rk), intent(in), optional, contiguous :: Xt(:)
real(kind=rk), intent(out), allocatable :: Tgc(:,:)
Calls
Called by
Call graph
basis_vector calls compute_tgc, is_rational
compute_tgc calls compute_tgc_bspline_1d_scalar, compute_tgc_bspline_1d_vector, compute_tgc_nurbs_1d_scalar, compute_tgc_nurbs_1d_vector
compute_tgc_bspline_1d_scalar calls basis_bspline
compute_tgc_bspline_1d_vector calls basis_bspline
compute_tgc_nurbs_1d_scalar calls basis_bspline
compute_tgc_nurbs_1d_vector calls basis_bspline
test_nurbs_curve calls basis