basis_bspline – ForCAD
basis_bspline Function
Seyed Ali Ghasemi
BSD 3-Clause
58 statements
Source File
public pure function basis_bspline(Xt, knot, nc, degree) result(B)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: Xt
real(kind=rk), intent(in), contiguous :: knot(:)
integer, intent(in) :: nc
integer, intent(in) :: degree
Return Value real(kind=rk), (nc)
Called by
Call graph
cmp_tgc_1d calls basis_bspline
cmp_tgc_2d calls basis_bspline
cmp_tgc_3d calls basis_bspline
compute_tgc_bspline_1d_scalar calls basis_bspline
compute_tgc_bspline_1d_vector calls basis_bspline
compute_tgc_bspline_2d_scalar calls basis_bspline
compute_tgc_bspline_2d_vector calls basis_bspline
compute_tgc_bspline_3d_scalar calls basis_bspline
compute_tgc_bspline_3d_vector calls basis_bspline
compute_tgc_nurbs_1d_scalar calls basis_bspline
compute_tgc_nurbs_1d_vector calls basis_bspline
compute_tgc_nurbs_2d_scalar calls basis_bspline
compute_tgc_nurbs_2d_vector calls basis_bspline
compute_tgc_nurbs_3d_scalar calls basis_bspline
compute_tgc_nurbs_3d_vector calls basis_bspline
compute_xg_bspline_1d calls basis_bspline
compute_xg_bspline_1d_1point calls basis_bspline
compute_xg_bspline_2d calls basis_bspline
compute_xg_bspline_2d_1point calls basis_bspline
compute_xg_bspline_3d calls basis_bspline
compute_xg_bspline_3d_1point calls basis_bspline
compute_xg_nurbs_1d_1point calls basis_bspline
compute_xg_nurbs_2d_1point calls basis_bspline
compute_xg_nurbs_3d_1point calls basis_bspline
lsq_fit_bspline calls basis_bspline
lsq_fit_nurbs calls basis_bspline
test_forcad_utils calls basis_bspline
compute_tgc calls compute_tgc_bspline_2d_scalar, compute_tgc_bspline_2d_vector, compute_tgc_nurbs_2d_scalar, compute_tgc_nurbs_2d_vector, compute_tgc_bspline_1d_scalar, compute_tgc_bspline_1d_vector, compute_tgc_nurbs_1d_scalar, compute_tgc_nurbs_1d_vector, compute_tgc_bspline_3d_scalar, compute_tgc_bspline_3d_vector, compute_tgc_nurbs_3d_scalar, compute_tgc_nurbs_3d_vector
compute_xg calls compute_xg_bspline_2d, compute_xg_bspline_2d_1point, compute_xg_nurbs_2d_1point, compute_xg_nurbs_2d, compute_xg_bspline_1d, compute_xg_bspline_1d_1point, compute_xg_nurbs_1d_1point, compute_xg_nurbs_1d, compute_xg_bspline_3d, compute_xg_bspline_3d_1point, compute_xg_nurbs_3d_1point, compute_xg_nurbs_3d
compute_xg_nurbs_1d calls cmp_tgc_1d
compute_xg_nurbs_2d calls cmp_tgc_2d
compute_xg_nurbs_3d calls cmp_tgc_3d
lsq_fit_bspline_1d calls lsq_fit_bspline, create
lsq_fit_bspline_2d calls lsq_fit_bspline, create, export_xth_in_xg
lsq_fit_bspline_3d calls lsq_fit_bspline, create, export_xth_in_xg
lsq_fit_nurbs_1d calls lsq_fit_nurbs, create
lsq_fit_nurbs_2d calls lsq_fit_nurbs, create, export_xth_in_xg
lsq_fit_nurbs_3d calls lsq_fit_nurbs, create, export_xth_in_xg
test_nurbs_volume calls lsq_fit_bspline, create, basis, nearest_point2
basis_scalar calls compute_tgc
basis_vector calls compute_tgc
cmp_xg calls compute_xg
create calls compute_xg
export_xth_in_xg calls compute_xg
put_to_nurbs calls compute_xg
nearest_point2 calls cmp_xg, create
example1_curve calls create
example3_surface calls create
example3_volume calls create
example_bend_pipe calls create, export_xth_in_xg
example_helix_pipe calls create, export_xth_in_xg
example_nurbs_curve calls create
example_nurbs_surface calls create, export_xth_in_xg
example_nurbs_volume calls create, export_xth_in_xg
example_plate_hole_1_2d calls create, export_xth_in_xg
example_plate_hole_1_3d calls create, export_xth_in_xg
example_plate_hole_2_2d calls create, export_xth_in_xg
example_plate_hole_2_3d calls create, export_xth_in_xg
example_plate_hole_4_2d calls create, export_xth_in_xg
example_plate_hole_4_3d calls create, export_xth_in_xg
example_ppm1 calls create
example_ppm2 calls create
example_ppm3 calls create
example_put_to_nurbs calls put_to_nurbs
example_toroidal_pipe calls create, export_xth_in_xg
example_twist_taper calls create, export_xth_in_xg
fdm_test_curve calls create
fdm_test_surface calls create
fdm_test_volume calls create
nearest_point_1d calls create, nearest_point2
nearest_point_2d calls create, nearest_point2
nearest_point_2d_bench calls create
nearest_point_3d calls create, nearest_point2
poisson_iga_solver_2d calls create, basis
poisson_iga_solver_3d calls create, basis
shape_c_1d calls create
shape_c_2d calls create
shape_c_3d calls create
shape_circle calls create
shape_half_circle calls create
shape_half_ring_2d calls create
shape_half_ring_3d calls create
shape_hexahedron calls create
shape_ring_2d calls create
shape_ring_3d calls create
shape_tetragon calls create
test_nurbs_curve calls create, basis, nearest_point2
test_nurbs_surface calls create, basis, nearest_point2