basis_vector – ForCAD
basis_vector Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
53 statements
Source File
private pure subroutine basis_vector(this, res1, res2, Xt1, Xt2, Tgc)
Type Bound
nurbs_surface
Arguments
Type Intent Optional Attributes Name
class(nurbs_surface), intent(inout) :: this
integer, intent(in), optional :: res1
integer, intent(in), optional :: res2
real(kind=rk), intent(in), optional, contiguous :: Xt1(:)
real(kind=rk), intent(in), optional, contiguous :: Xt2(:)
real(kind=rk), intent(out), allocatable :: Tgc(:,:)
Calls
Called by
Call graph
basis_vector calls compute_tgc, ndgrid, is_rational
compute_tgc calls compute_tgc_bspline_2d_scalar, compute_tgc_bspline_2d_vector, compute_tgc_nurbs_2d_scalar, compute_tgc_nurbs_2d_vector
ndgrid calls ndgrid2, ndgrid3
compute_tgc_bspline_2d_scalar calls kron, basis_bspline
compute_tgc_bspline_2d_vector calls kron, basis_bspline
compute_tgc_nurbs_2d_scalar calls kron, basis_bspline
compute_tgc_nurbs_2d_vector calls kron, basis_bspline
kron calls kron3, kron_t1_t1, kron_t1_t2
poisson_iga_solver_2d calls basis
test_nurbs_surface calls basis