basis – ForCAD
basis Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
55 statements
Source File
private pure subroutine basis(this, res1, res2, Xt1, Xt2, Tgc)
Type Bound
nurbs_surface
Arguments
Type Intent Optional Attributes Name
class(nurbs_surface), intent(inout) :: this
integer, intent(in), optional :: res1
integer, intent(in), optional :: res2
real(kind=rk), intent(in), optional, contiguous :: Xt1(:)
real(kind=rk), intent(in), optional, contiguous :: Xt2(:)
real(kind=rk), intent(out), allocatable :: Tgc(:,:)
Calls
Call graph
basis calls ndgrid, is_rational
ndgrid calls ndgrid2, ndgrid3