basis_scalar – ForCAD
basis_scalar Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
11 statements
Source File
private pure subroutine basis_scalar(this, Xt, Tgc)
Type Bound
nurbs_volume
Arguments
Type Intent Optional Attributes Name
class(nurbs_volume), intent(inout) :: this
real(kind=rk), intent(in), contiguous :: Xt(:)
real(kind=rk), intent(out), allocatable :: Tgc(:)
Calls
Called by
Call graph
basis_scalar calls compute_tgc, is_rational
compute_tgc calls compute_tgc_bspline_3d_scalar, compute_tgc_bspline_3d_vector, compute_tgc_nurbs_3d_scalar, compute_tgc_nurbs_3d_vector
compute_tgc_bspline_3d_scalar calls kron, basis_bspline
compute_tgc_bspline_3d_vector calls kron, basis_bspline
compute_tgc_nurbs_3d_scalar calls kron, basis_bspline
compute_tgc_nurbs_3d_vector calls kron, basis_bspline
kron calls kron3, kron_t1_t1, kron_t1_t2
poisson_iga_solver_3d calls basis
test_nurbs_volume calls basis