basis_bernstein – ForCAD
basis_bernstein Function
Seyed Ali Ghasemi
BSD 3-Clause
18 statements
Source File
public pure function basis_bernstein(Xt, nc) result(B)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: Xt
integer, intent(in) :: nc
Return Value real(kind=rk), allocatable, (:)
Called by
Call graph
create calls basis_bernstein
elevate_degree calls create
example_bezier_curve calls create
example_bezier_surface calls create
example_bezier_volume calls create