basis_bspline_2der_B – ForCAD
basis_bspline_2der_B Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
51 statements
Source File
private pure subroutine basis_bspline_2der_B(Xt, knot, nc, degree, d2B, dB)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: Xt
real(kind=rk), intent(in), contiguous :: knot(:)
integer, intent(in) :: nc
integer, intent(in) :: degree
real(kind=rk), intent(out) :: d2B(nc)
real(kind=rk), intent(out) :: dB(nc)
Called by
Call graph
basis_bspline_2der calls basis_bspline_2der_b
compute_d2tgc_bspline_1d_scalar calls basis_bspline_2der
compute_d2tgc_bspline_1d_vector calls basis_bspline_2der
compute_d2tgc_bspline_2d_scalar calls basis_bspline_2der
compute_d2tgc_bspline_2d_vector calls basis_bspline_2der
compute_d2tgc_bspline_3d_scalar calls basis_bspline_2der
compute_d2tgc_bspline_3d_vector calls basis_bspline_2der
compute_d2tgc_nurbs_1d_scalar calls basis_bspline_2der
compute_d2tgc_nurbs_1d_vector calls basis_bspline_2der
compute_d2tgc_nurbs_2d_scalar calls basis_bspline_2der
compute_d2tgc_nurbs_2d_vector calls basis_bspline_2der
compute_d2tgc_nurbs_3d_scalar calls basis_bspline_2der
compute_d2tgc_nurbs_3d_vector calls basis_bspline_2der
compute_d2tgc calls compute_d2tgc_bspline_3d_scalar, compute_d2tgc_bspline_3d_vector, compute_d2tgc_nurbs_3d_scalar, compute_d2tgc_nurbs_3d_vector, compute_d2tgc_bspline_2d_scalar, compute_d2tgc_bspline_2d_vector, compute_d2tgc_nurbs_2d_scalar, compute_d2tgc_nurbs_2d_vector, compute_d2tgc_bspline_1d_scalar, compute_d2tgc_bspline_1d_vector, compute_d2tgc_nurbs_1d_scalar, compute_d2tgc_nurbs_1d_vector
derivative2_scalar calls compute_d2tgc
derivative2_vector calls compute_d2tgc
nearest_point2 calls derivative2
fdm_test_curve calls derivative2
fdm_test_surface calls derivative2
fdm_test_volume calls derivative2
test_nurbs_curve calls derivative2, nearest_point2
test_nurbs_surface calls derivative2, nearest_point2
test_nurbs_volume calls derivative2, nearest_point2
nearest_point_1d calls nearest_point2
nearest_point_2d calls nearest_point2
nearest_point_3d calls nearest_point2