bend_pipe – ForCAD
bend_pipe Subroutine
BSD 3-Clause
39 statements
Source File
pure subroutine bend_pipe(this, center, length, rbend, angle_deg)
Bend a straight pipe-like NURBS volume into a circular arc. Each control point is transformed relative to the center . Let the total bend angle in degrees be (input), and define the total bend angle in radians For each control point: Mapping: Knots and weights are preserved; only the control lattice is updated.
Arguments
Type Intent Optional Attributes Name
type(nurbs_volume), intent(inout) :: this
NURBS volume to be bent.
real(kind=rk), intent(in) :: center(3)
Pipe center coordinates .
real(kind=rk), intent(in) :: length
Length of the straight pipe segment before bending.
real(kind=rk), intent(in) :: rbend
Bend radius , i.e. distance from the bend centerline.
real(kind=rk), intent(in) :: angle_deg
Bend angle in degrees .
Calls
Called by
Call graph
bend_pipe calls get_knot, get_nc, get_wc, get_xc, set, is_rational
get_nc_dir calls compute_multiplicity
set1 calls cmp_degree, cmp_nc, set
set2 calls cmp_nc, compute_knot_vector, set
set3 calls cmp_degree, set
set4 calls set
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
cmp_degree calls set, get_multiplicity
cmp_nc calls compute_multiplicity, set
compute_knot_vector calls repelem
get_multiplicity calls compute_multiplicity
example_bend_pipe calls bend_pipe