bincoeff – ForCAD
bincoeff Function
Seyed Ali Ghasemi
BSD 3-Clause
5 statements
Source File
private pure elemental function bincoeff(n, k) result(b)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
integer, intent(in) :: k
Return Value real(kind=rk)
Calls
Called by
Call graph
bincoeff calls factln
elevate_degree_a_5_9 calls bincoeff
elevate_degree calls elevate_degree_a_5_9
test_forcad_utils calls elevate_degree_a_5_9
example1_curve calls elevate_degree
example3_surface calls elevate_degree
example3_volume calls elevate_degree
example_bend_pipe calls elevate_degree
example_helix_pipe calls elevate_degree
example_nurbs_surface calls elevate_degree
example_nurbs_volume calls elevate_degree
example_toroidal_pipe calls elevate_degree
fdm_elevate_and_insert_1d calls elevate_degree
fdm_elevate_and_insert_2d calls elevate_degree
fdm_elevate_and_insert_3d calls elevate_degree
test_nurbs_curve calls elevate_degree
test_nurbs_surface calls elevate_degree
test_nurbs_volume calls elevate_degree