build_twist_taper – ForCAD
build_twist_taper Subroutine
BSD 3-Clause
37 statements
Source File
pure subroutine build_twist_taper(this, Length, nc, twist_deg, taper)
Apply a z-progressive twist and linear taper to a NURBS hexahedron.
Let the control points be indexed by along . Define the normalized axial coordinate which varies from 0 at the bottom face to 1 at the top face.
The total twist angle (in radians) at level is i.e. a linear ramp from to .
The in-plane (x–y) taper scale is chosen linear in : so at the bottom and at the top (shrinking if).
For each control point , first shift to the in-plane centroid of the box, apply the scale and rotation by about , and keep unchanged:
Knots are preserved; only the control points are updated.
Arguments
Type Intent Optional Attributes Name
type(nurbs_volume), intent(inout) :: this
Volume to be transformed.
real(kind=rk), intent(in) :: Length(3)
Box lengths .
integer, intent(in) :: nc(3)
Control points sizes.
real(kind=rk), intent(in) :: twist_deg
Total twist at top face (degrees).
real(kind=rk), intent(in) :: taper
In-plane scale at top face (0<taper≤1).
Calls
Called by
Call graph
build_twist_taper calls get_knot, get_wc, get_xc, set, is_rational
set1 calls cmp_degree, cmp_nc, set
set2 calls cmp_nc, compute_knot_vector, set
set3 calls cmp_degree, set
set4 calls set
cmp_degree calls set, get_multiplicity
cmp_nc calls set, compute_multiplicity
compute_knot_vector calls repelem
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
get_multiplicity calls compute_multiplicity
example_twist_taper calls build_twist_taper