build_helix – ForCAD
build_helix Subroutine
BSD 3-Clause
37 statements
Source File
pure subroutine build_helix(this, c, rh, p, n)
Map a straight pipe-like NURBS volume onto a cylindrical helix.
Each control point is first expressed relative to the input center . For the axial (k) index, define a normalized parameter which runs from 0 (start) to 1 (end) along the volume.
The helix angle as a function of is where n is the number of turns. For a point at polar coordinates and , the mapping is: where is the helix radius and is the pitch (axial rise per turn).
Knots are preserved; only the control points are updated.
Arguments
Type Intent Optional Attributes Name
type(nurbs_volume), intent(inout) :: this
NURBS volume to be helicalized.
real(kind=rk), intent(in) :: c(3)
Center , helix radius , pitch .
real(kind=rk), intent(in) :: rh
Center , helix radius , pitch .
real(kind=rk), intent(in) :: p
Center , helix radius , pitch .
integer, intent(in) :: n
Number of turns.
Calls
Called by
Call graph
build_helix calls get_knot, get_nc, get_wc, get_xc, set, is_rational
get_nc_dir calls compute_multiplicity
set1 calls cmp_degree, cmp_nc, set
set2 calls cmp_nc, compute_knot_vector, set
set3 calls cmp_degree, set
set4 calls set
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
cmp_degree calls set, get_multiplicity
cmp_nc calls compute_multiplicity, set
compute_knot_vector calls repelem
get_multiplicity calls compute_multiplicity
example_helix_pipe calls build_helix