cmp_elem_Xc_vis – ForCAD
cmp_elem_Xc_vis Function
Seyed Ali Ghasemi
BSD 3-Clause
11 statements
Source File
private pure function cmp_elem_Xc_vis(this, p) result(elemConn)
Type Bound
nurbs_surface
Arguments
Type Intent Optional Attributes Name
class(nurbs_surface), intent(in) :: this
integer, intent(in), optional, contiguous :: p(:)
Return Value integer, allocatable, (:,:)
Calls
Called by
Call graph
cmp_elem_xc_vis calls elemconn_c0
elemconn_c0 calls cmp_elemconn_c0_l, cmp_elemconn_c0_s, cmp_elemconn_c0_v
export_xc calls cmp_elem_xc_vis
test_nurbs_surface calls cmp_elem_xc_vis, export_xc
example3_surface calls export_xc
example_nurbs_surface calls export_xc
example_plate_hole_1_2d calls export_xc
example_plate_hole_2_2d calls export_xc
example_plate_hole_4_2d calls export_xc
lsq_fit_bspline_2d calls export_xc
poisson_iga_solver_2d calls export_xc
shape_c_2d calls export_xc
shape_half_ring_2d calls export_xc
shape_ring_2d calls export_xc
shape_tetragon calls export_xc