cmp_Tgc_1d – ForCAD
cmp_Tgc_1d Function
Seyed Ali Ghasemi
BSD 3-Clause
14 statements
Source File
private pure function cmp_Tgc_1d(Xti, knot, nc, degree, Wc) result(Tgc)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: Xti
real(kind=rk), intent(in), contiguous :: knot(:)
integer, intent(in) :: nc
integer, intent(in) :: degree
real(kind=rk), intent(in), contiguous :: Wc(:)
Return Value real(kind=rk), (nc)
Calls
Called by
Call graph
cmp_tgc_1d calls basis_bspline
compute_xg_nurbs_1d calls cmp_tgc_1d
compute_xg calls compute_xg_nurbs_1d
cmp_xg calls compute_xg
create calls compute_xg
nearest_point2 calls cmp_xg, create
example1_curve calls create
example_nurbs_curve calls create
fdm_test_curve calls create
lsq_fit_bspline_1d calls create
lsq_fit_nurbs_1d calls create
nearest_point_1d calls create, nearest_point2
shape_c_1d calls create
shape_circle calls create
shape_half_circle calls create
test_nurbs_curve calls create, nearest_point2