cmp_Xg – ForCAD
cmp_Xg Function
Seyed Ali Ghasemi
BSD 3-Clause
17 statements
Source File
private pure function cmp_Xg(this, Xt) result(Xg)
Type Bound
nurbs_volume
Arguments
Type Intent Optional Attributes Name
class(nurbs_volume), intent(in) :: this
real(kind=rk), intent(in), contiguous :: Xt(:)
Return Value real(kind=rk), allocatable, (:)
Calls
Called by
Call graph
cmp_xg calls compute_xg, is_rational
compute_xg calls compute_xg_bspline_3d, compute_xg_bspline_3d_1point, compute_xg_nurbs_3d, compute_xg_nurbs_3d_1point
compute_xg_bspline_3d calls kron, basis_bspline
compute_xg_bspline_3d_1point calls kron, basis_bspline
compute_xg_nurbs_3d calls cmp_tgc_3d
compute_xg_nurbs_3d_1point calls kron, basis_bspline
kron calls kron3, kron_t1_t1, kron_t1_t2
cmp_tgc_3d calls kron, basis_bspline
nearest_point2 calls cmp_xg
nearest_point_3d calls nearest_point2
test_nurbs_volume calls nearest_point2