cmp_Tgc_3d – ForCAD
cmp_Tgc_3d Function
Seyed Ali Ghasemi
BSD 3-Clause
16 statements
Source File
private pure function cmp_Tgc_3d(Xti, knot1, knot2, knot3, nc, degree, Wc) result(Tgc)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: Xti(:)
real(kind=rk), intent(in), contiguous :: knot1(:)
real(kind=rk), intent(in), contiguous :: knot2(:)
real(kind=rk), intent(in), contiguous :: knot3(:)
integer, intent(in) :: nc(3)
integer, intent(in) :: degree(3)
real(kind=rk), intent(in), contiguous :: Wc(:)
Return Value real(kind=rk), (nc(1)*nc(2)*nc(3))
Calls
Called by
Call graph
cmp_tgc_3d calls basis_bspline, kron
compute_xg_nurbs_3d calls cmp_tgc_3d
compute_xg calls compute_xg_nurbs_3d
cmp_xg calls compute_xg
create calls compute_xg
nearest_point2 calls cmp_xg, create
example3_volume calls create
example_nurbs_volume calls create
fdm_test_volume calls create
lsq_fit_bspline_3d calls create
nearest_point_3d calls create, nearest_point2
shape_c_3d calls create
shape_half_ring_3d calls create
shape_hexahedron calls create
shape_ring_3d calls create
test_nurbs_volume calls create, nearest_point2