cmp_length – ForCAD
cmp_length Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
23 statements
Source File
private pure subroutine cmp_length(this, length, ngauss)
Type Bound
nurbs_curve
Arguments
Type Intent Optional Attributes Name
class(nurbs_curve), intent(inout) :: this
real(kind=rk), intent(out) :: length
integer, intent(in), optional :: ngauss
Calls
Called by
Call graph
cmp_length calls ansatz, cmp_elem
ansatz calls cmp_elem, dyad, gauss_leg, unique, derivative, set
cmp_elem calls elemconn_cn, unique, get_multiplicity
dyad calls dyad_t1_t1
elemconn_cn calls cmp_elemconn_cn_l, cmp_elemconn_cn_s, cmp_elemconn_cn_v
gauss_leg calls gauss_legendre_1d, gauss_legendre_2d, gauss_legendre_3d
unique calls unique_integer, unique_real
get_multiplicity calls compute_multiplicity
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
derivative_scalar calls compute_dtgc, is_rational
derivative_vector calls compute_dtgc, is_rational
gauss_legendre_1d calls gauss_legendre
gauss_legendre_2d calls kron, ndgrid, gauss_legendre
gauss_legendre_3d calls kron, ndgrid, gauss_legendre
set1a calls cmp_degree, set
set1 calls cmp_degree, set
set2 calls cmp_nc, compute_knot_vector, set
set3 calls cmp_degree, set
set4 calls set
compute_dtgc calls compute_dtgc_bspline_1d_scalar, compute_dtgc_bspline_1d_vector, compute_dtgc_nurbs_1d_scalar, compute_dtgc_nurbs_1d_vector
kron calls kron3, kron_t1_t1, kron_t1_t2
ndgrid calls ndgrid2, ndgrid3
cmp_degree calls get_multiplicity
cmp_nc calls compute_multiplicity
compute_knot_vector calls repelem
compute_dtgc_bspline_1d_scalar calls basis_bspline_der
compute_dtgc_bspline_1d_vector calls basis_bspline_der
compute_dtgc_nurbs_1d_scalar calls basis_bspline_der
compute_dtgc_nurbs_1d_vector calls basis_bspline_der
basis_bspline_der calls basis_bspline_der_a, basis_bspline_der_b
compute_length calls cmp_length
test_nurbs_curve calls cmp_length