cmp_elem – ForCAD
cmp_elem Function
Seyed Ali Ghasemi
BSD 3-Clause
5 statements
Source File
private pure function cmp_elem(this) result(elemConn)
Type Bound
nurbs_curve
Arguments
Type Intent Optional Attributes Name
class(nurbs_curve), intent(in) :: this
Return Value integer, allocatable, (:,:)
Calls
Called by
Call graph
cmp_elem calls elemconn_cn, unique, get_multiplicity
elemconn_cn calls cmp_elemconn_cn_l, cmp_elemconn_cn_s, cmp_elemconn_cn_v
unique calls unique_integer, unique_real
get_multiplicity calls compute_multiplicity
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
ansatz calls cmp_elem
cmp_length calls cmp_elem, ansatz
export_xth calls cmp_elem
test_nurbs_curve calls cmp_elem, cmp_length, export_xth
compute_length calls cmp_length
example1_curve calls export_xth