cmp_elem – ForCAD
cmp_elem Function
Seyed Ali Ghasemi
BSD 3-Clause
5 statements
Source File
private pure function cmp_elem(this) result(elemConn)
Type Bound
nurbs_volume
Arguments
Type Intent Optional Attributes Name
class(nurbs_volume), intent(in) :: this
Return Value integer, allocatable, (:,:)
Calls
Called by
Call graph
cmp_elem calls elemconn_cn, unique, get_multiplicity
elemconn_cn calls cmp_elemconn_cn_l, cmp_elemconn_cn_s, cmp_elemconn_cn_v
unique calls unique_integer, unique_real
get_multiplicity calls compute_multiplicity
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
ansatz calls cmp_elem
cmp_volume calls cmp_elem, ansatz
export_xth calls cmp_elem
example3_volume calls cmp_elem, export_xth
test_nurbs_volume calls cmp_elem, cmp_volume, export_xth
compute_volume calls cmp_volume