cmp_nc – ForCAD
cmp_nc Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
51 statements
Source File
private pure subroutine cmp_nc(this, dir)
Type Bound
nurbs_volume
Arguments
Type Intent Optional Attributes Name
class(nurbs_volume), intent(inout) :: this
integer, intent(in), optional :: dir
Calls
Called by
Call graph
cmp_nc calls compute_multiplicity, set
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
set1 calls cmp_nc
set2 calls cmp_nc
test_nurbs_volume calls cmp_nc, set, elevate_degree, modify_wc, modify_xc, remove_knots, set_c, set_half_ring, set_hexahedron, set_ring, cmp_volume
ansatz calls set
bend_pipe calls set
build_helix calls set
build_twist_taper calls set
elevate_degree calls set
map_to_torus_sinez calls set
modify_wc calls set
modify_xc calls set
remove_knots calls set
set_c calls set
set_half_ring calls set
set_hexahedron calls set
set_ring calls set
compute_volume calls set, cmp_volume
example3_volume calls set, elevate_degree, remove_knots
example_nurbs_volume calls set, elevate_degree
example_put_to_nurbs calls set
fdm_elevate_and_insert_3d calls set, elevate_degree
lsq_fit_bspline_3d calls set
nearest_point_3d calls set
cmp_volume calls ansatz
example_bend_pipe calls bend_pipe, elevate_degree, set_ring
example_helix_pipe calls build_helix, elevate_degree, set_ring
example_toroidal_pipe calls elevate_degree, map_to_torus_sinez, set_ring
example_twist_taper calls build_twist_taper, set_hexahedron
fdm_test_volume calls set_hexahedron
poisson_iga_solver_3d calls ansatz, set_hexahedron
shape_c_3d calls set_c
shape_half_ring_3d calls set_half_ring
shape_hexahedron calls set_hexahedron
shape_ring_3d calls set_ring