cmp_elem_Xc_vis – ForCAD
cmp_elem_Xc_vis Function
Seyed Ali Ghasemi
BSD 3-Clause
11 statements
Source File
private pure function cmp_elem_Xc_vis(this, p) result(elemConn)
Type Bound
nurbs_volume
Arguments
Type Intent Optional Attributes Name
class(nurbs_volume), intent(in) :: this
integer, intent(in), optional, contiguous :: p(:)
Return Value integer, allocatable, (:,:)
Calls
Called by
Call graph
cmp_elem_xc_vis calls elemconn_c0
elemconn_c0 calls cmp_elemconn_c0_l, cmp_elemconn_c0_s, cmp_elemconn_c0_v
export_xc calls cmp_elem_xc_vis
test_nurbs_volume calls cmp_elem_xc_vis, export_xc
example3_volume calls export_xc
example_bend_pipe calls export_xc
example_helix_pipe calls export_xc
example_nurbs_volume calls export_xc
example_plate_hole_1_3d calls export_xc
example_plate_hole_2_3d calls export_xc
example_plate_hole_4_3d calls export_xc
example_put_to_nurbs calls export_xc
example_toroidal_pipe calls export_xc
example_twist_taper calls export_xc
lsq_fit_bspline_3d calls export_xc
poisson_iga_solver_3d calls export_xc
shape_c_3d calls export_xc
shape_half_ring_3d calls export_xc
shape_hexahedron calls export_xc
shape_ring_3d calls export_xc