cmp_elemConn_Cn_V – ForCAD
cmp_elemConn_Cn_V Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
35 statements
Source File
private pure subroutine cmp_elemConn_Cn_V(nnode1, nnode2, nnode3, p1, p2, p3, Xth1, Xth2, Xth3, vecKnot_mul1, vecKnot_mul2, vecKnot_mul3, elemConn)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nnode1
integer, intent(in) :: nnode2
integer, intent(in) :: nnode3
integer, intent(in) :: p1
integer, intent(in) :: p2
integer, intent(in) :: p3
real(kind=rk), intent(in), contiguous :: Xth1(:)
real(kind=rk), intent(in), contiguous :: Xth2(:)
real(kind=rk), intent(in), contiguous :: Xth3(:)
integer, intent(in), contiguous :: vecKnot_mul1(:)
integer, intent(in), contiguous :: vecKnot_mul2(:)
integer, intent(in), contiguous :: vecKnot_mul3(:)
integer, intent(out), allocatable :: elemConn(:,:)
Called by
Call graph
elemconn_cn calls cmp_elemconn_cn_v
cmp_elem calls elemconn_cn
ansatz calls cmp_elem
cmp_area calls cmp_elem, ansatz
cmp_length calls cmp_elem, ansatz
cmp_volume calls cmp_elem, ansatz
export_xth calls cmp_elem
example3_volume calls cmp_elem, export_xth
poisson_iga_solver_2d calls cmp_elem, ansatz
poisson_iga_solver_3d calls cmp_elem, ansatz
test_nurbs_curve calls cmp_elem, cmp_length, export_xth
test_nurbs_surface calls cmp_elem, cmp_area, export_xth
test_nurbs_volume calls cmp_elem, cmp_volume, export_xth
compute_area calls cmp_area
compute_length calls cmp_length
compute_volume calls cmp_volume
example1_curve calls export_xth
example3_surface calls export_xth