cmp_elem_Xth – ForCAD
cmp_elem_Xth Function
Seyed Ali Ghasemi
BSD 3-Clause
11 statements
Source File
private pure function cmp_elem_Xth(this, p) result(elemConn)
Type Bound
nurbs_surface
Arguments
Type Intent Optional Attributes Name
class(nurbs_surface), intent(in) :: this
integer, intent(in), optional, contiguous :: p(:)
Return Value integer, allocatable, (:,:)
Calls
Called by
Call graph
cmp_elem_xth calls elemconn_c0, unique
elemconn_c0 calls cmp_elemconn_c0_l, cmp_elemconn_c0_s, cmp_elemconn_c0_v
unique calls unique_integer, unique_real
export_xth calls cmp_elem_xth
example3_surface calls export_xth
test_nurbs_surface calls export_xth