cmp_volume – ForCAD
cmp_volume Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
24 statements
Source File
private pure subroutine cmp_volume(this, volume, ngauss)
Type Bound
nurbs_volume
Arguments
Type Intent Optional Attributes Name
class(nurbs_volume), intent(inout) :: this
real(kind=rk), intent(out) :: volume
integer, intent(in), optional :: ngauss(3)
Calls
Called by
Call graph
cmp_volume calls ansatz, cmp_elem, reduce
ansatz calls cmp_elem, gauss_leg, ndgrid, unique, derivative, set, det, inv
cmp_elem calls elemconn_cn, unique, get_multiplicity
elemconn_cn calls cmp_elemconn_cn_l, cmp_elemconn_cn_s, cmp_elemconn_cn_v
gauss_leg calls gauss_legendre_1d, gauss_legendre_2d, gauss_legendre_3d
ndgrid calls ndgrid2, ndgrid3
unique calls unique_integer, unique_real
get_multiplicity calls compute_multiplicity
inv calls det, inv, eye, solve
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
derivative_scalar calls compute_dtgc, is_rational
derivative_vector calls ndgrid, compute_dtgc, is_rational
gauss_legendre_1d calls gauss_legendre
gauss_legendre_2d calls ndgrid, kron, gauss_legendre
gauss_legendre_3d calls ndgrid, kron, gauss_legendre
set1 calls cmp_degree, cmp_nc, set
set2 calls cmp_nc, compute_knot_vector, set
set3 calls cmp_degree, set
set4 calls set
compute_dtgc calls compute_dtgc_bspline_3d_scalar, compute_dtgc_bspline_3d_vector, compute_dtgc_nurbs_3d_scalar, compute_dtgc_nurbs_3d_vector
kron calls kron3, kron_t1_t1, kron_t1_t2
cmp_degree calls get_multiplicity, set
cmp_nc calls compute_multiplicity, set
compute_knot_vector calls repelem
compute_dtgc_bspline_3d_scalar calls kron, basis_bspline_der
compute_dtgc_bspline_3d_vector calls kron, basis_bspline_der
compute_dtgc_nurbs_3d_scalar calls kron, basis_bspline_der
compute_dtgc_nurbs_3d_vector calls kron, basis_bspline_der
basis_bspline_der calls basis_bspline_der_a, basis_bspline_der_b
compute_volume calls cmp_volume
test_nurbs_volume calls cmp_volume