compute_Tgc_nurbs_3d_vector – ForCAD
compute_Tgc_nurbs_3d_vector Function
Seyed Ali Ghasemi
BSD 3-Clause
17 statements
Source File
private pure function compute_Tgc_nurbs_3d_vector(Xt, knot1, knot2, knot3, degree, nc, ng, Wc) result(Tgc)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: Xt(:,:)
real(kind=rk), intent(in), contiguous :: knot1(:)
real(kind=rk), intent(in), contiguous :: knot2(:)
real(kind=rk), intent(in), contiguous :: knot3(:)
integer, intent(in) :: degree(3)
integer, intent(in) :: nc(3)
integer, intent(in) :: ng(3)
real(kind=rk), intent(in), contiguous :: Wc(:)
Return Value real(kind=rk), allocatable, (:,:)
Calls
Called by
Call graph
compute_tgc_nurbs_3d_vector calls basis_bspline, kron
compute_tgc calls compute_tgc_nurbs_3d_vector
basis_scalar calls compute_tgc
basis_vector calls compute_tgc
test_nurbs_volume calls basis