compute_knot_vector – ForCAD
compute_knot_vector Function
Seyed Ali Ghasemi
BSD 3-Clause
7 statements
Source File
public pure function compute_knot_vector(Xth_dir, degree, continuity) result(knot)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: Xth_dir(:)
integer, intent(in) :: degree
integer, intent(in), contiguous :: continuity(:)
Return Value real(kind=rk), allocatable, (:)
Calls
Called by
Call graph
compute_knot_vector calls repelem
set2 calls compute_knot_vector
test_forcad_utils calls compute_knot_vector
ansatz calls set
bend_pipe calls set
build_helix calls set
build_twist_taper calls set
elevate_degree calls set
insert_knots calls set
map_to_torus_sinez calls set
modify_wc calls set
modify_xc calls set
remove_knots calls set
set_c calls set
set_circle calls set
set_half_circle calls set
set_half_ring calls set
set_hexahedron calls set
set_ring calls set
set_tetragon calls set
compute_area calls set, cmp_area
compute_length calls set, cmp_length
compute_volume calls set, cmp_volume
example1_curve calls set, elevate_degree, insert_knots, remove_knots
example3_surface calls set, elevate_degree, remove_knots
example3_volume calls set, elevate_degree, remove_knots
example_nurbs_curve calls set
example_nurbs_surface calls set, elevate_degree
example_nurbs_volume calls set, elevate_degree
example_plate_hole_1_2d calls set
example_plate_hole_1_3d calls set
example_plate_hole_2_2d calls set
example_plate_hole_2_3d calls set
example_plate_hole_4_2d calls set
example_plate_hole_4_3d calls set
example_put_to_nurbs calls set
fdm_elevate_and_insert_1d calls set, elevate_degree, insert_knots
fdm_elevate_and_insert_2d calls set, elevate_degree
fdm_elevate_and_insert_3d calls set, elevate_degree
fdm_test_curve calls set
lsq_fit_bspline_1d calls set
lsq_fit_bspline_2d calls set
lsq_fit_bspline_3d calls set
lsq_fit_nurbs_1d calls set
lsq_fit_nurbs_2d calls set
lsq_fit_nurbs_3d calls set
nearest_point_1d calls set
nearest_point_2d calls set
nearest_point_3d calls set
test_nurbs_curve calls set, elevate_degree, insert_knots, modify_wc, modify_xc, remove_knots, set_circle, set_half_circle, cmp_length
test_nurbs_surface calls set, elevate_degree, modify_wc, modify_xc, remove_knots, set_c, set_half_ring, set_ring, set_tetragon, cmp_area
test_nurbs_volume calls set, elevate_degree, modify_wc, modify_xc, remove_knots, set_c, set_half_ring, set_hexahedron, set_ring, cmp_volume
cmp_area calls ansatz
cmp_length calls ansatz
cmp_volume calls ansatz
example_bend_pipe calls bend_pipe, elevate_degree, set_ring
example_helix_pipe calls build_helix, elevate_degree, set_ring
example_ppm1 calls set_ring, set_tetragon
example_ppm2 calls set_half_ring, set_tetragon
example_ppm3 calls modify_xc, set_tetragon
example_toroidal_pipe calls elevate_degree, map_to_torus_sinez, set_ring
example_twist_taper calls build_twist_taper, set_hexahedron
fdm_test_surface calls set_tetragon
fdm_test_volume calls set_hexahedron
nearest_point_2d_bench calls set_tetragon
poisson_iga_solver_2d calls ansatz, set_tetragon
poisson_iga_solver_3d calls ansatz, set_hexahedron
shape_c_1d calls set_c
shape_c_2d calls set_c
shape_c_3d calls set_c
shape_circle calls set_circle
shape_half_circle calls set_half_circle
shape_half_ring_2d calls set_half_ring
shape_half_ring_3d calls set_half_ring
shape_hexahedron calls set_hexahedron
shape_ring_2d calls set_ring
shape_ring_3d calls set_ring
shape_tetragon calls set_tetragon