compute_d2Tgc_nurbs_1d_vector – ForCAD
compute_d2Tgc_nurbs_1d_vector Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
22 statements
Source File
private pure subroutine compute_d2Tgc_nurbs_1d_vector(Xt, knot, degree, nc, ng, Wc, d2Tgc, dTgc, Tgc)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: Xt(:)
real(kind=rk), intent(in), contiguous :: knot(:)
integer, intent(in) :: degree
integer, intent(in) :: nc
integer, intent(in) :: ng
real(kind=rk), intent(in), contiguous :: Wc(:)
real(kind=rk), intent(out), allocatable :: d2Tgc(:,:)
real(kind=rk), intent(out), allocatable :: dTgc(:,:)
real(kind=rk), intent(out), allocatable :: Tgc(:,:)
Calls
Called by
Call graph
compute_d2tgc_nurbs_1d_vector calls basis_bspline_2der
basis_bspline_2der calls basis_bspline_2der_a, basis_bspline_2der_b, basis_bspline_2der_c
compute_d2tgc calls compute_d2tgc_nurbs_1d_vector
derivative2_scalar calls compute_d2tgc
derivative2_vector calls compute_d2tgc
nearest_point2 calls derivative2
fdm_test_curve calls derivative2
test_nurbs_curve calls derivative2, nearest_point2
nearest_point_1d calls nearest_point2