compute_Tgc_bspline_3d_scalar – ForCAD
compute_Tgc_bspline_3d_scalar Function
Seyed Ali Ghasemi
BSD 3-Clause
9 statements
Source File
private pure function compute_Tgc_bspline_3d_scalar(Xt, knot1, knot2, knot3, degree, nc) result(Tgc)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: Xt(:)
real(kind=rk), intent(in), contiguous :: knot1(:)
real(kind=rk), intent(in), contiguous :: knot2(:)
real(kind=rk), intent(in), contiguous :: knot3(:)
integer, intent(in) :: degree(3)
integer, intent(in) :: nc(3)
Return Value real(kind=rk), allocatable, (:)
Calls
Called by
Call graph
compute_tgc_bspline_3d_scalar calls kron, basis_bspline
kron calls kron3, kron_t1_t1, kron_t1_t2
compute_tgc calls compute_tgc_bspline_3d_scalar
basis_scalar calls compute_tgc
basis_vector calls compute_tgc
poisson_iga_solver_3d calls basis
test_nurbs_volume calls basis