compute_dTgc_bspline_1d_scalar – ForCAD
compute_dTgc_bspline_1d_scalar Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
19 statements
Source File
private pure subroutine compute_dTgc_bspline_1d_scalar(Xt, knot, degree, nc, dTgc, Tgc, elem)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: Xt
real(kind=rk), intent(in), contiguous :: knot(:)
integer, intent(in) :: degree
integer, intent(in) :: nc
real(kind=rk), intent(out), allocatable :: dTgc(:)
real(kind=rk), intent(out), allocatable :: Tgc(:)
integer, intent(in), optional :: elem(:)
Calls
Called by
Call graph
compute_dtgc_bspline_1d_scalar calls basis_bspline_der
compute_dtgc calls compute_dtgc_bspline_1d_scalar
derivative_scalar calls compute_dtgc
derivative_vector calls compute_dtgc
ansatz calls derivative
test_nurbs_curve calls derivative, cmp_length
cmp_length calls ansatz
compute_length calls cmp_length