compute_d2Tgc_bspline_3d_vector – ForCAD
compute_d2Tgc_bspline_3d_vector Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
40 statements
Source File
private pure subroutine compute_d2Tgc_bspline_3d_vector(Xt, knot1, knot2, knot3, degree, nc, ng, d2Tgc, dTgc, Tgc)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: Xt(:,:)
real(kind=rk), intent(in), contiguous :: knot1(:)
real(kind=rk), intent(in), contiguous :: knot2(:)
real(kind=rk), intent(in), contiguous :: knot3(:)
integer, intent(in) :: degree(3)
integer, intent(in) :: nc(3)
integer, intent(in), optional :: ng(3)
real(kind=rk), intent(out), allocatable :: d2Tgc(:,:,:)
real(kind=rk), intent(out), allocatable :: dTgc(:,:,:)
real(kind=rk), intent(out), allocatable :: Tgc(:,:)
Calls
Called by
Call graph
compute_d2tgc_bspline_3d_vector calls basis_bspline_2der, kron
basis_bspline_2der calls basis_bspline_2der_a, basis_bspline_2der_b, basis_bspline_2der_c
kron calls kron3, kron_t1_t1, kron_t1_t2
compute_d2tgc calls compute_d2tgc_bspline_3d_vector
derivative2_scalar calls compute_d2tgc
derivative2_vector calls compute_d2tgc
nearest_point2 calls derivative2
fdm_test_volume calls derivative2
test_nurbs_volume calls derivative2, nearest_point2
nearest_point_3d calls nearest_point2