compute_Xg_nurbs_3d_1point – ForCAD
compute_Xg_nurbs_3d_1point Function
Seyed Ali Ghasemi
BSD 3-Clause
14 statements
Source File
private pure function compute_Xg_nurbs_3d_1point(Xt, knot1, knot2, knot3, degree, nc, Xc, Wc) result(Xg)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: Xt(:)
real(kind=rk), intent(in), contiguous :: knot1(:)
real(kind=rk), intent(in), contiguous :: knot2(:)
real(kind=rk), intent(in), contiguous :: knot3(:)
integer, intent(in) :: degree(3)
integer, intent(in) :: nc(3)
real(kind=rk), intent(in), contiguous :: Xc(:,:)
real(kind=rk), intent(in), contiguous :: Wc(:)
Return Value real(kind=rk), (size(Xc,2))
Calls
Called by
Call graph
compute_xg_nurbs_3d_1point calls kron, basis_bspline
kron calls kron3, kron_t1_t1, kron_t1_t2
compute_xg calls compute_xg_nurbs_3d_1point
cmp_xg calls compute_xg
create calls compute_xg
export_xth_in_xg calls compute_xg
put_to_nurbs calls compute_xg
nearest_point2 calls cmp_xg, create
example3_volume calls create
example_bend_pipe calls create, export_xth_in_xg
example_helix_pipe calls create, export_xth_in_xg
example_nurbs_volume calls create, export_xth_in_xg
example_put_to_nurbs calls put_to_nurbs
example_toroidal_pipe calls create, export_xth_in_xg
example_twist_taper calls create, export_xth_in_xg
fdm_test_volume calls create
lsq_fit_bspline_3d calls create
nearest_point_3d calls create, nearest_point2
poisson_iga_solver_3d calls create
shape_c_3d calls create
shape_half_ring_3d calls create
shape_hexahedron calls create
shape_ring_3d calls create
test_nurbs_volume calls create, nearest_point2