compute_Xg_nurbs_1d – ForCAD
compute_Xg_nurbs_1d Function
Seyed Ali Ghasemi
BSD 3-Clause
20 statements
Source File
private pure function compute_Xg_nurbs_1d(Xt, knot, degree, nc, ng, Xc, Wc) result(Xg)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: Xt(:)
real(kind=rk), intent(in), contiguous :: knot(:)
integer, intent(in) :: degree
integer, intent(in) :: nc
integer, intent(in), optional :: ng
real(kind=rk), intent(in), contiguous :: Xc(:,:)
real(kind=rk), intent(in), contiguous :: Wc(:)
Return Value real(kind=rk), allocatable, (:,:)
Calls
Called by
Call graph
compute_xg_nurbs_1d calls cmp_tgc_1d
cmp_tgc_1d calls basis_bspline
compute_xg calls compute_xg_nurbs_1d
cmp_xg calls compute_xg
create calls compute_xg
nearest_point2 calls cmp_xg, create
example1_curve calls create
example_nurbs_curve calls create
fdm_test_curve calls create
lsq_fit_bspline_1d calls create
nearest_point_1d calls create, nearest_point2
shape_c_1d calls create
shape_circle calls create
shape_half_circle calls create
test_nurbs_curve calls create, nearest_point2