compute_dTgc_nurbs_3d_vector – ForCAD
compute_dTgc_nurbs_3d_vector Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
30 statements
Source File
private pure subroutine compute_dTgc_nurbs_3d_vector(Xt, knot1, knot2, knot3, degree, nc, ng, Wc, dTgc, Tgc)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: Xt(:,:)
real(kind=rk), intent(in), contiguous :: knot1(:)
real(kind=rk), intent(in), contiguous :: knot2(:)
real(kind=rk), intent(in), contiguous :: knot3(:)
integer, intent(in) :: degree(3)
integer, intent(in) :: nc(3)
integer, intent(in) :: ng(3)
real(kind=rk), intent(in), contiguous :: Wc(:)
real(kind=rk), intent(out), allocatable :: dTgc(:,:,:)
real(kind=rk), intent(out), allocatable :: Tgc(:,:)
Calls
Called by
Call graph
compute_dtgc_nurbs_3d_vector calls basis_bspline_der, kron
compute_dtgc calls compute_dtgc_nurbs_3d_vector
derivative_scalar calls compute_dtgc
derivative_vector calls compute_dtgc
ansatz calls derivative
test_nurbs_volume calls derivative, cmp_volume
cmp_volume calls ansatz
compute_volume calls cmp_volume