compute_Tgc_nurbs_1d_scalar – ForCAD
compute_Tgc_nurbs_1d_scalar Function
Seyed Ali Ghasemi
BSD 3-Clause
11 statements
Source File
private pure function compute_Tgc_nurbs_1d_scalar(Xt, knot, degree, nc, Wc) result(Tgc)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: Xt
real(kind=rk), intent(in), contiguous :: knot(:)
integer, intent(in) :: degree
integer, intent(in) :: nc
real(kind=rk), intent(in), contiguous :: Wc(:)
Return Value real(kind=rk), allocatable, (:)
Calls
Called by
Call graph
compute_tgc_nurbs_1d_scalar calls basis_bspline
compute_tgc calls compute_tgc_nurbs_1d_scalar
basis_scalar calls compute_tgc
basis_vector calls compute_tgc
test_nurbs_curve calls basis