compute_dTgc_bspline_2d_scalar – ForCAD
compute_dTgc_bspline_2d_scalar Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
28 statements
Source File
private pure subroutine compute_dTgc_bspline_2d_scalar(Xt, knot1, knot2, degree, nc, dTgc, Tgc, elem)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: Xt(:)
real(kind=rk), intent(in), contiguous :: knot1(:)
real(kind=rk), intent(in), contiguous :: knot2(:)
integer, intent(in) :: degree(2)
integer, intent(in) :: nc(2)
real(kind=rk), intent(out), allocatable :: dTgc(:,:)
real(kind=rk), intent(out), allocatable :: Tgc(:)
integer, intent(in), optional, contiguous :: elem(:)
Calls
Called by
Call graph
compute_dtgc_bspline_2d_scalar calls basis_bspline_der, kron
basis_bspline_der calls basis_bspline_der_a, basis_bspline_der_b
kron calls kron3, kron_t1_t1, kron_t1_t2
compute_dtgc calls compute_dtgc_bspline_2d_scalar
derivative_scalar calls compute_dtgc
derivative_vector calls compute_dtgc
ansatz calls derivative
test_nurbs_surface calls derivative, cmp_area
cmp_area calls ansatz
poisson_iga_solver_2d calls ansatz
compute_area calls cmp_area