compute_Xg_bspline_2d – ForCAD
compute_Xg_bspline_2d Function
Seyed Ali Ghasemi
BSD 3-Clause
19 statements
Source File
private pure function compute_Xg_bspline_2d(Xt, knot1, knot2, degree, nc, ng, Xc) result(Xg)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: Xt(:,:)
real(kind=rk), intent(in), contiguous :: knot1(:)
real(kind=rk), intent(in), contiguous :: knot2(:)
integer, intent(in) :: degree(2)
integer, intent(in) :: nc(2)
integer, intent(in), optional :: ng(2)
real(kind=rk), intent(in), contiguous :: Xc(:,:)
Return Value real(kind=rk), allocatable, (:,:)
Calls
Called by
Call graph
compute_xg_bspline_2d calls kron, basis_bspline
kron calls kron3, kron_t1_t1, kron_t1_t2
compute_xg calls compute_xg_bspline_2d
cmp_xg calls compute_xg
create calls compute_xg
export_xth_in_xg calls compute_xg
nearest_point2 calls cmp_xg, create
example3_surface calls create
example_nurbs_surface calls create, export_xth_in_xg
example_plate_hole_1_2d calls create, export_xth_in_xg
example_plate_hole_2_2d calls create, export_xth_in_xg
example_plate_hole_4_2d calls create, export_xth_in_xg
example_ppm1 calls create
example_ppm2 calls create
example_ppm3 calls create
fdm_test_surface calls create
lsq_fit_bspline_2d calls create, export_xth_in_xg
lsq_fit_nurbs_2d calls create, export_xth_in_xg
nearest_point_2d calls create, nearest_point2
nearest_point_2d_bench calls create
poisson_iga_solver_2d calls create
shape_c_2d calls create
shape_half_ring_2d calls create
shape_ring_2d calls create
shape_tetragon calls create
test_nurbs_surface calls create, nearest_point2