create – ForCAD
create Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
52 statements
Source File
private pure subroutine create(this, res1, res2, Xt1, Xt2)
Type Bound
bezier_surface
Arguments
Type Intent Optional Attributes Name
class(bezier_surface), intent(inout) :: this
integer, intent(in), optional :: res1
integer, intent(in), optional :: res2
real(kind=rk), intent(in), optional :: Xt1(:)
real(kind=rk), intent(in), optional :: Xt2(:)
Calls
Called by
Source Code
    pure subroutine create(this, res1, res2, Xt1, Xt2)
        class(bezier_surface), intent(inout) :: this
        integer, intent(in), optional :: res1, res2
        real(rk), intent(in), optional :: Xt1(:), Xt2(:)
        integer :: i, j
        real(rk), dimension(:), allocatable :: Tgc1, Tgc2, Tgc
        real(rk), dimension(:,:), allocatable :: Xt
        ! check
        if (.not.allocated(this%Xc)) then
            error stop 'Control points are not set.'
        end if
        ! Set parameter values
        if (present(Xt1)) then
            if (allocated(this%Xt1)) deallocate(this%Xt1)
            this%Xt1 = Xt1
        elseif (present(res1)) then
            if (allocated(this%Xt1)) deallocate(this%Xt1)
            allocate(this%Xt1(res1))
            this%Xt1 = [(real(i-1, rk) / real(res1-1, rk), i=1, res1)]
            ! else
            ! this%Xt1 = this%Xt1
        end if
        ! Set parameter values
        if (present(Xt2)) then
            if (allocated(this%Xt2)) deallocate(this%Xt2)
            this%Xt2 = Xt2
        elseif (present(res2)) then
            if (allocated(this%Xt2)) deallocate(this%Xt2)
            allocate(this%Xt2(res2))
            this%Xt2 = [(real(i-1, rk) / real(res2-1, rk), i=1, res2)]
            ! else
            ! this%Xt2 = this%Xt2
        end if
        ! Set number of geometry points
        this%ng(1) = size(this%Xt1,1)
        this%ng(2) = size(this%Xt2,1)
        call ndgrid(this%Xt1, this%Xt2, Xt)
        if (allocated(this%Xg)) deallocate(this%Xg)
        allocate(this%Xg(this%ng(1)*this%ng(2), size(this%Xc,2)))
        if (allocated(this%Wc)) then ! Rational Bezier surface
            do i = 1, size(Xt, 1)
                Tgc1 = basis_bernstein(Xt(i,1), this%nc(1))
                Tgc2 = basis_bernstein(Xt(i,2), this%nc(2))
                Tgc = kron(Tgc2, Tgc1)
                Tgc = Tgc*(this%Wc/(dot_product(Tgc,this%Wc)))
                do j = 1, size(this%Xc, 2)
                    this%Xg(i,j) = dot_product(Tgc,this%Xc(:,j))
                end do
            end do
        else ! Non-rational Bezier surface
            do i = 1, size(Xt, 1)
                Tgc1 = basis_bernstein(Xt(i,1), this%nc(1))
                Tgc2 = basis_bernstein(Xt(i,2), this%nc(2))
                Tgc = kron(Tgc2, Tgc1)
                do j = 1, size(this%Xc, 2)
                    this%Xg(i,j) = dot_product(Tgc,this%Xc(:,j))
                end do
            end do
        end if
    end subroutine create
Call graph
create calls ndgrid, basis_bernstein, kron
ndgrid calls ndgrid2, ndgrid3
example_bezier_surface calls create