create – ForCAD
create Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
65 statements
Source File
private pure subroutine create(this, res1, res2, Xt1, Xt2, Xt)
Type Bound
nurbs_surface
Arguments
Type Intent Optional Attributes Name
class(nurbs_surface), intent(inout) :: this
integer, intent(in), optional :: res1
integer, intent(in), optional :: res2
real(kind=rk), intent(in), optional, contiguous :: Xt1(:)
real(kind=rk), intent(in), optional, contiguous :: Xt2(:)
real(kind=rk), intent(in), optional, contiguous :: Xt(:,:)
Calls
Called by
Call graph
create calls compute_xg, ndgrid, is_rational, set
compute_xg calls compute_xg_bspline_2d, compute_xg_bspline_2d_1point, compute_xg_nurbs_2d, compute_xg_nurbs_2d_1point
ndgrid calls ndgrid2, ndgrid3
compute_xg_bspline_2d calls kron, basis_bspline
compute_xg_bspline_2d_1point calls kron, basis_bspline
compute_xg_nurbs_2d calls cmp_tgc_2d
compute_xg_nurbs_2d_1point calls kron, basis_bspline
kron calls kron3, kron_t1_t1, kron_t1_t2
cmp_tgc_2d calls kron, basis_bspline
nearest_point2 calls create
example3_surface calls create
example_nurbs_surface calls create
example_plate_hole_1_2d calls create
example_plate_hole_2_2d calls create
example_plate_hole_4_2d calls create
example_ppm1 calls create
example_ppm2 calls create
example_ppm3 calls create
fdm_test_surface calls create
lsq_fit_bspline_2d calls create
lsq_fit_nurbs_2d calls create
nearest_point_2d calls create, nearest_point2
nearest_point_2d_bench calls create
poisson_iga_solver_2d calls create
shape_c_2d calls create
shape_half_ring_2d calls create
shape_ring_2d calls create
shape_tetragon calls create
test_nurbs_surface calls create, nearest_point2