create – ForCAD
create Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
85 statements
Source File
private pure subroutine create(this, res1, res2, res3, Xt1, Xt2, Xt3, Xt)
Type Bound
nurbs_volume
Arguments
Type Intent Optional Attributes Name
class(nurbs_volume), intent(inout) :: this
integer, intent(in), optional :: res1
integer, intent(in), optional :: res2
integer, intent(in), optional :: res3
real(kind=rk), intent(in), optional, contiguous :: Xt1(:)
real(kind=rk), intent(in), optional, contiguous :: Xt2(:)
real(kind=rk), intent(in), optional, contiguous :: Xt3(:)
real(kind=rk), intent(in), optional, contiguous :: Xt(:,:)
Calls
Called by
Call graph
create calls compute_xg, ndgrid, is_rational, set
compute_xg calls compute_xg_bspline_3d, compute_xg_bspline_3d_1point, compute_xg_nurbs_3d, compute_xg_nurbs_3d_1point
ndgrid calls ndgrid2, ndgrid3
compute_xg_bspline_3d calls kron, basis_bspline
compute_xg_bspline_3d_1point calls kron, basis_bspline
compute_xg_nurbs_3d calls cmp_tgc_3d
compute_xg_nurbs_3d_1point calls kron, basis_bspline
kron calls kron3, kron_t1_t1, kron_t1_t2
cmp_tgc_3d calls kron, basis_bspline
nearest_point2 calls create
example3_volume calls create
example_nurbs_volume calls create
fdm_test_volume calls create
lsq_fit_bspline_3d calls create
nearest_point_3d calls create, nearest_point2
poisson_iga_solver_3d calls create
shape_c_3d calls create
shape_half_ring_3d calls create
shape_hexahedron calls create
shape_ring_3d calls create
test_nurbs_volume calls create, nearest_point2