derivative_vector – ForCAD
derivative_vector Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
42 statements
Source File
private pure subroutine derivative_vector(this, res1, res2, res3, Xt1, Xt2, Xt3, dTgc, Tgc)
Type Bound
nurbs_volume
Arguments
Type Intent Optional Attributes Name
class(nurbs_volume), intent(inout) :: this
integer, intent(in), optional :: res1
integer, intent(in), optional :: res2
integer, intent(in), optional :: res3
real(kind=rk), intent(in), optional, contiguous :: Xt1(:)
real(kind=rk), intent(in), optional, contiguous :: Xt2(:)
real(kind=rk), intent(in), optional, contiguous :: Xt3(:)
real(kind=rk), intent(out), allocatable :: dTgc(:,:,:)
real(kind=rk), intent(out), optional, allocatable :: Tgc(:,:)
Calls
Called by
Call graph
derivative_vector calls compute_dtgc, ndgrid, is_rational
compute_dtgc calls compute_dtgc_bspline_3d_scalar, compute_dtgc_bspline_3d_vector, compute_dtgc_nurbs_3d_scalar, compute_dtgc_nurbs_3d_vector
ndgrid calls ndgrid2, ndgrid3
compute_dtgc_bspline_3d_scalar calls basis_bspline_der, kron
compute_dtgc_bspline_3d_vector calls basis_bspline_der, kron
compute_dtgc_nurbs_3d_scalar calls basis_bspline_der, kron
compute_dtgc_nurbs_3d_vector calls basis_bspline_der, kron
basis_bspline_der calls basis_bspline_der_a, basis_bspline_der_b
ansatz calls derivative
test_nurbs_volume calls derivative, cmp_volume
cmp_volume calls ansatz
compute_volume calls cmp_volume