derivative_vector – ForCAD
derivative_vector Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
33 statements
Source File
private pure subroutine derivative_vector(this, res1, res2, Xt1, Xt2, dTgc, Tgc)
Type Bound
nurbs_surface
Arguments
Type Intent Optional Attributes Name
class(nurbs_surface), intent(inout) :: this
integer, intent(in), optional :: res1
integer, intent(in), optional :: res2
real(kind=rk), intent(in), optional, contiguous :: Xt1(:)
real(kind=rk), intent(in), optional, contiguous :: Xt2(:)
real(kind=rk), intent(out), allocatable :: dTgc(:,:,:)
real(kind=rk), intent(out), optional, allocatable :: Tgc(:,:)
Calls
Called by
Call graph
derivative_vector calls compute_dtgc, ndgrid, is_rational
compute_dtgc calls compute_dtgc_bspline_2d_scalar, compute_dtgc_bspline_2d_vector, compute_dtgc_nurbs_2d_scalar, compute_dtgc_nurbs_2d_vector
ndgrid calls ndgrid2, ndgrid3
compute_dtgc_bspline_2d_scalar calls basis_bspline_der, kron
compute_dtgc_bspline_2d_vector calls basis_bspline_der, kron
compute_dtgc_nurbs_2d_scalar calls basis_bspline_der, kron
compute_dtgc_nurbs_2d_vector calls basis_bspline_der, kron
ansatz calls derivative
test_nurbs_surface calls derivative, cmp_area
cmp_area calls ansatz
compute_area calls cmp_area