derivative2_scalar – ForCAD
derivative2_scalar Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
13 statements
Source File
private pure subroutine derivative2_scalar(this, Xt, d2Tgc, dTgc, Tgc)
Type Bound
nurbs_surface
Arguments
Type Intent Optional Attributes Name
class(nurbs_surface), intent(inout) :: this
real(kind=rk), intent(in), contiguous :: Xt(:)
real(kind=rk), intent(out), allocatable :: d2Tgc(:,:)
real(kind=rk), intent(out), optional, allocatable :: dTgc(:,:)
real(kind=rk), intent(out), optional, allocatable :: Tgc(:)
Calls
Called by
Call graph
derivative2_scalar calls compute_d2tgc, is_rational
compute_d2tgc calls compute_d2tgc_bspline_2d_scalar, compute_d2tgc_bspline_2d_vector, compute_d2tgc_nurbs_2d_scalar, compute_d2tgc_nurbs_2d_vector
compute_d2tgc_bspline_2d_scalar calls basis_bspline_2der, kron
compute_d2tgc_bspline_2d_vector calls basis_bspline_2der, kron
compute_d2tgc_nurbs_2d_scalar calls basis_bspline_2der, kron
compute_d2tgc_nurbs_2d_vector calls basis_bspline_2der, kron
basis_bspline_2der calls basis_bspline_2der_a, basis_bspline_2der_b, basis_bspline_2der_c
kron calls kron3, kron_t1_t1, kron_t1_t2
nearest_point2 calls derivative2
fdm_test_surface calls derivative2
test_nurbs_surface calls derivative2, nearest_point2
nearest_point_2d calls nearest_point2