derivative2_vector – ForCAD
derivative2_vector Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
31 statements
Source File
private pure subroutine derivative2_vector(this, res, Xt, d2Tgc, dTgc, Tgc)
Type Bound
nurbs_curve
Arguments
Type Intent Optional Attributes Name
class(nurbs_curve), intent(inout) :: this
integer, intent(in), optional :: res
real(kind=rk), intent(in), optional, contiguous :: Xt(:)
real(kind=rk), intent(out), allocatable :: d2Tgc(:,:)
real(kind=rk), intent(out), optional, allocatable :: dTgc(:,:)
real(kind=rk), intent(out), optional, allocatable :: Tgc(:,:)
Calls
Called by
Call graph
derivative2_vector calls compute_d2tgc, is_rational
compute_d2tgc calls compute_d2tgc_bspline_1d_scalar, compute_d2tgc_bspline_1d_vector, compute_d2tgc_nurbs_1d_scalar, compute_d2tgc_nurbs_1d_vector
compute_d2tgc_bspline_1d_scalar calls basis_bspline_2der
compute_d2tgc_bspline_1d_vector calls basis_bspline_2der
compute_d2tgc_nurbs_1d_scalar calls basis_bspline_2der
compute_d2tgc_nurbs_1d_vector calls basis_bspline_2der
basis_bspline_2der calls basis_bspline_2der_a, basis_bspline_2der_b, basis_bspline_2der_c
nearest_point2 calls derivative2
fdm_test_curve calls derivative2
test_nurbs_curve calls derivative2, nearest_point2
nearest_point_1d calls nearest_point2