derivative2_scalar – ForCAD
derivative2_scalar Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
12 statements
Source File
private pure subroutine derivative2_scalar(this, Xt, d2Tgc, dTgc, Tgc)
Type Bound
nurbs_curve
Arguments
Type Intent Optional Attributes Name
class(nurbs_curve), intent(inout) :: this
real(kind=rk), intent(in) :: Xt
real(kind=rk), intent(out), allocatable :: d2Tgc(:)
real(kind=rk), intent(out), optional, allocatable :: dTgc(:)
real(kind=rk), intent(out), optional, allocatable :: Tgc(:)
Calls
Called by
Call graph
derivative2_scalar calls compute_d2tgc, is_rational
nearest_point2 calls derivative2
nearest_point_1d calls nearest_point2