derivative_vector – ForCAD
derivative_vector Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
22 statements
Source File
private pure subroutine derivative_vector(this, res, Xt, dTgc, Tgc)
Type Bound
nurbs_curve
Arguments
Type Intent Optional Attributes Name
class(nurbs_curve), intent(inout) :: this
integer, intent(in), optional :: res
real(kind=rk), intent(in), optional, contiguous :: Xt(:)
real(kind=rk), intent(out), allocatable :: dTgc(:,:)
real(kind=rk), intent(out), optional, allocatable :: Tgc(:,:)
Calls
Called by
Call graph
derivative_vector calls compute_dtgc, is_rational
compute_dtgc calls compute_dtgc_bspline_1d_scalar, compute_dtgc_bspline_1d_vector, compute_dtgc_nurbs_1d_scalar, compute_dtgc_nurbs_1d_vector
compute_dtgc_bspline_1d_scalar calls basis_bspline_der
compute_dtgc_bspline_1d_vector calls basis_bspline_der
compute_dtgc_nurbs_1d_scalar calls basis_bspline_der
compute_dtgc_nurbs_1d_vector calls basis_bspline_der
ansatz calls derivative
test_nurbs_curve calls derivative, cmp_length
cmp_length calls ansatz
compute_length calls cmp_length