derivative_scalar – ForCAD
derivative_scalar Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
12 statements
Source File
private pure subroutine derivative_scalar(this, Xt, dTgc, Tgc, elem)
Type Bound
nurbs_surface
Arguments
Type Intent Optional Attributes Name
class(nurbs_surface), intent(inout) :: this
real(kind=rk), intent(in), contiguous :: Xt(:)
real(kind=rk), intent(out), allocatable :: dTgc(:,:)
real(kind=rk), intent(out), optional, allocatable :: Tgc(:)
integer, intent(in), optional :: elem(:)
Calls
Called by
Call graph
derivative_scalar calls compute_dtgc, is_rational
compute_dtgc calls compute_dtgc_bspline_2d_scalar, compute_dtgc_bspline_2d_vector, compute_dtgc_nurbs_2d_scalar, compute_dtgc_nurbs_2d_vector
compute_dtgc_bspline_2d_scalar calls basis_bspline_der, kron
compute_dtgc_bspline_2d_vector calls basis_bspline_der, kron
compute_dtgc_nurbs_2d_scalar calls basis_bspline_der, kron
compute_dtgc_nurbs_2d_vector calls basis_bspline_der, kron
basis_bspline_der calls basis_bspline_der_a, basis_bspline_der_b
ansatz calls derivative
test_nurbs_surface calls derivative, cmp_area
cmp_area calls ansatz
compute_area calls cmp_area