derivative2_vector – ForCAD
derivative2_vector Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
43 statements
Source File
private pure subroutine derivative2_vector(this, res1, res2, res3, Xt1, Xt2, Xt3, d2Tgc, dTgc, Tgc)
Type Bound
nurbs_volume
Arguments
Type Intent Optional Attributes Name
class(nurbs_volume), intent(inout) :: this
integer, intent(in), optional :: res1
integer, intent(in), optional :: res2
integer, intent(in), optional :: res3
real(kind=rk), intent(in), optional, contiguous :: Xt1(:)
real(kind=rk), intent(in), optional, contiguous :: Xt2(:)
real(kind=rk), intent(in), optional, contiguous :: Xt3(:)
real(kind=rk), intent(out), allocatable :: d2Tgc(:,:,:)
real(kind=rk), intent(out), optional, allocatable :: dTgc(:,:,:)
real(kind=rk), intent(out), optional, allocatable :: Tgc(:,:)
Calls
Called by
Call graph
derivative2_vector calls compute_d2tgc, ndgrid, is_rational
ndgrid calls ndgrid2, ndgrid3
nearest_point2 calls derivative2
fdm_test_volume calls derivative2
test_nurbs_volume calls derivative2, nearest_point2
nearest_point_3d calls nearest_point2