derivative_scalar – ForCAD
derivative_scalar Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
12 statements
Source File
private pure subroutine derivative_scalar(this, Xt, dTgc, Tgc, elem)
Type Bound
nurbs_volume
Arguments
Type Intent Optional Attributes Name
class(nurbs_volume), intent(inout) :: this
real(kind=rk), intent(in), contiguous :: Xt(:)
real(kind=rk), intent(out), allocatable :: dTgc(:,:)
real(kind=rk), intent(out), optional, allocatable :: Tgc(:)
integer, intent(in), optional :: elem(:)
Calls
Called by
Call graph
derivative_scalar calls compute_dtgc, is_rational
ansatz calls derivative
test_nurbs_volume calls derivative, cmp_volume
cmp_volume calls ansatz
compute_volume calls cmp_volume