derivative2_vector – ForCAD
derivative2_vector Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
34 statements
Source File
private pure subroutine derivative2_vector(this, res1, res2, Xt1, Xt2, d2Tgc, dTgc, Tgc)
Type Bound
nurbs_surface
Arguments
Type Intent Optional Attributes Name
class(nurbs_surface), intent(inout) :: this
integer, intent(in), optional :: res1
integer, intent(in), optional :: res2
real(kind=rk), intent(in), optional, contiguous :: Xt1(:)
real(kind=rk), intent(in), optional, contiguous :: Xt2(:)
real(kind=rk), intent(out), allocatable :: d2Tgc(:,:,:)
real(kind=rk), intent(out), optional, allocatable :: dTgc(:,:,:)
real(kind=rk), intent(out), optional, allocatable :: Tgc(:,:)
Calls
Called by
Call graph
derivative2_vector calls compute_d2tgc, ndgrid, is_rational
compute_d2tgc calls compute_d2tgc_bspline_2d_scalar, compute_d2tgc_bspline_2d_vector, compute_d2tgc_nurbs_2d_scalar, compute_d2tgc_nurbs_2d_vector
ndgrid calls ndgrid2, ndgrid3
compute_d2tgc_bspline_2d_scalar calls basis_bspline_2der, kron
compute_d2tgc_bspline_2d_vector calls basis_bspline_2der, kron
compute_d2tgc_nurbs_2d_scalar calls basis_bspline_2der, kron
compute_d2tgc_nurbs_2d_vector calls basis_bspline_2der, kron
basis_bspline_2der calls basis_bspline_2der_a, basis_bspline_2der_b, basis_bspline_2der_c
nearest_point2 calls derivative2
fdm_test_surface calls derivative2
test_nurbs_surface calls derivative2, nearest_point2
nearest_point_2d calls nearest_point2