derivative_scalar – ForCAD
derivative_scalar Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
19 statements
Source File
private pure subroutine derivative_scalar(this, Xt, dTgc, Tgc, elem)
Type Bound
nurbs_volume
Arguments
Type Intent Optional Attributes Name
class(nurbs_volume), intent(inout) :: this
real(kind=rk), intent(in), contiguous :: Xt(:)
real(kind=rk), intent(out), allocatable :: dTgc(:,:)
real(kind=rk), intent(out), optional, allocatable :: Tgc(:)
integer, intent(in), optional, contiguous :: elem(:)
Calls
Called by
Call graph
derivative_scalar calls compute_dtgc, is_rational
compute_dtgc calls compute_dtgc_bspline_3d_scalar, compute_dtgc_bspline_3d_vector, compute_dtgc_nurbs_3d_scalar, compute_dtgc_nurbs_3d_vector
compute_dtgc_bspline_3d_scalar calls basis_bspline_der, kron
compute_dtgc_bspline_3d_vector calls basis_bspline_der, kron
compute_dtgc_nurbs_3d_scalar calls basis_bspline_der, kron
compute_dtgc_nurbs_3d_vector calls basis_bspline_der, kron
basis_bspline_der calls basis_bspline_der_a, basis_bspline_der_b
kron calls kron3, kron_t1_t1, kron_t1_t2
ansatz calls derivative
test_nurbs_volume calls derivative, cmp_volume
cmp_volume calls ansatz
poisson_iga_solver_3d calls ansatz
compute_volume calls cmp_volume