derivative – ForCAD
derivative Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
57 statements
Source File
private pure subroutine derivative(this, res1, res2, res3, Xt1, Xt2, Xt3, dTgc)
Type Bound
nurbs_volume
Arguments
Type Intent Optional Attributes Name
class(nurbs_volume), intent(inout) :: this
integer, intent(in), optional :: res1
integer, intent(in), optional :: res2
integer, intent(in), optional :: res3
real(kind=rk), intent(in), optional, contiguous :: Xt1(:)
real(kind=rk), intent(in), optional, contiguous :: Xt2(:)
real(kind=rk), intent(in), optional, contiguous :: Xt3(:)
real(kind=rk), intent(out), allocatable :: dTgc(:,:)
Calls
Call graph
derivative calls ndgrid, basis_bspline_der, kron
ndgrid calls ndgrid2, ndgrid3
basis_bspline_der calls isinf