det – ForCAD
det Function
Seyed Ali Ghasemi
BSD 3-Clause
14 statements
Source File
public pure function det(A) result(detA)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: A(:,:)
Return Value real(kind=rk)
Called by
Call graph
ansatz calls det, inv
inv calls det, inv
test_forcad_utils calls det, inv
cmp_area calls ansatz
cmp_volume calls ansatz
nearest_point2 calls inv
poisson_iga_solver_2d calls ansatz
poisson_iga_solver_3d calls ansatz
compute_area calls cmp_area
compute_volume calls cmp_volume
nearest_point_2d calls nearest_point2
nearest_point_3d calls nearest_point2
test_nurbs_surface calls cmp_area, nearest_point2
test_nurbs_volume calls cmp_volume, nearest_point2