dyad_t1_t1 – ForCAD
dyad_t1_t1 Function
Seyed Ali Ghasemi
BSD 3-Clause
10 statements
Source File
private pure function dyad_t1_t1(a, b) result(c)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: a(:)
real(kind=rk), intent(in), contiguous :: b(:)
Return Value real(kind=rk), allocatable, (:,:)
Called by
Call graph
dyad calls dyad_t1_t1
ansatz calls dyad
cmp_length calls ansatz
compute_length calls cmp_length
test_nurbs_curve calls cmp_length