elevate_degree_A_5_9 – ForCAD
elevate_degree_A_5_9 Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
166 statements
Source File
public pure subroutine elevate_degree_A_5_9(t, knot, degree, Xcw, nc_new, knot_new, Xcw_new, Tmap)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: t
real(kind=rk), intent(in), contiguous :: knot(:)
integer, intent(in) :: degree
real(kind=rk), intent(in), contiguous :: Xcw(:,:)
integer, intent(out) :: nc_new
real(kind=rk), intent(out), allocatable :: knot_new(:)
real(kind=rk), intent(out), allocatable :: Xcw_new(:,:)
real(kind=rk), intent(out), optional, allocatable :: Tmap(:,:)
Calls
Called by
Call graph
elevate_degree_a_5_9 calls compute_multiplicity, bincoeff
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
bincoeff calls factln
elevate_degree calls elevate_degree_a_5_9
test_forcad_utils calls elevate_degree_a_5_9
example1_curve calls elevate_degree
example3_surface calls elevate_degree
example3_volume calls elevate_degree
example_bend_pipe calls elevate_degree
example_helix_pipe calls elevate_degree
example_nurbs_surface calls elevate_degree
example_nurbs_volume calls elevate_degree
example_toroidal_pipe calls elevate_degree
fdm_elevate_and_insert_1d calls elevate_degree
fdm_elevate_and_insert_2d calls elevate_degree
fdm_elevate_and_insert_3d calls elevate_degree
test_nurbs_curve calls elevate_degree
test_nurbs_surface calls elevate_degree
test_nurbs_volume calls elevate_degree