elevate_degree – ForCAD
elevate_degree Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
78 statements
Source File
private pure subroutine elevate_degree(this, dir, t)
Type Bound
nurbs_surface
Arguments
Type Intent Optional Attributes Name
class(nurbs_surface), intent(inout) :: this
integer, intent(in) :: dir
integer, intent(in) :: t
Calls
Called by
Call graph
elevate_degree calls set, create, elevate_degree_a, is_rational
create calls is_rational, ndgrid, basis_bspline, kron
elevate_degree_a calls compute_multiplicity, bincoeff
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
ndgrid calls ndgrid2, ndgrid3
bincoeff calls factln
set1 calls get_degree, get_nc
set2 calls compute_knot_vector, get_nc
set3 calls get_degree
compute_knot_vector calls repelem
get_degree calls get_multiplicity
get_nc calls compute_multiplicity
get_multiplicity calls compute_multiplicity
example3_surface calls elevate_degree