elevate_degree – ForCAD
elevate_degree Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
131 statements
Source File
private pure subroutine elevate_degree(this, dir, t, B, Bs)
Type Bound
nurbs_surface
Arguments
Type Intent Optional Attributes Name
class(nurbs_surface), intent(inout) :: this
integer, intent(in) :: dir
integer, intent(in) :: t
real(kind=rk), intent(out), optional, allocatable :: B(:,:)
real(kind=rk), intent(out), optional, allocatable :: Bs(:,:)
Calls
Called by
Call graph
elevate_degree calls get_knot, set, elevate_degree_a_5_9, is_rational
elevate_degree_a_5_9 calls compute_multiplicity, bincoeff
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
bincoeff calls factln
set1 calls cmp_degree, cmp_nc, set
set2 calls cmp_nc, compute_knot_vector, set
set3 calls cmp_degree, set
set4 calls set
cmp_degree calls set, get_multiplicity
cmp_nc calls compute_multiplicity, set
compute_knot_vector calls repelem
get_multiplicity calls compute_multiplicity
example3_surface calls elevate_degree
example_nurbs_surface calls elevate_degree
fdm_elevate_and_insert_2d calls elevate_degree
test_nurbs_surface calls elevate_degree