elevate_degree_A – ForCAD
elevate_degree_A Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
181 statements
Source File
public pure subroutine elevate_degree_A(t, knot, order, Xcw, nc_new, knot_new, Xcw_new)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: t
real(kind=rk), intent(in) :: knot(:)
integer, intent(in) :: order
real(kind=rk), intent(in) :: Xcw(:,:)
integer, intent(out) :: nc_new
real(kind=rk), intent(out), allocatable :: knot_new(:)
real(kind=rk), intent(out), allocatable :: Xcw_new(:,:)
Calls
Called by
Call graph
elevate_degree_a calls compute_multiplicity, bincoeff
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
bincoeff calls factln
elevate_degree calls elevate_degree_a
example_nurbs_curve calls elevate_degree
example_nurbs_surface calls elevate_degree
example_nurbs_volume calls elevate_degree