export_iges – ForCAD
export_iges Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
68 statements
Source File
private impure subroutine export_iges(this, filename)
Uses
forIGES
Type Bound
nurbs_surface
Arguments
Type Intent Optional Attributes Name
class(nurbs_surface), intent(inout) :: this
character(len=*), intent(in) :: filename
Calls
Called by
Call graph
export_iges calls append, delete, init, makedpsections, makegsection, makessection, is_rational, writeigesfile
example3_surface calls export_iges
test_nurbs_surface calls export_iges