export_Xth_in_Xg – ForCAD
export_Xth_in_Xg Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
135 statements
Source File
private impure subroutine export_Xth_in_Xg(this, filename, res, encoding)
Type Bound
nurbs_volume
Arguments
Type Intent Optional Attributes Name
class(nurbs_volume), intent(inout) :: this
character(len=*), intent(in) :: filename
integer, intent(in), optional :: res
character(len=*), intent(in), optional :: encoding
Calls
Called by
Call graph
export_xth_in_xg calls compute_xg, unique, export_vtk_legacy, is_rational, set
compute_xg calls compute_xg_bspline_3d, compute_xg_bspline_3d_1point, compute_xg_nurbs_3d, compute_xg_nurbs_3d_1point
unique calls unique_integer, unique_real
compute_xg_bspline_3d calls kron, basis_bspline
compute_xg_bspline_3d_1point calls kron, basis_bspline
compute_xg_nurbs_3d calls cmp_tgc_3d
compute_xg_nurbs_3d_1point calls kron, basis_bspline
kron calls kron3, kron_t1_t1, kron_t1_t2
cmp_tgc_3d calls kron, basis_bspline
example_nurbs_volume calls export_xth_in_xg