export_Xth – ForCAD
export_Xth Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
17 statements
Source File
private impure subroutine export_Xth(this, filename, point_data, field_names, encoding)
Type Bound
nurbs_curve
Arguments
Type Intent Optional Attributes Name
class(nurbs_curve), intent(in) :: this
character(len=*), intent(in) :: filename
real(kind=rk), intent(in), optional :: point_data(:,:)
character(len=*), intent(in), optional :: field_names(:)
character(len=*), intent(in), optional :: encoding
Calls
Called by
Call graph
export_xth calls ndgrid, unique, set, cmp_elem, export_vtk_legacy
ndgrid calls ndgrid2, ndgrid3
unique calls unique_integer, unique_real
cmp_elem calls unique, elemconn_cn, get_multiplicity
elemconn_cn calls cmp_elemconn_cn_l, cmp_elemconn_cn_s, cmp_elemconn_cn_v
get_multiplicity calls compute_multiplicity
set1 calls cmp_degree
set1a calls cmp_degree
set2 calls cmp_nc, compute_knot_vector
set3 calls cmp_degree
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
cmp_degree calls get_multiplicity
cmp_nc calls compute_multiplicity
compute_knot_vector calls repelem
example1_curve calls export_xth
test_nurbs_curve calls export_xth