export_vtk_legacy – ForCAD
export_vtk_legacy Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
146 statements
Source File
public impure subroutine export_vtk_legacy(filename, points, elemConn, vtkCellType, point_data, field_names, encoding)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
real(kind=rk), intent(in), contiguous :: points(:,:)
integer, intent(in), contiguous :: elemConn(:,:)
integer, intent(in) :: vtkCellType
real(kind=rk), intent(in), optional, contiguous :: point_data(:,:)
character(len=*), intent(in), optional, contiguous :: field_names(:)
character(len=*), intent(in), optional :: encoding
Called by
Call graph
export_xc calls export_vtk_legacy
export_xg calls export_vtk_legacy
export_xth calls export_vtk_legacy
export_xth_in_xg calls export_vtk_legacy
test_forcad_utils calls export_vtk_legacy
example1_curve calls export_xc, export_xg, export_xth
example3_surface calls export_xc, export_xg, export_xth
example3_volume calls export_xc, export_xg, export_xth
example_bend_pipe calls export_xc, export_xg, export_xth_in_xg
example_helix_pipe calls export_xc, export_xg, export_xth_in_xg
example_nurbs_curve calls export_xc, export_xg
example_nurbs_surface calls export_xc, export_xg, export_xth_in_xg
example_nurbs_volume calls export_xc, export_xg, export_xth_in_xg
example_plate_hole_1_2d calls export_xc, export_xg, export_xth_in_xg
example_plate_hole_1_3d calls export_xc, export_xg, export_xth_in_xg
example_plate_hole_2_2d calls export_xc, export_xg, export_xth_in_xg
example_plate_hole_2_3d calls export_xc, export_xg, export_xth_in_xg
example_plate_hole_4_2d calls export_xc, export_xg, export_xth_in_xg
example_plate_hole_4_3d calls export_xc, export_xg, export_xth_in_xg
example_put_to_nurbs calls export_xc, export_xg
example_toroidal_pipe calls export_xc, export_xg, export_xth_in_xg
example_twist_taper calls export_xc, export_xg, export_xth_in_xg
lsq_fit_bspline_1d calls export_xc, export_xg
lsq_fit_bspline_2d calls export_xc, export_xg, export_xth_in_xg
lsq_fit_bspline_3d calls export_xc, export_xg, export_xth_in_xg
lsq_fit_nurbs_1d calls export_xc, export_xg
lsq_fit_nurbs_2d calls export_xc, export_xg, export_xth_in_xg
lsq_fit_nurbs_3d calls export_xc, export_xg, export_xth_in_xg
poisson_iga_solver_2d calls export_xc, export_xg
poisson_iga_solver_3d calls export_xc, export_xg
shape_c_1d calls export_xc, export_xg
shape_c_2d calls export_xc, export_xg
shape_c_3d calls export_xc, export_xg
shape_circle calls export_xc, export_xg
shape_half_circle calls export_xc, export_xg
shape_half_ring_2d calls export_xc, export_xg
shape_half_ring_3d calls export_xc, export_xg
shape_hexahedron calls export_xc, export_xg
shape_ring_2d calls export_xc, export_xg
shape_ring_3d calls export_xc, export_xg
shape_tetragon calls export_xc, export_xg
test_nurbs_curve calls export_xc, export_xg, export_xth
test_nurbs_surface calls export_xc, export_xg, export_xth
test_nurbs_volume calls export_xc, export_xg, export_xth