export_Xc – ForCAD
export_Xc Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
19 statements
Source File
private impure subroutine export_Xc(this, filename, point_data, field_names, encoding)
Type Bound
nurbs_volume
Arguments
Type Intent Optional Attributes Name
class(nurbs_volume), intent(inout) :: this
character(len=*), intent(in) :: filename
real(kind=rk), intent(in), optional, contiguous :: point_data(:,:)
character(len=*), intent(in), optional, contiguous :: field_names(:)
character(len=*), intent(in), optional :: encoding
Calls
Called by
Call graph
export_xc calls cmp_elem_xc_vis, export_vtk_legacy, set
cmp_elem_xc_vis calls elemconn_c0
elemconn_c0 calls cmp_elemconn_c0_l, cmp_elemconn_c0_s, cmp_elemconn_c0_v
example3_volume calls export_xc
example_bend_pipe calls export_xc
example_helix_pipe calls export_xc
example_nurbs_volume calls export_xc
example_plate_hole_1_3d calls export_xc
example_plate_hole_2_3d calls export_xc
example_plate_hole_4_3d calls export_xc
example_put_to_nurbs calls export_xc
example_toroidal_pipe calls export_xc
example_twist_taper calls export_xc
lsq_fit_bspline_3d calls export_xc
poisson_iga_solver_3d calls export_xc
shape_c_3d calls export_xc
shape_half_ring_3d calls export_xc
shape_hexahedron calls export_xc
shape_ring_3d calls export_xc
test_nurbs_volume calls export_xc