export_Xg – ForCAD
export_Xg Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
17 statements
Source File
private impure subroutine export_Xg(this, filename, point_data, field_names, encoding)
Type Bound
nurbs_surface
Arguments
Type Intent Optional Attributes Name
class(nurbs_surface), intent(in) :: this
character(len=*), intent(in) :: filename
real(kind=rk), intent(in), optional :: point_data(:,:)
character(len=*), intent(in), optional :: field_names(:)
character(len=*), intent(in), optional :: encoding
Calls
Called by
Call graph
export_xg calls cmp_elem_xg_vis, export_vtk_legacy
cmp_elem_xg_vis calls elemconn_c0
elemconn_c0 calls cmp_elemconn_c0_l, cmp_elemconn_c0_s, cmp_elemconn_c0_v
example3_surface calls export_xg
example_nurbs_surface calls export_xg
lsq_fit_bspline_2d calls export_xg
poisson_iga_solver_2d calls export_xg
shape_c_2d calls export_xg
shape_half_ring_2d calls export_xg
shape_ring_2d calls export_xg
shape_tetragon calls export_xg
test_nurbs_surface calls export_xg