export_Xth – ForCAD
export_Xth Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
15 statements
Source File
private impure subroutine export_Xth(this, filename, point_data, field_names, encoding)
Type Bound
nurbs_surface
Arguments
Type Intent Optional Attributes Name
class(nurbs_surface), intent(in) :: this
character(len=*), intent(in) :: filename
real(kind=rk), intent(in), optional, contiguous :: point_data(:,:)
character(len=*), intent(in), optional, contiguous :: field_names(:)
character(len=*), intent(in), optional :: encoding
Calls
Called by
Call graph
export_xth calls ndgrid, unique, cmp_elem_xth, export_vtk_legacy
ndgrid calls ndgrid2, ndgrid3
unique calls unique_integer, unique_real
cmp_elem_xth calls unique, elemconn_c0
elemconn_c0 calls cmp_elemconn_c0_l, cmp_elemconn_c0_s, cmp_elemconn_c0_v
example3_surface calls export_xth
test_nurbs_surface calls export_xth