export_Xg – ForCAD
export_Xg Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
19 statements
Source File
private impure subroutine export_Xg(this, filename, point_data, field_names, encoding)
Type Bound
nurbs_volume
Arguments
Type Intent Optional Attributes Name
class(nurbs_volume), intent(inout) :: this
character(len=*), intent(in) :: filename
real(kind=rk), intent(in), optional, contiguous :: point_data(:,:)
character(len=*), intent(in), optional, contiguous :: field_names(:)
character(len=*), intent(in), optional :: encoding
Calls
Called by
Call graph
export_xg calls cmp_elem_xg_vis, export_vtk_legacy, set
cmp_elem_xg_vis calls elemconn_c0
elemconn_c0 calls cmp_elemconn_c0_l, cmp_elemconn_c0_s, cmp_elemconn_c0_v
example3_volume calls export_xg
example_bend_pipe calls export_xg
example_helix_pipe calls export_xg
example_nurbs_volume calls export_xg
example_plate_hole_1_3d calls export_xg
example_plate_hole_2_3d calls export_xg
example_plate_hole_4_3d calls export_xg
example_put_to_nurbs calls export_xg
example_toroidal_pipe calls export_xg
example_twist_taper calls export_xg
lsq_fit_bspline_3d calls export_xg
lsq_fit_nurbs_3d calls export_xg
poisson_iga_solver_3d calls export_xg
shape_c_3d calls export_xg
shape_half_ring_3d calls export_xg
shape_hexahedron calls export_xg
shape_ring_3d calls export_xg
test_nurbs_volume calls export_xg