export_Xc – ForCAD
export_Xc Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
24 statements
Source File
private impure subroutine export_Xc(this, filename)
Type Bound
bezier_volume
Arguments
Type Intent Optional Attributes Name
class(bezier_volume), intent(in) :: this
character(len=*), intent(in) :: filename
Calls
Called by
Call graph
export_xc calls get_elem_xc
get_elem_xc calls elemconn_c0
elemconn_c0 calls cmp_elemconn_c0_l, cmp_elemconn_c0_s, cmp_elemconn_c0_v
example_bezier_volume calls export_xc