eye – ForCAD
eye Function
Seyed Ali Ghasemi
BSD 3-Clause
9 statements
Source File
public pure function eye(n) result(I)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
Return Value real(kind=rk), allocatable, (:,:)
Called by
Call graph
inv calls eye, inv
test_forcad_utils calls eye, inv
ansatz calls inv
nearest_point2 calls inv
cmp_area calls ansatz
cmp_volume calls ansatz
nearest_point_2d calls nearest_point2
nearest_point_3d calls nearest_point2
poisson_iga_solver_2d calls ansatz
poisson_iga_solver_3d calls ansatz
test_nurbs_surface calls nearest_point2, cmp_area
test_nurbs_volume calls nearest_point2, cmp_volume
compute_area calls cmp_area
compute_volume calls cmp_volume