finalize – ForCAD
finalize Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
14 statements
Source File
private pure subroutine finalize(this)
Type Bound
nurbs_surface
Arguments
Type Intent Optional Attributes Name
class(nurbs_surface), intent(inout) :: this
Called by
Call graph
nearest_point2 calls finalize
example3_surface calls finalize
example_nurbs_surface calls finalize
example_ppm1 calls finalize
example_ppm2 calls finalize
example_ppm3 calls finalize
fdm_elevate_and_insert_2d calls finalize
fdm_test_surface calls finalize
nearest_point_2d calls finalize, nearest_point2
nearest_point_2d_bench calls finalize
poisson_iga_solver_2d calls finalize
shape_c_2d calls finalize
shape_half_ring_2d calls finalize
shape_ring_2d calls finalize
shape_tetragon calls finalize
test_nurbs_surface calls finalize, nearest_point2