findspan – ForCAD
findspan Function
Seyed Ali Ghasemi
BSD 3-Clause
23 statements
Source File
public pure function findspan(n, degree, Xth, knot) result(s)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
integer, intent(in) :: degree
real(kind=rk), intent(in) :: Xth
real(kind=rk), intent(in), contiguous :: knot(:)
Return Value integer
Called by
Call graph
insert_knots calls findspan
remove_knots calls findspan
test_forcad_utils calls findspan
example1_curve calls insert_knots, remove_knots
example3_surface calls insert_knots, remove_knots
example3_volume calls insert_knots, remove_knots
example_bend_pipe calls insert_knots
example_helix_pipe calls insert_knots
example_nurbs_surface calls insert_knots
example_nurbs_volume calls insert_knots
example_toroidal_pipe calls insert_knots
fdm_elevate_and_insert_1d calls insert_knots
fdm_elevate_and_insert_2d calls insert_knots
fdm_elevate_and_insert_3d calls insert_knots
poisson_iga_solver_2d calls insert_knots
poisson_iga_solver_3d calls insert_knots
test_nurbs_curve calls insert_knots, remove_knots
test_nurbs_surface calls insert_knots, remove_knots
test_nurbs_volume calls insert_knots, remove_knots