gauss_legendre_2D – ForCAD
gauss_legendre_2D Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
12 statements
Source File
private pure subroutine gauss_legendre_2D(interval1, interval2, degree, Xksi, Wksi)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: interval1(:)
real(kind=rk), intent(in), contiguous :: interval2(:)
integer, intent(in), contiguous :: degree(:)
real(kind=rk), intent(out), allocatable :: Xksi(:,:)
real(kind=rk), intent(out), allocatable :: Wksi(:)
Calls
Called by
Call graph
gauss_legendre_2d calls kron, ndgrid, gauss_legendre
kron calls kron3, kron_t1_t1, kron_t1_t2
ndgrid calls ndgrid2, ndgrid3
gauss_leg calls gauss_legendre_2d
ansatz calls gauss_leg
test_forcad_utils calls gauss_leg
cmp_area calls ansatz
cmp_length calls ansatz
cmp_volume calls ansatz
poisson_iga_solver_2d calls ansatz
poisson_iga_solver_3d calls ansatz
compute_area calls cmp_area
compute_length calls cmp_length
compute_volume calls cmp_volume
test_nurbs_curve calls cmp_length
test_nurbs_surface calls cmp_area
test_nurbs_volume calls cmp_volume