gauss_legendre – ForCAD
gauss_legendre Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
44 statements
Source File
private pure subroutine gauss_legendre(x, w, interval)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(out) :: x(:)
real(kind=rk), intent(out) :: w(:)
real(kind=rk), intent(in), contiguous :: interval(:)
Called by
Call graph
gauss_legendre_1d calls gauss_legendre
gauss_legendre_2d calls gauss_legendre
gauss_legendre_3d calls gauss_legendre
gauss_leg calls gauss_legendre_1d, gauss_legendre_2d, gauss_legendre_3d
ansatz calls gauss_leg
test_forcad_utils calls gauss_leg
cmp_area calls ansatz
cmp_length calls ansatz
cmp_volume calls ansatz
poisson_iga_solver_2d calls ansatz
poisson_iga_solver_3d calls ansatz
compute_area calls cmp_area
compute_length calls cmp_length
compute_volume calls cmp_volume
test_nurbs_curve calls cmp_length
test_nurbs_surface calls cmp_area
test_nurbs_volume calls cmp_volume