get_elem_Xg – ForCAD
get_elem_Xg Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
10 statements
Source File
private pure subroutine get_elem_Xg(this, elemConn, p)
Type Bound
bezier_volume
Arguments
Type Intent Optional Attributes Name
class(bezier_volume), intent(in) :: this
integer, intent(out), dimension(:,:), allocatable :: elemConn
integer, intent(in), optional :: p(:)
Calls
Called by
Call graph
get_elem_xg calls elemconn_c0
elemconn_c0 calls cmp_elemconn_c0_l, cmp_elemconn_c0_s, cmp_elemconn_c0_v
export_xg calls get_elem_xg
example_bezier_volume calls export_xg