get_Xc_all – ForCAD
get_Xc_all Function
Seyed Ali Ghasemi
BSD 3-Clause
9 statements
Source File
private pure function get_Xc_all(this) result(Xc)
Type Bound
nurbs_volume
Arguments
Type Intent Optional Attributes Name
class(nurbs_volume), intent(in) :: this
Return Value real(kind=rk), allocatable, (:,:)
Called by
Call graph
modify_wc calls get_xc
modify_xc calls get_xc
test_nurbs_volume calls get_xc, modify_wc, modify_xc