get_knot_all – ForCAD
get_knot_all Function
Seyed Ali Ghasemi
BSD 3-Clause
21 statements
Source File
private pure function get_knot_all(this, dir) result(knot)
Type Bound
nurbs_surface
Arguments
Type Intent Optional Attributes Name
class(nurbs_surface), intent(in) :: this
integer, intent(in) :: dir
Return Value real(kind=rk), allocatable, (:)
Called by
Call graph
elevate_degree calls get_knot
insert_knots calls get_knot
modify_wc calls get_knot
modify_xc calls get_knot
remove_knots calls get_knot
example3_surface calls get_knot, elevate_degree, insert_knots, remove_knots
fdm_elevate_and_insert_2d calls get_knot, elevate_degree, insert_knots
lsq_fit_bspline_2d calls get_knot
lsq_fit_nurbs_2d calls get_knot
test_nurbs_surface calls get_knot, elevate_degree, insert_knots, modify_wc, modify_xc, remove_knots
example_nurbs_surface calls elevate_degree, insert_knots
example_ppm3 calls modify_xc
poisson_iga_solver_2d calls insert_knots