get_order – ForCAD
get_order Function
Seyed Ali Ghasemi
BSD 3-Clause
9 statements
Source File
private pure function get_order(this) result(order)
Type Bound
nurbs_surface
Arguments
Type Intent Optional Attributes Name
class(nurbs_surface), intent(in) :: this
Return Value integer, (2)
Calls
Called by
Call graph
get_order calls get_multiplicity
get_multiplicity calls compute_multiplicity
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
set1 calls get_order
set3 calls get_order
elevate_degree calls set
insert_knots calls set
modify_wc calls set
modify_xc calls set
example3_surface calls set, elevate_degree, insert_knots
example_nurbs_surface calls set