get_Wci – ForCAD
get_Wci Function
Seyed Ali Ghasemi
BSD 3-Clause
14 statements
Source File
private pure function get_Wci(this, n) result(Wc)
Type Bound
nurbs_volume
Arguments
Type Intent Optional Attributes Name
class(nurbs_volume), intent(in) :: this
integer, intent(in) :: n
Return Value real(kind=rk)
Called by
Call graph
bend_pipe calls get_wc
build_helix calls get_wc
build_twist_taper calls get_wc
map_to_torus_sinez calls get_wc
modify_wc calls get_wc
modify_xc calls get_wc
fdm_elevate_and_insert_3d calls get_wc
test_nurbs_volume calls get_wc, modify_wc, modify_xc
example_bend_pipe calls bend_pipe
example_helix_pipe calls build_helix
example_toroidal_pipe calls map_to_torus_sinez
example_twist_taper calls build_twist_taper