get_multiplicity – ForCAD
get_multiplicity Function
Seyed Ali Ghasemi
BSD 3-Clause
27 statements
Source File
private pure function get_multiplicity(this, dir) result(m)
Type Bound
nurbs_volume
Arguments
Type Intent Optional Attributes Name
class(nurbs_volume), intent(in) :: this
integer, intent(in) :: dir
Return Value integer, allocatable, (:)
Calls
Called by
Call graph
get_multiplicity calls compute_multiplicity
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
cmp_degree calls get_multiplicity
cmp_elem calls get_multiplicity
test_nurbs_volume calls get_multiplicity, cmp_elem, cmp_volume, set, elevate_degree, modify_wc, modify_xc, remove_knots, set_c, set_half_ring, set_hexahedron, set_ring
ansatz calls cmp_elem, set
cmp_volume calls cmp_elem, ansatz
set1 calls cmp_degree
set3 calls cmp_degree
example3_volume calls cmp_elem, set, elevate_degree, remove_knots
poisson_iga_solver_3d calls cmp_elem, ansatz, set_hexahedron
compute_volume calls cmp_volume, set
bend_pipe calls set
build_helix calls set
build_twist_taper calls set
elevate_degree calls set
map_to_torus_sinez calls set
modify_wc calls set
modify_xc calls set
remove_knots calls set
set_c calls set
set_half_ring calls set
set_hexahedron calls set
set_ring calls set
example_nurbs_volume calls set, elevate_degree
example_plate_hole_1_3d calls set
example_plate_hole_2_3d calls set
example_plate_hole_4_3d calls set
example_put_to_nurbs calls set
fdm_elevate_and_insert_3d calls set, elevate_degree
lsq_fit_bspline_3d calls set
lsq_fit_nurbs_3d calls set
nearest_point_3d calls set
example_bend_pipe calls bend_pipe, elevate_degree, set_ring
example_helix_pipe calls build_helix, elevate_degree, set_ring
example_toroidal_pipe calls elevate_degree, map_to_torus_sinez, set_ring
example_twist_taper calls build_twist_taper, set_hexahedron
fdm_test_volume calls set_hexahedron
shape_c_3d calls set_c
shape_half_ring_3d calls set_half_ring
shape_hexahedron calls set_hexahedron
shape_ring_3d calls set_ring