get_Xg_all – ForCAD
get_Xg_all Function
Seyed Ali Ghasemi
BSD 3-Clause
9 statements
Source File
private pure function get_Xg_all(this) result(Xg)
Type Bound
nurbs_surface
Arguments
Type Intent Optional Attributes Name
class(nurbs_surface), intent(in) :: this
Return Value real(kind=rk), allocatable, (:,:)
Called by
Call graph
example_ppm1 calls get_xg
example_ppm2 calls get_xg
example_ppm3 calls get_xg
lsq_fit_bspline_2d calls get_xg
test_nurbs_surface calls get_xg