get_Xcid – ForCAD
get_Xcid Function
Seyed Ali Ghasemi
BSD 3-Clause
18 statements
Source File
private pure function get_Xcid(this, n, dir) result(Xc)
Type Bound
nurbs_surface
Arguments
Type Intent Optional Attributes Name
class(nurbs_surface), intent(in) :: this
integer, intent(in) :: n
integer, intent(in) :: dir
Return Value real(kind=rk)
Called by
Call graph
modify_wc calls get_xc
modify_xc calls get_xc
poisson_iga_solver_2d calls get_xc
test_nurbs_surface calls get_xc, modify_wc, modify_xc
example_ppm3 calls modify_xc