get_nc – ForCAD
get_nc Function
Seyed Ali Ghasemi
BSD 3-Clause
26 statements
Source File
private pure function get_nc(this, dir) result(nc)
Type Bound
nurbs_volume
Arguments
Type Intent Optional Attributes Name
class(nurbs_volume), intent(in) :: this
integer, intent(in) :: dir
Return Value integer
Calls
Called by
Call graph
get_nc calls compute_multiplicity
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
set1 calls get_nc
set2 calls get_nc
elevate_degree calls set
insert_knots calls set
modify_wc calls set
modify_xc calls set
remove_knots calls set
set_hexahedron calls set
example3_volume calls set, elevate_degree, insert_knots
example_morph calls set
example_nurbs_volume calls set
shape_hexahedron calls set_hexahedron