get_Xcid – ForCAD
get_Xcid Function
Seyed Ali Ghasemi
BSD 3-Clause
18 statements
Source File
private pure function get_Xcid(this, n, dir) result(Xc)
Type Bound
nurbs_volume
Arguments
Type Intent Optional Attributes Name
class(nurbs_volume), intent(in) :: this
integer, intent(in) :: n
integer, intent(in) :: dir
Return Value real(kind=rk)
Called by
Call graph
bend_pipe calls get_xc
build_helix calls get_xc
build_twist_taper calls get_xc
map_to_torus_sinez calls get_xc
modify_wc calls get_xc
modify_xc calls get_xc
fdm_elevate_and_insert_3d calls get_xc
poisson_iga_solver_3d calls get_xc
test_nurbs_volume calls get_xc, modify_wc, modify_xc
example_bend_pipe calls bend_pipe
example_helix_pipe calls build_helix
example_toroidal_pipe calls map_to_torus_sinez
example_twist_taper calls build_twist_taper