get_degree – ForCAD
get_degree Function
Seyed Ali Ghasemi
BSD 3-Clause
11 statements
Source File
private pure function get_degree(this) result(degree)
Type Bound
nurbs_volume
Arguments
Type Intent Optional Attributes Name
class(nurbs_volume), intent(in) :: this
Return Value integer, (3)
Calls
Called by
Call graph
get_degree calls get_multiplicity
get_multiplicity calls compute_multiplicity
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
set1 calls get_degree
set3 calls get_degree
elevate_degree calls set
insert_knots calls set
modify_wc calls set
modify_xc calls set
set_hexahedron calls set
example3_volume calls set, elevate_degree, insert_knots
example_nurbs_volume calls set
shape_hexahedron calls set_hexahedron