get_Wc_all – ForCAD
get_Wc_all Function
Seyed Ali Ghasemi
BSD 3-Clause
10 statements
Source File
private pure function get_Wc_all(this) result(Wc)
Type Bound
nurbs_volume
Arguments
Type Intent Optional Attributes Name
class(nurbs_volume), intent(in) :: this
Return Value real(kind=rk), allocatable, (:)
Called by
Call graph
bend_pipe calls get_wc
modify_wc calls get_wc
modify_xc calls get_wc
fdm_elevate_and_insert_3d calls get_wc
test_nurbs_volume calls get_wc, modify_wc, modify_xc
example_bend_pipe calls bend_pipe