get_nc_dir – ForCAD
get_nc_dir Function
Seyed Ali Ghasemi
BSD 3-Clause
27 statements
Source File
private pure function get_nc_dir(this, dir) result(nc)
Type Bound
nurbs_volume
Arguments
Type Intent Optional Attributes Name
class(nurbs_volume), intent(in) :: this
integer, intent(in) :: dir
Return Value integer
Calls
Called by
Call graph
get_nc_dir calls compute_multiplicity
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
bend_pipe calls get_nc
build_helix calls get_nc
map_to_torus_sinez calls get_nc
lsq_fit_bspline_3d calls get_nc
lsq_fit_nurbs_3d calls get_nc
poisson_iga_solver_3d calls get_nc
test_nurbs_volume calls get_nc
example_bend_pipe calls bend_pipe
example_helix_pipe calls build_helix
example_toroidal_pipe calls map_to_torus_sinez