get_Xgid – ForCAD
get_Xgid Function
Seyed Ali Ghasemi
BSD 3-Clause
17 statements
Source File
private pure function get_Xgid(this, n, dir) result(Xg)
Type Bound
nurbs_surface
Arguments
Type Intent Optional Attributes Name
class(nurbs_surface), intent(in) :: this
integer, intent(in) :: n
integer, intent(in) :: dir
Return Value real(kind=rk)
Called by
Call graph
example_ppm1 calls get_xg
example_ppm2 calls get_xg
example_ppm3 calls get_xg
test_nurbs_surface calls get_xg