get_knot_all – ForCAD
get_knot_all Function
Seyed Ali Ghasemi
BSD 3-Clause
27 statements
Source File
private pure function get_knot_all(this, dir) result(knot)
Type Bound
nurbs_volume
Arguments
Type Intent Optional Attributes Name
class(nurbs_volume), intent(in) :: this
integer, intent(in) :: dir
Return Value real(kind=rk), allocatable, (:)
Called by
Call graph
bend_pipe calls get_knot
elevate_degree calls get_knot
insert_knots calls get_knot
modify_wc calls get_knot
modify_xc calls get_knot
remove_knots calls get_knot
example3_volume calls get_knot, elevate_degree, insert_knots, remove_knots
fdm_elevate_and_insert_3d calls get_knot, elevate_degree, insert_knots
lsq_fit_bspline_3d calls get_knot
test_nurbs_volume calls get_knot, elevate_degree, insert_knots, modify_wc, modify_xc, remove_knots
example_bend_pipe calls bend_pipe, elevate_degree, insert_knots
example_nurbs_volume calls elevate_degree, insert_knots
poisson_iga_solver_3d calls insert_knots