get_Wc_all – ForCAD
get_Wc_all Function
Seyed Ali Ghasemi
BSD 3-Clause
10 statements
Source File
private pure function get_Wc_all(this) result(Wc)
Type Bound
nurbs_surface
Arguments
Type Intent Optional Attributes Name
class(nurbs_surface), intent(in) :: this
Return Value real(kind=rk), allocatable, (:)
Called by
Call graph
modify_wc calls get_wc
modify_xc calls get_wc
fdm_elevate_and_insert_2d calls get_wc
test_nurbs_surface calls get_wc, modify_wc, modify_xc
example_ppm3 calls modify_xc