get_Xci – ForCAD
get_Xci Function
Seyed Ali Ghasemi
BSD 3-Clause
13 statements
Source File
private pure function get_Xci(this, n) result(Xc)
Type Bound
nurbs_curve
Arguments
Type Intent Optional Attributes Name
class(nurbs_curve), intent(in) :: this
integer, intent(in) :: n
Return Value real(kind=rk), allocatable, (:)
Called by
Call graph
modify_wc calls get_xc
modify_xc calls get_xc
test_nurbs_curve calls get_xc, modify_wc, modify_xc