get_nc – ForCAD
get_nc Function
Seyed Ali Ghasemi
BSD 3-Clause
20 statements
Source File
private pure function get_nc(this, dir) result(nc)
Type Bound
nurbs_surface
Arguments
Type Intent Optional Attributes Name
class(nurbs_surface), intent(in) :: this
integer, intent(in) :: dir
Return Value integer
Calls
Called by
Call graph
get_nc calls compute_multiplicity
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
set1 calls get_nc
set2 calls get_nc
elevate_degree calls set
insert_knots calls set
modify_wc calls set
modify_xc calls set
remove_knots calls set
set_tetragon calls set
example3_surface calls set, elevate_degree, insert_knots, remove_knots
example_nurbs_surface calls set
shape_tetragon calls set_tetragon