get_order – ForCAD
get_order Function
Seyed Ali Ghasemi
BSD 3-Clause
11 statements
Source File
private pure function get_order(this) result(order)
Type Bound
nurbs_volume
Arguments
Type Intent Optional Attributes Name
class(nurbs_volume), intent(in) :: this
Return Value integer, (3)
Calls
Called by
Call graph
get_order calls get_multiplicity
get_multiplicity calls compute_multiplicity
set1 calls get_order
insert_knots calls set
modify_wc calls set
modify_xc calls set
example_nurbs_volume calls set, insert_knots