get_multiplicity – ForCAD
get_multiplicity Function
Seyed Ali Ghasemi
BSD 3-Clause
20 statements
Source File
private pure function get_multiplicity(this, dir) result(m)
Type Bound
nurbs_surface
Arguments
Type Intent Optional Attributes Name
class(nurbs_surface), intent(in) :: this
integer, intent(in) :: dir
Return Value integer, allocatable, (:)
Calls
Called by
Call graph
get_multiplicity calls compute_multiplicity
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
cmp_degree calls get_multiplicity
cmp_elem calls get_multiplicity
test_nurbs_surface calls get_multiplicity, cmp_elem, cmp_area, export_xth, set, elevate_degree, insert_knots, modify_wc, modify_xc, remove_knots, set_c, set_half_ring, set_ring, set_tetragon
ansatz calls cmp_elem, set
cmp_area calls cmp_elem, ansatz
export_xth calls cmp_elem, set
set1 calls cmp_degree
set3 calls cmp_degree
poisson_iga_solver_2d calls cmp_elem, ansatz, insert_knots, set_tetragon
compute_area calls cmp_area, set
example3_surface calls export_xth, set, elevate_degree, insert_knots, remove_knots
elevate_degree calls set
insert_knots calls set
modify_wc calls set
modify_xc calls set
remove_knots calls set
set_c calls set
set_half_ring calls set
set_ring calls set
set_tetragon calls set
example_nurbs_surface calls set
lsq_fit_bspline_2d calls set
nearest_point_2d calls set
example_ppm1 calls set_ring, set_tetragon
example_ppm2 calls set_half_ring, set_tetragon
example_ppm3 calls modify_xc, set_tetragon
fdm_test_surface calls set_tetragon
nearest_point_2d_bench calls set_tetragon
shape_c_2d calls set_c
shape_half_ring_2d calls set_half_ring
shape_ring_2d calls set_ring
shape_tetragon calls set_tetragon