get_degree – ForCAD
get_degree Function
Seyed Ali Ghasemi
BSD 3-Clause
7 statements
Source File
private pure function get_degree(this) result(degree)
Type Bound
nurbs_curve
Arguments
Type Intent Optional Attributes Name
class(nurbs_curve), intent(in) :: this
Return Value integer
Calls
Called by
Call graph
get_degree calls get_multiplicity
get_multiplicity calls compute_multiplicity
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
set1 calls get_degree
set3 calls get_degree
example1_curve calls get_degree, set, elevate_degree, insert_knots, remove_knots
elevate_degree calls set
insert_knots calls set
modify_wc calls set
modify_xc calls set
remove_knots calls set
set_circle calls set
example_nurbs_curve calls set
shape_circle calls set_circle