get_degree_dir – ForCAD
get_degree_dir Function
Seyed Ali Ghasemi
BSD 3-Clause
15 statements
Source File
private pure function get_degree_dir(this, dir) result(degree)
Type Bound
nurbs_surface
Arguments
Type Intent Optional Attributes Name
class(nurbs_surface), intent(in) :: this
integer, intent(in) :: dir
Return Value integer
Calls
Called by
Call graph
get_degree_dir calls get_multiplicity
get_multiplicity calls compute_multiplicity
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
set1 calls get_degree
set3 calls get_degree
example3_surface calls get_degree, set, elevate_degree, insert_knots, remove_knots
elevate_degree calls set
insert_knots calls set
modify_wc calls set
modify_xc calls set
remove_knots calls set
set_tetragon calls set
example_nurbs_surface calls set
shape_tetragon calls set_tetragon