get_knoti – ForCAD
get_knoti Function
Seyed Ali Ghasemi
BSD 3-Clause
40 statements
Source File
private pure function get_knoti(this, dir, i) result(knot)
Type Bound
nurbs_volume
Arguments
Type Intent Optional Attributes Name
class(nurbs_volume), intent(in) :: this
integer, intent(in) :: dir
integer, intent(in) :: i
Return Value real(kind=rk)
Called by
Call graph
bend_pipe calls get_knot
build_helix calls get_knot
build_twist_taper calls get_knot
elevate_degree calls get_knot
insert_knots calls get_knot
map_to_torus_sinez calls get_knot
modify_wc calls get_knot
modify_xc calls get_knot
remove_knots calls get_knot
example3_volume calls get_knot, elevate_degree, insert_knots, remove_knots
fdm_elevate_and_insert_3d calls get_knot, elevate_degree, insert_knots
lsq_fit_bspline_3d calls get_knot
lsq_fit_nurbs_3d calls get_knot
test_nurbs_volume calls get_knot, elevate_degree, insert_knots, modify_wc, modify_xc, remove_knots
example_bend_pipe calls bend_pipe, elevate_degree, insert_knots
example_helix_pipe calls build_helix, elevate_degree, insert_knots
example_nurbs_volume calls elevate_degree, insert_knots
example_toroidal_pipe calls elevate_degree, insert_knots, map_to_torus_sinez
example_twist_taper calls build_twist_taper
poisson_iga_solver_3d calls insert_knots