get_continuity – ForCAD
get_continuity Function
Seyed Ali Ghasemi
BSD 3-Clause
9 statements
Source File
private pure function get_continuity(this) result(c)
Type Bound
nurbs_curve
Arguments
Type Intent Optional Attributes Name
class(nurbs_curve), intent(in) :: this
Return Value integer, allocatable, (:)
Calls
Called by
Call graph
get_continuity calls compute_multiplicity
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
lsq_fit_bspline_1d calls get_continuity
test_nurbs_curve calls get_continuity