hexahedron_Xc – ForCAD
hexahedron_Xc Function
Seyed Ali Ghasemi
BSD 3-Clause
22 statements
Source File
public pure function hexahedron_Xc(L, nc) result(Xc)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: L(3)
integer, intent(in) :: nc(3)
Return Value real(kind=rk), allocatable, (:,:)
Called by
Call graph
set_hexahedron calls hexahedron_xc
example_put_to_nurbs calls hexahedron_xc
fdm_test_volume calls set_hexahedron
shape_hexahedron calls set_hexahedron
test_nurbs_volume calls set_hexahedron