insert_knots – ForCAD
insert_knots Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
97 statements
Source File
private pure subroutine insert_knots(this, Xth, r, B, Bs)
Type Bound
nurbs_curve
Arguments
Type Intent Optional Attributes Name
class(nurbs_curve), intent(inout) :: this
real(kind=rk), intent(in), contiguous :: Xth(:)
integer, intent(in), contiguous :: r(:)
real(kind=rk), intent(out), optional, allocatable :: B(:,:)
real(kind=rk), intent(out), optional, allocatable :: Bs(:,:)
Calls
Called by
Call graph
insert_knots calls compute_multiplicity, set, findspan, insert_knot_a_5_1, is_rational
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
set1a calls cmp_degree, set
set1 calls cmp_degree, set
set2 calls cmp_nc, compute_knot_vector, set
set3 calls cmp_degree, set
set4 calls set
cmp_degree calls get_multiplicity
cmp_nc calls compute_multiplicity
compute_knot_vector calls repelem
get_multiplicity calls compute_multiplicity
example1_curve calls insert_knots
fdm_elevate_and_insert_1d calls insert_knots
test_nurbs_curve calls insert_knots