insert_knots – ForCAD
insert_knots Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
104 statements
Source File
private pure subroutine insert_knots(this, dir, Xth, r)
Type Bound
nurbs_surface
Arguments
Type Intent Optional Attributes Name
class(nurbs_surface), intent(inout) :: this
integer, intent(in) :: dir
real(kind=rk), intent(in), contiguous :: Xth(:)
integer, intent(in), contiguous :: r(:)
Calls
Called by
Call graph
insert_knots calls compute_multiplicity, get_knot, set, findspan, insert_knot_a_5_1, is_rational
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
set1 calls cmp_degree, cmp_nc
set2 calls cmp_nc, compute_knot_vector
set3 calls cmp_degree
cmp_degree calls get_multiplicity
cmp_nc calls compute_multiplicity
compute_knot_vector calls repelem
get_multiplicity calls compute_multiplicity
example3_surface calls insert_knots
test_nurbs_surface calls insert_knots