insert_knot – ForCAD
insert_knot Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
91 statements
Source File
private pure subroutine insert_knot(this, Xth)
Type Bound
nurbs_curve
Arguments
Type Intent Optional Attributes Name
class(nurbs_curve), intent(inout) :: this
real(kind=rk), intent(in) :: Xth(:)
Calls
Called by
Call graph
insert_knot calls set, create, findspan
create calls basis_bspline
set1 calls get_order
set2 calls compute_knot_vector
compute_knot_vector calls repelem
get_order calls get_multiplicity
get_multiplicity calls compute_multiplicity
example_nurbs_curve calls insert_knot