insert_knot_A_5_1 – ForCAD
insert_knot_A_5_1 Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
55 statements
Source File
public pure subroutine insert_knot_A_5_1(p, UP, Pw, u, k, s, r, nq, UQ, Qw, T)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: p
real(kind=rk), intent(in), contiguous :: UP(0:)
real(kind=rk), intent(in), contiguous :: Pw(0:,:)
real(kind=rk), intent(in) :: u
integer, intent(in) :: k
integer, intent(in) :: s
integer, intent(in) :: r
integer, intent(out) :: nq
real(kind=rk), intent(out), allocatable :: UQ(:)
real(kind=rk), intent(out), allocatable :: Qw(:,:)
real(kind=rk), intent(out), optional, allocatable :: T(:,:)
Called by
Call graph
insert_knots calls insert_knot_a_5_1
test_forcad_utils calls insert_knot_a_5_1
example1_curve calls insert_knots
example3_surface calls insert_knots
example3_volume calls insert_knots
example_bend_pipe calls insert_knots
example_helix_pipe calls insert_knots
example_nurbs_surface calls insert_knots
example_nurbs_volume calls insert_knots
example_toroidal_pipe calls insert_knots
fdm_elevate_and_insert_1d calls insert_knots
fdm_elevate_and_insert_2d calls insert_knots
fdm_elevate_and_insert_3d calls insert_knots
poisson_iga_solver_2d calls insert_knots
poisson_iga_solver_3d calls insert_knots
test_nurbs_curve calls insert_knots
test_nurbs_surface calls insert_knots
test_nurbs_volume calls insert_knots