insert_knots – ForCAD
insert_knots Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
104 statements
Source File
private pure subroutine insert_knots(this, dir, Xth, r)
Type Bound
nurbs_surface
Arguments
Type Intent Optional Attributes Name
class(nurbs_surface), intent(inout) :: this
integer, intent(in) :: dir
real(kind=rk), intent(in), contiguous :: Xth(:)
integer, intent(in), contiguous :: r(:)
Calls
Called by
Call graph
insert_knots calls compute_multiplicity, get_knot, set, findspan, insert_knot_a_5_1, is_rational
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
set1 calls get_degree, get_nc
set2 calls compute_knot_vector, get_nc
set3 calls get_degree
compute_knot_vector calls repelem
get_nc calls compute_multiplicity
get_degree_all calls get_multiplicity
get_degree_dir calls get_multiplicity
get_multiplicity calls compute_multiplicity
example3_surface calls insert_knots