inv – ForCAD
inv Function
Seyed Ali Ghasemi
BSD 3-Clause
35 statements
Source File
public pure recursive function inv(A) result(A_inv)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: A(:,:)
Return Value real(kind=rk), allocatable, (:,:)
Calls
Called by
Call graph
inv calls inv, det
ansatz calls inv
nearest_point2 calls inv
cmp_area calls ansatz
cmp_volume calls ansatz
nearest_point_2d calls nearest_point2
nearest_point_3d calls nearest_point2
test_nurbs_surface calls nearest_point2, cmp_area
test_nurbs_volume calls nearest_point2, cmp_volume
compute_area calls cmp_area
compute_volume calls cmp_volume