is_rational – ForCAD
is_rational Function
Seyed Ali Ghasemi
BSD 3-Clause
11 statements
Source File
private pure function is_rational(this) result(r)
Type Bound
nurbs_volume
Arguments
Type Intent Optional Attributes Name
class(nurbs_volume), intent(in) :: this
Return Value logical
Called by
Call graph
basis_scalar calls is_rational
basis_vector calls is_rational
bend_pipe calls is_rational
build_helix calls is_rational
build_twist_taper calls is_rational
cmp_xg calls is_rational
create calls is_rational
derivative2_scalar calls is_rational
derivative2_vector calls is_rational
derivative_scalar calls is_rational
derivative_vector calls is_rational
elevate_degree calls is_rational
export_xth_in_xg calls is_rational
insert_knots calls is_rational
map_to_torus_sinez calls is_rational
put_to_nurbs calls is_rational
nearest_point2 calls cmp_xg, create, derivative2
example3_volume calls create, elevate_degree, insert_knots
example_bend_pipe calls bend_pipe, create, elevate_degree, export_xth_in_xg, insert_knots
example_helix_pipe calls build_helix, create, elevate_degree, export_xth_in_xg, insert_knots
example_nurbs_volume calls create, elevate_degree, export_xth_in_xg, insert_knots
example_plate_hole_1_3d calls create, export_xth_in_xg
example_plate_hole_2_3d calls create, export_xth_in_xg
example_plate_hole_4_3d calls create, export_xth_in_xg
example_put_to_nurbs calls put_to_nurbs
example_toroidal_pipe calls create, elevate_degree, export_xth_in_xg, insert_knots, map_to_torus_sinez
example_twist_taper calls build_twist_taper, create, export_xth_in_xg
fdm_elevate_and_insert_3d calls elevate_degree, insert_knots
fdm_test_volume calls create, derivative2
lsq_fit_bspline_3d calls create, export_xth_in_xg
lsq_fit_nurbs_3d calls create, export_xth_in_xg
nearest_point_3d calls create, nearest_point2
poisson_iga_solver_3d calls create, insert_knots, basis, ansatz
shape_c_3d calls create
shape_half_ring_3d calls create
shape_hexahedron calls create
shape_ring_3d calls create
test_nurbs_volume calls create, elevate_degree, insert_knots, basis, derivative2, derivative, nearest_point2, cmp_volume
ansatz calls derivative
cmp_volume calls ansatz
compute_volume calls cmp_volume