isinf – ForCAD
isinf Function
Seyed Ali Ghasemi
BSD 3-Clause
7 statements
Source File
private pure elemental function isinf(x) result(output)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: x
Return Value logical
Called by
Call graph
basis_bspline_der calls isinf
compute_dtgc_bspline_1d calls basis_bspline_der
compute_dtgc_bspline_2d calls basis_bspline_der
compute_dtgc_bspline_3d calls basis_bspline_der
compute_dtgc_nurbs_1d calls basis_bspline_der
compute_dtgc_nurbs_2d calls basis_bspline_der
compute_dtgc_nurbs_3d calls basis_bspline_der