lsq_fit_nurbs – ForCAD
lsq_fit_nurbs Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
105 statements
Source File
private pure subroutine lsq_fit_nurbs(this, Xt, Xdata, ndata, maxit, tol, lambda_xc, mu0, reg_logw)
Uses
forcad_interface
Type Bound
nurbs_volume
Arguments
Type Intent Optional Attributes Name
class(nurbs_volume), intent(inout) :: this
real(kind=rk), intent(in), contiguous :: Xt(:,:)
real(kind=rk), intent(in), contiguous :: Xdata(:,:)
integer, intent(in) :: ndata(3)
integer, intent(in), optional :: maxit
real(kind=rk), intent(in), optional :: tol
real(kind=rk), intent(in), optional :: lambda_xc
real(kind=rk), intent(in), optional :: mu0
real(kind=rk), intent(in), optional :: reg_logw
Calls
Called by
Call graph
lsq_fit_nurbs calls kron, basis_bspline, solve, set
kron calls kron3, kron_t1_t1, kron_t1_t2
lsq_fit_nurbs_3d calls lsq_fit_nurbs