lsq_fit_bspline – ForCAD
lsq_fit_bspline Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
20 statements
Source File
private pure subroutine lsq_fit_bspline(this, Xt, Xdata, ndata)
Uses
forcad_interface
Type Bound
nurbs_volume
Arguments
Type Intent Optional Attributes Name
class(nurbs_volume), intent(inout) :: this
real(kind=rk), intent(in), contiguous :: Xt(:,:)
real(kind=rk), intent(in), contiguous :: Xdata(:,:)
integer, intent(in) :: ndata(3)
Calls
Called by
Call graph
lsq_fit_bspline calls kron, basis_bspline, solve
kron calls kron3, kron_t1_t1, kron_t1_t2
lsq_fit_bspline_3d calls lsq_fit_bspline
test_nurbs_volume calls lsq_fit_bspline