lsq_fit_bspline – ForCAD
lsq_fit_bspline Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
18 statements
Source File
private pure subroutine lsq_fit_bspline(this, Xt, Xdata, ndata)
Uses
forcad_interface
Type Bound
nurbs_surface
Arguments
Type Intent Optional Attributes Name
class(nurbs_surface), intent(inout) :: this
real(kind=rk), intent(in), contiguous :: Xt(:,:)
real(kind=rk), intent(in), contiguous :: Xdata(:,:)
integer, intent(in) :: ndata(2)
Calls
Called by
Call graph
lsq_fit_bspline calls basis_bspline, kron, solve
lsq_fit_bspline_2d calls lsq_fit_bspline
test_nurbs_surface calls lsq_fit_bspline