lsq_fit_bspline – ForCAD
lsq_fit_bspline Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
26 statements
Source File
private pure subroutine lsq_fit_bspline(this, Xt, Xdata, ndata)
Uses
forcad_interface
Type Bound
nurbs_surface
Arguments
Type Intent Optional Attributes Name
class(nurbs_surface), intent(inout) :: this
real(kind=rk), intent(in), contiguous :: Xt(:,:)
real(kind=rk), intent(in), contiguous :: Xdata(:,:)
integer, intent(in) :: ndata(2)
Calls
Called by
Call graph
lsq_fit_bspline calls kron, basis_bspline, solve, set
kron calls kron3, kron_t1_t1, kron_t1_t2
lsq_fit_bspline_2d calls lsq_fit_bspline