modify_Xc – ForCAD
modify_Xc Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
18 statements
Source File
private pure subroutine modify_Xc(this, X, num, dir)
Type Bound
nurbs_curve
Arguments
Type Intent Optional Attributes Name
class(nurbs_curve), intent(inout) :: this
real(kind=rk), intent(in) :: X
integer, intent(in) :: num
integer, intent(in) :: dir
Calls
Called by
Call graph
modify_xc calls get_knot, get_wc, get_xc, set
set1 calls cmp_degree, set
set1a calls cmp_degree, set
set2 calls cmp_nc, compute_knot_vector, set
set3 calls cmp_degree, set
set4 calls set
cmp_degree calls get_multiplicity
cmp_nc calls compute_multiplicity
compute_knot_vector calls repelem
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
get_multiplicity calls compute_multiplicity
test_nurbs_curve calls modify_xc