modify_Xc – ForCAD
modify_Xc Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
16 statements
Source File
private pure subroutine modify_Xc(this, X, num, dir)
Type Bound
nurbs_curve
Arguments
Type Intent Optional Attributes Name
class(nurbs_curve), intent(inout) :: this
real(kind=rk), intent(in) :: X
integer, intent(in) :: num
integer, intent(in) :: dir
Calls
Call graph
modify_xc calls get_knot, get_wc, get_xc, set
set1a calls cmp_degree
set1 calls cmp_degree
set2 calls compute_knot_vector
set3 calls cmp_degree
cmp_degree calls get_multiplicity
compute_knot_vector calls repelem
get_multiplicity calls compute_multiplicity
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2