modify_Wc – ForCAD
modify_Wc Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
17 statements
Source File
private pure subroutine modify_Wc(this, W, num)
Type Bound
nurbs_volume
Arguments
Type Intent Optional Attributes Name
class(nurbs_volume), intent(inout) :: this
real(kind=rk), intent(in) :: W
integer, intent(in) :: num
Calls
Called by
Call graph
modify_wc calls get_knot, get_wc, get_xc, set
set1 calls cmp_degree, cmp_nc, set
set2 calls cmp_nc, compute_knot_vector, set
set3 calls cmp_degree, set
set4 calls set
cmp_degree calls set, get_multiplicity
cmp_nc calls set, compute_multiplicity
compute_knot_vector calls repelem
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
get_multiplicity calls compute_multiplicity
test_nurbs_volume calls modify_wc