modify_Wc – ForCAD
modify_Wc Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
11 statements
Source File
private pure subroutine modify_Wc(this, W, num)
Type Bound
nurbs_volume
Arguments
Type Intent Optional Attributes Name
class(nurbs_volume), intent(inout) :: this
real(kind=rk), intent(in) :: W
integer, intent(in) :: num
Calls
Call graph
modify_wc calls set
set1 calls get_nc, get_order
set2 calls compute_knot_vector, get_nc
set3 calls get_order
compute_knot_vector calls repelem
get_nc calls compute_multiplicity
get_order calls get_multiplicity
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
get_multiplicity calls compute_multiplicity