nearest_point – ForCAD
nearest_point Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
18 statements
Source File
private pure subroutine nearest_point(this, point_Xg, nearest_Xg, nearest_Xt, id)
Type Bound
nurbs_volume
Arguments
Type Intent Optional Attributes Name
class(nurbs_volume), intent(in) :: this
real(kind=rk), intent(in), contiguous :: point_Xg(:)
real(kind=rk), intent(out), optional :: nearest_Xg(size(point_Xg))
real(kind=rk), intent(out), optional :: nearest_Xt(3)
integer, intent(out), optional :: id
Called by
Call graph
nearest_point2 calls nearest_point
nearest_point_3d calls nearest_point, nearest_point2
test_nurbs_volume calls nearest_point, nearest_point2