nearest_point2 – ForCAD
nearest_point2 Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
91 statements
Source File
private impure subroutine nearest_point2(this, point_Xg, tol, maxit, nearest_Xt, nearest_Xg)
Type Bound
nurbs_surface
Arguments
Type Intent Optional Attributes Name
class(nurbs_surface), intent(inout) :: this
real(kind=rk), intent(in), contiguous :: point_Xg(:)
real(kind=rk), intent(in) :: tol
integer, intent(in) :: maxit
real(kind=rk), intent(out) :: nearest_Xt(2)
real(kind=rk), intent(out), optional :: nearest_Xg(size(this%Xc,2))
Calls
Called by
Call graph
nearest_point2 calls derivative2, cmp_xg, create, finalize, inv, nearest_point
cmp_xg calls compute_xg, is_rational
create calls compute_xg, ndgrid, is_rational, set
inv calls inv, det, eye, solve
compute_xg calls compute_xg_bspline_2d, compute_xg_bspline_2d_1point, compute_xg_nurbs_2d, compute_xg_nurbs_2d_1point
ndgrid calls ndgrid2, ndgrid3
derivative2_scalar calls is_rational, compute_d2tgc
derivative2_vector calls ndgrid, is_rational, compute_d2tgc
compute_d2tgc calls compute_d2tgc_bspline_2d_scalar, compute_d2tgc_bspline_2d_vector, compute_d2tgc_nurbs_2d_scalar, compute_d2tgc_nurbs_2d_vector
compute_xg_bspline_2d calls kron, basis_bspline
compute_xg_bspline_2d_1point calls kron, basis_bspline
compute_xg_nurbs_2d calls cmp_tgc_2d
compute_xg_nurbs_2d_1point calls kron, basis_bspline
kron calls kron3, kron_t1_t1, kron_t1_t2
cmp_tgc_2d calls kron, basis_bspline
compute_d2tgc_bspline_2d_scalar calls kron, basis_bspline_2der
compute_d2tgc_bspline_2d_vector calls kron, basis_bspline_2der
compute_d2tgc_nurbs_2d_scalar calls kron, basis_bspline_2der
compute_d2tgc_nurbs_2d_vector calls kron, basis_bspline_2der
basis_bspline_2der calls basis_bspline_2der_a, basis_bspline_2der_b, basis_bspline_2der_c
nearest_point_2d calls nearest_point2
test_nurbs_surface calls nearest_point2