nearest_point – ForCAD
nearest_point Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
15 statements
Source File
private pure subroutine nearest_point(this, point_Xg, nearest_Xg, nearest_Xt, id)
Type Bound
nurbs_volume
Arguments
Type Intent Optional Attributes Name
class(nurbs_volume), intent(in) :: this
real(kind=rk), intent(in) :: point_Xg(:)
real(kind=rk), intent(out), optional, allocatable :: nearest_Xg(:)
real(kind=rk), intent(out), optional, allocatable :: nearest_Xt(:)
integer, intent(out), optional :: id
Calls
Called by
Call graph
nearest_point calls nearest_point_help_3d
nearest_point2 calls nearest_point
nearest_point_3d calls nearest_point, nearest_point2
test_nurbs_volume calls nearest_point, nearest_point2