put_to_nurbs – ForCAD
put_to_nurbs Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
24 statements
Source File
private pure subroutine put_to_nurbs(this, X, elemConn)
Type Bound
nurbs_volume
Arguments
Type Intent Optional Attributes Name
class(nurbs_volume), intent(inout) :: this
real(kind=rk), intent(in), contiguous :: X(:,:)
integer, intent(in), optional, contiguous :: elemConn(:,:)
Calls
Called by
Call graph
put_to_nurbs calls compute_xg, is_rational, set_elem_xg_vis
compute_xg calls compute_xg_bspline_3d, compute_xg_bspline_3d_1point, compute_xg_nurbs_3d, compute_xg_nurbs_3d_1point
compute_xg_bspline_3d calls kron, basis_bspline
compute_xg_bspline_3d_1point calls kron, basis_bspline
compute_xg_nurbs_3d calls cmp_tgc_3d
compute_xg_nurbs_3d_1point calls kron, basis_bspline
kron calls kron3, kron_t1_t1, kron_t1_t2
cmp_tgc_3d calls kron, basis_bspline
example_put_to_nurbs calls put_to_nurbs