remove_knots_A_5_8 – ForCAD
remove_knots_A_5_8 Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
92 statements
Source File
public pure subroutine remove_knots_A_5_8(p, knot, Pw, u, r, s, num, t, knot_new, Pw_new)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: p
real(kind=rk), intent(in), contiguous :: knot(:)
real(kind=rk), intent(in), contiguous :: Pw(:,:)
real(kind=rk), intent(in) :: u
integer, intent(in) :: r
integer, intent(in) :: s
integer, intent(in) :: num
integer, intent(out) :: t
real(kind=rk), intent(out), allocatable :: knot_new(:)
real(kind=rk), intent(out), allocatable :: Pw_new(:,:)
Called by
Call graph
remove_knots calls remove_knots_a_5_8
example1_curve calls remove_knots
example3_surface calls remove_knots
example3_volume calls remove_knots
test_nurbs_curve calls remove_knots
test_nurbs_surface calls remove_knots
test_nurbs_volume calls remove_knots