remove_knots – ForCAD
remove_knots Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
130 statements
Source File
private pure subroutine remove_knots(this, dir, Xth, r)
Type Bound
nurbs_surface
Arguments
Type Intent Optional Attributes Name
class(nurbs_surface), intent(inout) :: this
integer, intent(in) :: dir
real(kind=rk), intent(in), contiguous :: Xth(:)
integer, intent(in), contiguous :: r(:)
Calls
Called by
Call graph
remove_knots calls compute_multiplicity, get_knot, set, findspan, is_rational, remove_knots_a_5_8
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
set1 calls cmp_degree, cmp_nc, set
set2 calls cmp_nc, compute_knot_vector, set
set3 calls cmp_degree, set
set4 calls set
cmp_degree calls set, get_multiplicity
cmp_nc calls compute_multiplicity, set
compute_knot_vector calls repelem
get_multiplicity calls compute_multiplicity
example3_surface calls remove_knots
test_nurbs_surface calls remove_knots