rotation – ForCAD
rotation Function
Seyed Ali Ghasemi
BSD 3-Clause
13 statements
Source File
public pure function rotation(alpha, beta, theta) result(R)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: alpha
real(kind=rk), intent(in) :: beta
real(kind=rk), intent(in) :: theta
Return Value real(kind=rk), dimension(3,3)
Calls
Called by
Call graph
rotation calls cosd, sind
rotate_xc calls rotation
rotate_xg calls rotation
test_forcad_utils calls rotation
example1_curve calls rotate_xc, rotate_xg
example3_surface calls rotate_xc, rotate_xg
example3_volume calls rotate_xc, rotate_xg
example_ppm2 calls rotate_xc
test_nurbs_curve calls rotate_xc, rotate_xg
test_nurbs_surface calls rotate_xc, rotate_xg
test_nurbs_volume calls rotate_xc, rotate_xg