rotate_Xg – ForCAD
rotate_Xg Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
8 statements
Source File
private pure subroutine rotate_Xg(this, alpha, beta, theta)
Type Bound
nurbs_surface
Arguments
Type Intent Optional Attributes Name
class(nurbs_surface), intent(inout) :: this
real(kind=rk), intent(in) :: alpha
real(kind=rk), intent(in) :: beta
real(kind=rk), intent(in) :: theta
Calls
Called by
Call graph
rotate_xg calls rotation
rotation calls cosd, sind
example3_surface calls rotate_xg
test_nurbs_surface calls rotate_xg