set – ForCAD
set Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
14 statements
Source File
private pure subroutine set(this, Xc, Wc)
Set control points and weights for the Bezier curve object.
Type Bound
bezier_curve
Arguments
Type Intent Optional Attributes Name
class(bezier_curve), intent(inout) :: this
real(kind=rk), intent(in) :: Xc(:,:)
real(kind=rk), intent(in), optional :: Wc(:)
Called by
Call graph
elevate_degree calls set
modify_wc calls set
modify_xc calls set
example_bezier_curve calls set