set1 – ForCAD
set1 Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
23 statements
Source File
private pure subroutine set1(this, knot1, knot2, Xc, Wc)
Set knot vectors, control points and weights for the NURBS surface object.
Type Bound
nurbs_surface
Arguments
Type Intent Optional Attributes Name
class(nurbs_surface), intent(inout) :: this
real(kind=rk), intent(in), contiguous :: knot1(:)
real(kind=rk), intent(in), contiguous :: knot2(:)
real(kind=rk), intent(in), contiguous :: Xc(:,:)
real(kind=rk), intent(in), optional, contiguous :: Wc(:)
Calls
Called by
Call graph
set1 calls cmp_degree, cmp_nc
cmp_degree calls get_multiplicity
cmp_nc calls compute_multiplicity
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
get_multiplicity calls compute_multiplicity
elevate_degree calls set
insert_knots calls set
modify_wc calls set
modify_xc calls set
remove_knots calls set
set_c calls set
set_half_ring calls set
set_ring calls set
set_tetragon calls set
example3_surface calls set, elevate_degree, insert_knots, remove_knots
example_nurbs_surface calls set
example_ppm1 calls set_ring, set_tetragon
example_ppm2 calls set_half_ring, set_tetragon
example_ppm3 calls modify_xc, set_tetragon
nearest_point_2d calls set_tetragon
shape_c_2d calls set_c
shape_half_ring_2d calls set_half_ring
shape_ring_2d calls set_ring
shape_tetragon calls set_tetragon