set1 – ForCAD
set1 Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
36 statements
Source File
private pure subroutine set1(this, knot1, knot2, knot3, Xc, Wc)
Set control points and weights for the NURBS volume object.
Type Bound
nurbs_volume
Arguments
Type Intent Optional Attributes Name
class(nurbs_volume), intent(inout) :: this
real(kind=rk), intent(in), contiguous :: knot1(:)
real(kind=rk), intent(in), contiguous :: knot2(:)
real(kind=rk), intent(in), contiguous :: knot3(:)
real(kind=rk), intent(in), contiguous :: Xc(:,:)
real(kind=rk), intent(in), optional, contiguous :: Wc(:)
Calls
Called by
Call graph
set1 calls cmp_degree, cmp_nc, set
cmp_degree calls set, get_multiplicity
cmp_nc calls set, compute_multiplicity
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
get_multiplicity calls compute_multiplicity
ansatz calls set
bend_pipe calls set
build_helix calls set
build_twist_taper calls set
elevate_degree calls set
map_to_torus_sinez calls set
modify_wc calls set
modify_xc calls set
remove_knots calls set
set_c calls set
set_half_ring calls set
set_hexahedron calls set
set_ring calls set
compute_volume calls set, cmp_volume
example3_volume calls set, elevate_degree, remove_knots
example_nurbs_volume calls set, elevate_degree
example_plate_hole_1_3d calls set
example_plate_hole_2_3d calls set
example_plate_hole_4_3d calls set
example_put_to_nurbs calls set
fdm_elevate_and_insert_3d calls set, elevate_degree
lsq_fit_bspline_3d calls set
nearest_point_3d calls set
test_nurbs_volume calls set, elevate_degree, modify_wc, modify_xc, remove_knots, set_c, set_half_ring, set_hexahedron, set_ring, cmp_volume
cmp_volume calls ansatz
example_bend_pipe calls bend_pipe, elevate_degree, set_ring
example_helix_pipe calls build_helix, elevate_degree, set_ring
example_toroidal_pipe calls elevate_degree, map_to_torus_sinez, set_ring
example_twist_taper calls build_twist_taper, set_hexahedron
fdm_test_volume calls set_hexahedron
poisson_iga_solver_3d calls ansatz, set_hexahedron
shape_c_3d calls set_c
shape_half_ring_3d calls set_half_ring
shape_hexahedron calls set_hexahedron
shape_ring_3d calls set_ring