set2 – ForCAD
set2 Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
17 statements
Source File
private pure subroutine set2(this, Xth_dir1, Xth_dir2, Xth_dir3, degree, continuity1, continuity2, continuity3, Xc, Wc)
Set control points and weights for the NURBS volume object.
Type Bound
nurbs_volume
Arguments
Type Intent Optional Attributes Name
class(nurbs_volume), intent(inout) :: this
real(kind=rk), intent(in), contiguous :: Xth_dir1(:)
real(kind=rk), intent(in), contiguous :: Xth_dir2(:)
real(kind=rk), intent(in), contiguous :: Xth_dir3(:)
integer, intent(in), contiguous :: degree(:)
integer, intent(in), contiguous :: continuity1(:)
integer, intent(in), contiguous :: continuity2(:)
integer, intent(in), contiguous :: continuity3(:)
real(kind=rk), intent(in), optional, contiguous :: Xc(:,:)
real(kind=rk), intent(in), optional, contiguous :: Wc(:)
Calls
Called by
Call graph
set2 calls cmp_nc, compute_knot_vector
cmp_nc calls compute_multiplicity
compute_knot_vector calls repelem
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
ansatz calls set
elevate_degree calls set
export_xth calls set
insert_knots calls set
modify_wc calls set
modify_xc calls set
remove_knots calls set
set_c calls set
set_half_ring calls set
set_hexahedron calls set
set_ring calls set
compute_volume calls set, cmp_volume
example3_volume calls set, elevate_degree, export_xth, insert_knots, remove_knots
example_nurbs_volume calls set
example_put_to_nurbs calls set
lsq_fit_bspline_3d calls set
nearest_point_3d calls set
test_nurbs_volume calls set, elevate_degree, export_xth, insert_knots, modify_wc, modify_xc, remove_knots, set_c, set_half_ring, set_hexahedron, set_ring, cmp_volume
cmp_volume calls ansatz
fdm_test_volume calls set_hexahedron
poisson_iga_solver_3d calls ansatz, insert_knots, set_hexahedron
shape_c_3d calls set_c
shape_half_ring_3d calls set_half_ring
shape_hexahedron calls set_hexahedron
shape_ring_3d calls set_ring