set2 – ForCAD
set2 Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
15 statements
Source File
private pure subroutine set2(this, Xth_dir1, Xth_dir2, degree, continuity1, continuity2, Xc, Wc)
Set NURBS surface using nodes of parameter space, degree, continuity, control points and weights
Type Bound
nurbs_surface
Arguments
Type Intent Optional Attributes Name
class(nurbs_surface), intent(inout) :: this
real(kind=rk), intent(in), contiguous :: Xth_dir1(:)
real(kind=rk), intent(in), contiguous :: Xth_dir2(:)
integer, intent(in), contiguous :: degree(:)
integer, intent(in), contiguous :: continuity1(:)
integer, intent(in), contiguous :: continuity2(:)
real(kind=rk), intent(in), contiguous :: Xc(:,:)
real(kind=rk), intent(in), optional, contiguous :: Wc(:)
Calls
Called by
Call graph
set2 calls cmp_nc, compute_knot_vector
cmp_nc calls compute_multiplicity
compute_knot_vector calls repelem
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
ansatz calls set
elevate_degree calls set
export_xth calls set
insert_knots calls set
modify_wc calls set
modify_xc calls set
remove_knots calls set
set_c calls set
set_half_ring calls set
set_ring calls set
set_tetragon calls set
compute_area calls set, cmp_area
example3_surface calls set, elevate_degree, export_xth, insert_knots, remove_knots
example_nurbs_surface calls set
nearest_point_2d calls set
test_nurbs_surface calls set, elevate_degree, export_xth, insert_knots, modify_wc, modify_xc, remove_knots, set_c, set_half_ring, set_ring, set_tetragon, cmp_area
cmp_area calls ansatz
example_ppm1 calls set_ring, set_tetragon
example_ppm2 calls set_half_ring, set_tetragon
example_ppm3 calls modify_xc, set_tetragon
fdm_test_surface calls set_tetragon
nearest_point_2d_bench calls set_tetragon
shape_c_2d calls set_c
shape_half_ring_2d calls set_half_ring
shape_ring_2d calls set_ring
shape_tetragon calls set_tetragon