set2 – ForCAD
set2 Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
37 statements
Source File
private pure subroutine set2(this, Xth_dir, degree, continuity, Xc, Wc)
Set NURBS curve using nodes of parameter space (Xth), degree, continuity, control points and weights.
Type Bound
nurbs_curve
Arguments
Type Intent Optional Attributes Name
class(nurbs_curve), intent(inout) :: this
real(kind=rk), intent(in), contiguous :: Xth_dir(:)
integer, intent(in) :: degree
integer, intent(in), contiguous :: continuity(:)
real(kind=rk), intent(in), optional, contiguous :: Xc(:,:)
real(kind=rk), intent(in), optional, contiguous :: Wc(:)
Calls
Called by
Call graph
set2 calls cmp_nc, compute_knot_vector, set
cmp_nc calls compute_multiplicity
compute_knot_vector calls repelem
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
ansatz calls set
elevate_degree calls set
insert_knots calls set
modify_wc calls set
modify_xc calls set
remove_knots calls set
set_circle calls set
set_c calls set
set_half_circle calls set
compute_length calls set, cmp_length
example1_curve calls set, elevate_degree, insert_knots, remove_knots
example_nurbs_curve calls set
fdm_elevate_and_insert_1d calls set, elevate_degree, insert_knots
fdm_test_curve calls set
lsq_fit_bspline_1d calls set
lsq_fit_nurbs_1d calls set
nearest_point_1d calls set
test_nurbs_curve calls set, elevate_degree, insert_knots, modify_wc, modify_xc, remove_knots, set_circle, set_half_circle, cmp_length
cmp_length calls ansatz
shape_c_1d calls set_c
shape_circle calls set_circle
shape_half_circle calls set_half_circle