set3 – ForCAD
set3 Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
30 statements
Source File
private pure subroutine set3(this, nc, Xc, Wc)
Set Bezier or Rational Bezier volume using control points and weights.
Type Bound
nurbs_volume
Arguments
Type Intent Optional Attributes Name
class(nurbs_volume), intent(inout) :: this
integer, intent(in), contiguous :: nc(:)
real(kind=rk), intent(in), contiguous :: Xc(:,:)
real(kind=rk), intent(in), optional, contiguous :: Wc(:)
Calls
Called by
Call graph
set3 calls cmp_degree
cmp_degree calls get_multiplicity
get_multiplicity calls compute_multiplicity
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
ansatz calls set
elevate_degree calls set
export_xth calls set
insert_knots calls set
modify_wc calls set
modify_xc calls set
remove_knots calls set
set_c calls set
set_half_ring calls set
set_hexahedron calls set
set_ring calls set
compute_volume calls set, cmp_volume
example3_volume calls set, elevate_degree, export_xth, insert_knots, remove_knots
example_nurbs_volume calls set
example_put_to_nurbs calls set
lsq_fit_bspline_3d calls set
nearest_point_3d calls set
test_nurbs_volume calls set, elevate_degree, export_xth, insert_knots, modify_wc, modify_xc, remove_knots, set_c, set_half_ring, set_hexahedron, set_ring, cmp_volume
cmp_volume calls ansatz
fdm_test_volume calls set_hexahedron
shape_c_3d calls set_c
shape_half_ring_3d calls set_half_ring
shape_hexahedron calls set_hexahedron
shape_ring_3d calls set_ring