set4 – ForCAD
set4 Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
49 statements
Source File
private pure subroutine set4(this, degree, nc, Xc, Wc)
Type Bound
nurbs_surface
Arguments
Type Intent Optional Attributes Name
class(nurbs_surface), intent(inout) :: this
integer, intent(in), contiguous :: degree(:)
integer, intent(in), contiguous :: nc(:)
real(kind=rk), intent(in), contiguous :: Xc(:,:)
real(kind=rk), intent(in), optional, contiguous :: Wc(:)
Calls
Called by
Call graph
set4 calls set
ansatz calls set
elevate_degree calls set
modify_wc calls set
modify_xc calls set
remove_knots calls set
set_c calls set
set_half_ring calls set
set_ring calls set
set_tetragon calls set
compute_area calls set, cmp_area
example3_surface calls set, elevate_degree, remove_knots
example_nurbs_surface calls set, elevate_degree
example_plate_hole_1_2d calls set
example_plate_hole_2_2d calls set
example_plate_hole_4_2d calls set
fdm_elevate_and_insert_2d calls set, elevate_degree
lsq_fit_bspline_2d calls set
lsq_fit_nurbs_2d calls set
nearest_point_2d calls set
test_nurbs_surface calls set, elevate_degree, modify_wc, modify_xc, remove_knots, set_c, set_half_ring, set_ring, set_tetragon, cmp_area
cmp_area calls ansatz
example_ppm1 calls set_ring, set_tetragon
example_ppm2 calls set_half_ring, set_tetragon
example_ppm3 calls modify_xc, set_tetragon
fdm_test_surface calls set_tetragon
nearest_point_2d_bench calls set_tetragon
poisson_iga_solver_2d calls ansatz, set_tetragon
shape_c_2d calls set_c
shape_half_ring_2d calls set_half_ring
shape_ring_2d calls set_ring
shape_tetragon calls set_tetragon