set_ring – ForCAD
set_ring Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
48 statements
Source File
private pure subroutine set_ring(this, center, radius1, radius2, length)
Type Bound
nurbs_volume
Arguments
Type Intent Optional Attributes Name
class(nurbs_volume), intent(inout) :: this
real(kind=rk), intent(in), contiguous :: center(:)
real(kind=rk), intent(in) :: radius1
real(kind=rk), intent(in) :: radius2
real(kind=rk), intent(in) :: length
Calls
Called by
Call graph
set_ring calls set
set1 calls cmp_degree, cmp_nc
set2 calls cmp_nc, compute_knot_vector
set3 calls cmp_degree
cmp_degree calls get_multiplicity
cmp_nc calls compute_multiplicity
compute_knot_vector calls repelem
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
get_multiplicity calls compute_multiplicity
shape_ring_3d calls set_ring