set_tetragon – ForCAD
set_tetragon Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
7 statements
Source File
private pure subroutine set_tetragon(this, L, nc, Wc)
Type Bound
nurbs_surface
Arguments
Type Intent Optional Attributes Name
class(nurbs_surface), intent(inout) :: this
real(kind=rk), intent(in) :: L(2)
integer, intent(in) :: nc(2)
real(kind=rk), intent(in), optional, contiguous :: Wc(:)
Calls
Called by
Call graph
set_tetragon calls set, tetragon_xc
set1 calls cmp_degree, cmp_nc
set2 calls cmp_nc, compute_knot_vector
set3 calls cmp_degree
cmp_degree calls get_multiplicity
cmp_nc calls compute_multiplicity
compute_knot_vector calls repelem
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
get_multiplicity calls compute_multiplicity
example_ppm1 calls set_tetragon
example_ppm2 calls set_tetragon
example_ppm3 calls set_tetragon
fdm_test_surface calls set_tetragon
nearest_point_2d_bench calls set_tetragon
shape_tetragon calls set_tetragon
test_nurbs_surface calls set_tetragon