set_hexahedron – ForCAD
set_hexahedron Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
12 statements
Source File
private pure subroutine set_hexahedron(this, L, nc, Wc)
Type Bound
nurbs_volume
Arguments
Type Intent Optional Attributes Name
class(nurbs_volume), intent(inout) :: this
real(kind=rk), intent(in), contiguous :: L(:)
integer, intent(in), contiguous :: nc(:)
real(kind=rk), intent(in), optional, contiguous :: Wc(:)
Calls
Called by
Call graph
set_hexahedron calls set, hexahedron_xc
set1 calls cmp_degree, cmp_nc, set
set2 calls cmp_nc, compute_knot_vector, set
set3 calls cmp_degree, set
set4 calls set
cmp_degree calls set, get_multiplicity
cmp_nc calls set, compute_multiplicity
compute_knot_vector calls repelem
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
get_multiplicity calls compute_multiplicity
example_twist_taper calls set_hexahedron
fdm_test_volume calls set_hexahedron
poisson_iga_solver_3d calls set_hexahedron
shape_hexahedron calls set_hexahedron
test_nurbs_volume calls set_hexahedron