set_ring – ForCAD
set_ring Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
32 statements
Source File
private pure subroutine set_ring(this, center, radius1, radius2)
Type Bound
nurbs_surface
Arguments
Type Intent Optional Attributes Name
class(nurbs_surface), intent(inout) :: this
real(kind=rk), intent(in), contiguous :: center(:)
real(kind=rk), intent(in) :: radius1
real(kind=rk), intent(in) :: radius2
Calls
Called by
Call graph
set_ring calls set
set1 calls cmp_degree, cmp_nc, set
set2 calls cmp_nc, compute_knot_vector, set
set3 calls cmp_degree, set
set4 calls set
cmp_degree calls set, get_multiplicity
cmp_nc calls set, compute_multiplicity
compute_knot_vector calls repelem
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
get_multiplicity calls compute_multiplicity
example_ppm1 calls set_ring
shape_ring_2d calls set_ring
test_nurbs_surface calls set_ring