set_half_circle – ForCAD
set_half_circle Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
20 statements
Source File
private pure subroutine set_half_circle(this, center, radius)
Type Bound
nurbs_curve
Arguments
Type Intent Optional Attributes Name
class(nurbs_curve), intent(inout) :: this
real(kind=rk), intent(in), contiguous :: center(:)
real(kind=rk), intent(in) :: radius
Calls
Called by
Call graph
set_half_circle calls set
set1 calls cmp_degree, set
set1a calls cmp_degree, set
set2 calls cmp_nc, compute_knot_vector, set
set3 calls cmp_degree, set
set4 calls set
cmp_degree calls get_multiplicity
cmp_nc calls compute_multiplicity
compute_knot_vector calls repelem
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
get_multiplicity calls compute_multiplicity
shape_half_circle calls set_half_circle
test_nurbs_curve calls set_half_circle