show – ForCAD
show Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
19 statements
Source File
private impure subroutine show(this, vtkfile_Xc, vtkfile_Xg, vtkfile_Xth_in_Xg)
Type Bound
nurbs_volume
Arguments
Type Intent Optional Attributes Name
class(nurbs_volume), intent(inout) :: this
character(len=*), intent(in) :: vtkfile_Xc
character(len=*), intent(in) :: vtkfile_Xg
character(len=*), intent(in), optional :: vtkfile_Xth_in_Xg
Called by
Call graph
example3_volume calls show
example_bend_pipe calls show
example_helix_pipe calls show
example_nurbs_volume calls show
example_plate_hole_1_3d calls show
example_plate_hole_2_3d calls show
example_plate_hole_4_3d calls show
example_put_to_nurbs calls show
example_toroidal_pipe calls show
example_twist_taper calls show
lsq_fit_bspline_3d calls show
lsq_fit_nurbs_3d calls show
shape_c_3d calls show
shape_half_ring_3d calls show
shape_hexahedron calls show
shape_ring_3d calls show