show – ForCAD
show Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
19 statements
Source File
private impure subroutine show(this, vtkfile_Xc, vtkfile_Xg, vtkfile_Xth_in_Xg)
Type Bound
nurbs_surface
Arguments
Type Intent Optional Attributes Name
class(nurbs_surface), intent(inout) :: this
character(len=*), intent(in) :: vtkfile_Xc
character(len=*), intent(in) :: vtkfile_Xg
character(len=*), intent(in), optional :: vtkfile_Xth_in_Xg
Called by
Call graph
example3_surface calls show
example_nurbs_surface calls show
example_plate_hole_1_2d calls show
example_plate_hole_2_2d calls show
example_plate_hole_4_2d calls show
lsq_fit_bspline_2d calls show
lsq_fit_nurbs_2d calls show
shape_c_2d calls show
shape_half_ring_2d calls show
shape_ring_2d calls show
shape_tetragon calls show