solve – ForCAD
solve Function
Seyed Ali Ghasemi
BSD 3-Clause
44 statements
Source File
public pure function solve(A, B) result(X)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: A(:,:)
real(kind=rk), intent(in), contiguous :: B(:,:)
Return Value real(kind=rk), allocatable, (:,:)
Called by
Call graph
inv calls solve, inv
lsq_fit_bspline calls solve
lsq_fit_nurbs calls solve
poisson_iga_solver_2d calls solve, ansatz
poisson_iga_solver_3d calls solve, ansatz
test_forcad_utils calls solve, inv
ansatz calls inv
nearest_point2 calls inv
lsq_fit_bspline_1d calls lsq_fit_bspline
lsq_fit_bspline_2d calls lsq_fit_bspline
lsq_fit_bspline_3d calls lsq_fit_bspline
lsq_fit_nurbs_1d calls lsq_fit_nurbs
lsq_fit_nurbs_2d calls lsq_fit_nurbs
lsq_fit_nurbs_3d calls lsq_fit_nurbs
test_nurbs_volume calls lsq_fit_bspline, nearest_point2, cmp_volume
cmp_area calls ansatz
cmp_volume calls ansatz
nearest_point_2d calls nearest_point2
nearest_point_3d calls nearest_point2
test_nurbs_surface calls nearest_point2, cmp_area
compute_area calls cmp_area
compute_volume calls cmp_volume