tetragon_Xc – ForCAD
tetragon_Xc Function
Seyed Ali Ghasemi
BSD 3-Clause
15 statements
Source File
public pure function tetragon_Xc(L, nc) result(Xc)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: L(:)
integer, intent(in), contiguous :: nc(:)
Return Value real(kind=rk), allocatable, (:,:)
Called by
Call graph
set_tetragon calls tetragon_xc
test_forcad_utils calls tetragon_xc
example_ppm1 calls set_tetragon
example_ppm2 calls set_tetragon
example_ppm3 calls set_tetragon
fdm_test_surface calls set_tetragon
nearest_point_2d_bench calls set_tetragon
poisson_iga_solver_2d calls set_tetragon
shape_tetragon calls set_tetragon
test_nurbs_surface calls set_tetragon