basis_bspline_der – ForCAD
basis_bspline_der Interface
BSD 3-Clause
4 statements
Source File
public interface basis_bspline_der
Calls
Called by
Module Procedures
private pure subroutine basis_bspline_der_A(Xt, knot, nc, degree, dB, B)
Author
Seyed Ali Ghasemi
License
BSD 3-Clause
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: Xt
real(kind=rk), intent(in), contiguous :: knot(:)
integer, intent(in) :: nc
integer, intent(in) :: degree
real(kind=rk), intent(out) :: dB(nc)
real(kind=rk), intent(out) :: B(nc)
private pure subroutine basis_bspline_der_B(Xt, knot, nc, degree, dB)
Author
Seyed Ali Ghasemi
License
BSD 3-Clause
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: Xt
real(kind=rk), intent(in), contiguous :: knot(:)
integer, intent(in) :: nc
integer, intent(in) :: degree
real(kind=rk), intent(out) :: dB(nc)
Call graph
basis_bspline_der calls basis_bspline_der_a, basis_bspline_der_b
compute_dtgc_bspline_1d_scalar calls basis_bspline_der
compute_dtgc_bspline_1d_vector calls basis_bspline_der
compute_dtgc_bspline_2d_scalar calls basis_bspline_der
compute_dtgc_bspline_2d_vector calls basis_bspline_der
compute_dtgc_bspline_3d_scalar calls basis_bspline_der
compute_dtgc_bspline_3d_vector calls basis_bspline_der
compute_dtgc_nurbs_1d_scalar calls basis_bspline_der
compute_dtgc_nurbs_1d_vector calls basis_bspline_der
compute_dtgc_nurbs_2d_scalar calls basis_bspline_der
compute_dtgc_nurbs_2d_vector calls basis_bspline_der
compute_dtgc_nurbs_3d_scalar calls basis_bspline_der
compute_dtgc_nurbs_3d_vector calls basis_bspline_der
test_forcad_utils calls basis_bspline_der
compute_dtgc calls compute_dtgc_bspline_2d_scalar, compute_dtgc_bspline_2d_vector, compute_dtgc_nurbs_2d_scalar, compute_dtgc_nurbs_2d_vector, compute_dtgc_bspline_3d_scalar, compute_dtgc_bspline_3d_vector, compute_dtgc_nurbs_3d_scalar, compute_dtgc_nurbs_3d_vector, compute_dtgc_bspline_1d_scalar, compute_dtgc_bspline_1d_vector, compute_dtgc_nurbs_1d_scalar, compute_dtgc_nurbs_1d_vector
derivative_scalar calls compute_dtgc
derivative_vector calls compute_dtgc
ansatz calls derivative
test_nurbs_curve calls derivative, cmp_length
test_nurbs_surface calls derivative, cmp_area
test_nurbs_volume calls derivative, cmp_volume
cmp_area calls ansatz
cmp_length calls ansatz
cmp_volume calls ansatz
poisson_iga_solver_2d calls ansatz
poisson_iga_solver_3d calls ansatz
compute_area calls cmp_area
compute_length calls cmp_length
compute_volume calls cmp_volume