basis_bspline_2der – ForCAD
basis_bspline_2der Interface
BSD 3-Clause
5 statements
Source File
public interface basis_bspline_2der
Calls
Called by
Module Procedures
private pure subroutine basis_bspline_2der_A(Xt, knot, nc, degree, d2B, dB, B)
Author
Seyed Ali Ghasemi
License
BSD 3-Clause
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: Xt
real(kind=rk), intent(in), contiguous :: knot(:)
integer, intent(in) :: nc
integer, intent(in) :: degree
real(kind=rk), intent(out) :: d2B(nc)
real(kind=rk), intent(out) :: dB(nc)
real(kind=rk), intent(out) :: B(nc)
private pure subroutine basis_bspline_2der_B(Xt, knot, nc, degree, d2B, dB)
Author
Seyed Ali Ghasemi
License
BSD 3-Clause
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: Xt
real(kind=rk), intent(in), contiguous :: knot(:)
integer, intent(in) :: nc
integer, intent(in) :: degree
real(kind=rk), intent(out) :: d2B(nc)
real(kind=rk), intent(out) :: dB(nc)
private pure subroutine basis_bspline_2der_C(Xt, knot, nc, degree, d2B)
Author
Seyed Ali Ghasemi
License
BSD 3-Clause
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: Xt
real(kind=rk), intent(in), contiguous :: knot(:)
integer, intent(in) :: nc
integer, intent(in) :: degree
real(kind=rk), intent(out) :: d2B(nc)
Call graph
basis_bspline_2der calls basis_bspline_2der_a, basis_bspline_2der_b, basis_bspline_2der_c
compute_d2tgc_bspline_1d_scalar calls basis_bspline_2der
compute_d2tgc_bspline_1d_vector calls basis_bspline_2der
compute_d2tgc_bspline_2d_scalar calls basis_bspline_2der
compute_d2tgc_bspline_2d_vector calls basis_bspline_2der
compute_d2tgc_bspline_3d_scalar calls basis_bspline_2der
compute_d2tgc_bspline_3d_vector calls basis_bspline_2der
compute_d2tgc_nurbs_1d_scalar calls basis_bspline_2der
compute_d2tgc_nurbs_1d_vector calls basis_bspline_2der
compute_d2tgc_nurbs_2d_scalar calls basis_bspline_2der
compute_d2tgc_nurbs_2d_vector calls basis_bspline_2der
compute_d2tgc_nurbs_3d_scalar calls basis_bspline_2der
compute_d2tgc_nurbs_3d_vector calls basis_bspline_2der
test_forcad_utils calls basis_bspline_2der
compute_d2tgc calls compute_d2tgc_bspline_3d_scalar, compute_d2tgc_bspline_3d_vector, compute_d2tgc_nurbs_3d_scalar, compute_d2tgc_nurbs_3d_vector, compute_d2tgc_bspline_1d_scalar, compute_d2tgc_bspline_1d_vector, compute_d2tgc_nurbs_1d_scalar, compute_d2tgc_nurbs_1d_vector, compute_d2tgc_bspline_2d_scalar, compute_d2tgc_bspline_2d_vector, compute_d2tgc_nurbs_2d_scalar, compute_d2tgc_nurbs_2d_vector
derivative2_scalar calls compute_d2tgc
derivative2_vector calls compute_d2tgc
nearest_point2 calls derivative2
fdm_test_curve calls derivative2
fdm_test_surface calls derivative2
fdm_test_volume calls derivative2
test_nurbs_curve calls derivative2, nearest_point2
test_nurbs_surface calls derivative2, nearest_point2
test_nurbs_volume calls derivative2, nearest_point2
nearest_point_1d calls nearest_point2
nearest_point_2d calls nearest_point2
nearest_point_3d calls nearest_point2