compute_multiplicity – ForCAD
compute_multiplicity Interface
BSD 3-Clause
4 statements
Source File
public interface compute_multiplicity
Calls
Called by
Module Procedures
private pure function compute_multiplicity1(knot) result(multiplicity)
Author
Seyed Ali Ghasemi
License
BSD 3-Clause
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: knot(:)
Return Value integer, allocatable, (:)
private pure function compute_multiplicity2(knot, Xth) result(multiplicity)
Author
Seyed Ali Ghasemi
License
BSD 3-Clause
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: knot(:)
real(kind=rk), intent(in) :: Xth
Return Value integer
Call graph
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
cmp_nc calls compute_multiplicity
elevate_degree_a_5_9 calls compute_multiplicity
get_continuity calls compute_multiplicity
get_multiplicity calls compute_multiplicity
get_nc_dir calls compute_multiplicity
insert_knots calls compute_multiplicity, set
remove_knots calls compute_multiplicity, set
test_forcad_utils calls compute_multiplicity, elevate_degree_a_5_9
cmp_degree calls get_multiplicity
cmp_elem calls get_multiplicity
elevate_degree calls elevate_degree_a_5_9, set
set1 calls cmp_nc, cmp_degree
set2 calls cmp_nc
example1_curve calls insert_knots, remove_knots, elevate_degree, set
example3_surface calls insert_knots, remove_knots, elevate_degree, set
example3_volume calls insert_knots, remove_knots, cmp_elem, elevate_degree, set
example_bend_pipe calls insert_knots, elevate_degree, bend_pipe, set_ring
example_helix_pipe calls insert_knots, elevate_degree, build_helix, set_ring
example_nurbs_surface calls insert_knots, elevate_degree, set
example_nurbs_volume calls insert_knots, elevate_degree, set
example_toroidal_pipe calls insert_knots, elevate_degree, map_to_torus_sinez, set_ring
fdm_elevate_and_insert_1d calls insert_knots, elevate_degree, set
fdm_elevate_and_insert_2d calls insert_knots, elevate_degree, set
fdm_elevate_and_insert_3d calls insert_knots, elevate_degree, set
lsq_fit_bspline_1d calls get_continuity, set
lsq_fit_bspline_2d calls get_continuity, get_nc, set
lsq_fit_bspline_3d calls get_continuity, get_nc, set
lsq_fit_nurbs_1d calls get_continuity, set
lsq_fit_nurbs_2d calls get_continuity, get_nc, set
lsq_fit_nurbs_3d calls get_continuity, get_nc, set
poisson_iga_solver_2d calls insert_knots, get_nc, cmp_elem, ansatz, set_tetragon
poisson_iga_solver_3d calls insert_knots, get_nc, cmp_elem, ansatz, set_hexahedron
test_nurbs_curve calls cmp_nc, get_continuity, get_multiplicity, insert_knots, remove_knots, cmp_elem, elevate_degree, set, cmp_length, modify_wc, modify_xc, set_circle, set_half_circle
test_nurbs_surface calls cmp_nc, get_continuity, get_multiplicity, insert_knots, remove_knots, get_nc, cmp_elem, elevate_degree, set, cmp_area, modify_wc, modify_xc, set_c, set_half_ring, set_ring, set_tetragon
test_nurbs_volume calls cmp_nc, get_continuity, get_multiplicity, insert_knots, remove_knots, get_nc, cmp_elem, elevate_degree, set, cmp_volume, modify_wc, modify_xc, set_c, set_half_ring, set_hexahedron, set_ring
ansatz calls cmp_elem, set
bend_pipe calls get_nc, set
build_helix calls get_nc, set
cmp_area calls cmp_elem, ansatz
cmp_length calls cmp_elem, ansatz
cmp_volume calls cmp_elem, ansatz
map_to_torus_sinez calls get_nc, set
set1a calls cmp_degree
set3 calls cmp_degree
build_twist_taper calls set
modify_wc calls set
modify_xc calls set
set_c calls set
set_circle calls set
set_half_circle calls set
set_half_ring calls set
set_hexahedron calls set
set_ring calls set
set_tetragon calls set
compute_area calls set, cmp_area
compute_length calls set, cmp_length
compute_volume calls set, cmp_volume
example_nurbs_curve calls set
example_plate_hole_1_2d calls set
example_plate_hole_1_3d calls set
example_plate_hole_2_2d calls set
example_plate_hole_2_3d calls set
example_plate_hole_4_2d calls set
example_plate_hole_4_3d calls set
example_put_to_nurbs calls set
fdm_test_curve calls set
nearest_point_1d calls set
nearest_point_2d calls set
nearest_point_3d calls set
example_ppm1 calls set_ring, set_tetragon
example_ppm2 calls set_half_ring, set_tetragon
example_ppm3 calls modify_xc, set_tetragon
example_twist_taper calls build_twist_taper, set_hexahedron
fdm_test_surface calls set_tetragon
fdm_test_volume calls set_hexahedron
nearest_point_2d_bench calls set_tetragon
shape_c_1d calls set_c
shape_c_2d calls set_c
shape_c_3d calls set_c
shape_circle calls set_circle
shape_half_circle calls set_half_circle
shape_half_ring_2d calls set_half_ring
shape_half_ring_3d calls set_half_ring
shape_hexahedron calls set_hexahedron
shape_ring_2d calls set_ring
shape_ring_3d calls set_ring
shape_tetragon calls set_tetragon