compute_Tgc – ForCAD
compute_Tgc Interface
BSD 3-Clause
6 statements
Source File
public interface compute_Tgc
Calls
Called by
Module Procedures
private pure function compute_Tgc_nurbs_3d_vector(Xt, knot1, knot2, knot3, degree, nc, ng, Wc) result(Tgc)
Author
Seyed Ali Ghasemi
License
BSD 3-Clause
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: Xt(:,:)
real(kind=rk), intent(in), contiguous :: knot1(:)
real(kind=rk), intent(in), contiguous :: knot2(:)
real(kind=rk), intent(in), contiguous :: knot3(:)
integer, intent(in) :: degree(3)
integer, intent(in) :: nc(3)
integer, intent(in), optional :: ng(3)
real(kind=rk), intent(in), contiguous :: Wc(:)
Return Value real(kind=rk), allocatable, (:,:)
private pure function compute_Tgc_bspline_3d_vector(Xt, knot1, knot2, knot3, degree, nc, ng) result(Tgc)
Author
Seyed Ali Ghasemi
License
BSD 3-Clause
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: Xt(:,:)
real(kind=rk), intent(in), contiguous :: knot1(:)
real(kind=rk), intent(in), contiguous :: knot2(:)
real(kind=rk), intent(in), contiguous :: knot3(:)
integer, intent(in) :: degree(3)
integer, intent(in) :: nc(3)
integer, intent(in), optional :: ng(3)
Return Value real(kind=rk), allocatable, (:,:)
private pure function compute_Tgc_nurbs_3d_scalar(Xt, knot1, knot2, knot3, degree, nc, Wc) result(Tgc)
Author
Seyed Ali Ghasemi
License
BSD 3-Clause
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: Xt(:)
real(kind=rk), intent(in), contiguous :: knot1(:)
real(kind=rk), intent(in), contiguous :: knot2(:)
real(kind=rk), intent(in), contiguous :: knot3(:)
integer, intent(in) :: degree(3)
integer, intent(in) :: nc(3)
real(kind=rk), intent(in), contiguous :: Wc(:)
Return Value real(kind=rk), allocatable, (:)
private pure function compute_Tgc_bspline_3d_scalar(Xt, knot1, knot2, knot3, degree, nc) result(Tgc)
Author
Seyed Ali Ghasemi
License
BSD 3-Clause
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: Xt(:)
real(kind=rk), intent(in), contiguous :: knot1(:)
real(kind=rk), intent(in), contiguous :: knot2(:)
real(kind=rk), intent(in), contiguous :: knot3(:)
integer, intent(in) :: degree(3)
integer, intent(in) :: nc(3)
Return Value real(kind=rk), allocatable, (:)
Call graph
compute_tgc calls compute_tgc_bspline_3d_scalar, compute_tgc_bspline_3d_vector, compute_tgc_nurbs_3d_scalar, compute_tgc_nurbs_3d_vector
compute_tgc_bspline_3d_scalar calls kron, basis_bspline
compute_tgc_bspline_3d_vector calls kron, basis_bspline
compute_tgc_nurbs_3d_scalar calls kron, basis_bspline
compute_tgc_nurbs_3d_vector calls kron, basis_bspline
kron calls kron3, kron_t1_t1, kron_t1_t2
basis_scalar calls compute_tgc
basis_vector calls compute_tgc
poisson_iga_solver_3d calls basis
test_nurbs_volume calls basis