compute_Xg – ForCAD
compute_Xg Interface
BSD 3-Clause
6 statements
Source File
private interface compute_Xg
Calls
Called by
Module Procedures
private pure function compute_Xg_nurbs_3d(Xt, knot1, knot2, knot3, degree, nc, ng, Xc, Wc) result(Xg)
Author
Seyed Ali Ghasemi
License
BSD 3-Clause
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: Xt(:,:)
real(kind=rk), intent(in), contiguous :: knot1(:)
real(kind=rk), intent(in), contiguous :: knot2(:)
real(kind=rk), intent(in), contiguous :: knot3(:)
integer, intent(in) :: degree(3)
integer, intent(in) :: nc(3)
integer, intent(in), optional :: ng(3)
real(kind=rk), intent(in), contiguous :: Xc(:,:)
real(kind=rk), intent(in), contiguous :: Wc(:)
Return Value real(kind=rk), allocatable, (:,:)
private pure function compute_Xg_bspline_3d(Xt, knot1, knot2, knot3, degree, nc, ng, Xc) result(Xg)
Author
Seyed Ali Ghasemi
License
BSD 3-Clause
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: Xt(:,:)
real(kind=rk), intent(in), contiguous :: knot1(:)
real(kind=rk), intent(in), contiguous :: knot2(:)
real(kind=rk), intent(in), contiguous :: knot3(:)
integer, intent(in) :: degree(3)
integer, intent(in) :: nc(3)
integer, intent(in), optional :: ng(3)
real(kind=rk), intent(in), contiguous :: Xc(:,:)
Return Value real(kind=rk), allocatable, (:,:)
private pure function compute_Xg_nurbs_3d_1point(Xt, knot1, knot2, knot3, degree, nc, Xc, Wc) result(Xg)
Author
Seyed Ali Ghasemi
License
BSD 3-Clause
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: Xt(:)
real(kind=rk), intent(in), contiguous :: knot1(:)
real(kind=rk), intent(in), contiguous :: knot2(:)
real(kind=rk), intent(in), contiguous :: knot3(:)
integer, intent(in) :: degree(3)
integer, intent(in) :: nc(3)
real(kind=rk), intent(in), contiguous :: Xc(:,:)
real(kind=rk), intent(in), contiguous :: Wc(:)
Return Value real(kind=rk), (size(Xc,2))
private pure function compute_Xg_bspline_3d_1point(Xt, knot1, knot2, knot3, degree, nc, Xc) result(Xg)
Author
Seyed Ali Ghasemi
License
BSD 3-Clause
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: Xt(:)
real(kind=rk), intent(in), contiguous :: knot1(:)
real(kind=rk), intent(in), contiguous :: knot2(:)
real(kind=rk), intent(in), contiguous :: knot3(:)
integer, intent(in) :: degree(3)
integer, intent(in) :: nc(3)
real(kind=rk), intent(in), contiguous :: Xc(:,:)
Return Value real(kind=rk), (size(Xc,2))
Call graph
compute_xg calls compute_xg_bspline_3d, compute_xg_bspline_3d_1point, compute_xg_nurbs_3d, compute_xg_nurbs_3d_1point
compute_xg_bspline_3d calls kron, basis_bspline
compute_xg_bspline_3d_1point calls kron, basis_bspline
compute_xg_nurbs_3d calls cmp_tgc_3d
compute_xg_nurbs_3d_1point calls kron, basis_bspline
kron calls kron3, kron_t1_t1, kron_t1_t2
cmp_tgc_3d calls kron, basis_bspline
cmp_xg calls compute_xg
create calls compute_xg
export_xth_in_xg calls compute_xg
put_to_nurbs calls compute_xg
nearest_point2 calls cmp_xg, create
example3_volume calls create
example_bend_pipe calls create, export_xth_in_xg
example_helix_pipe calls create, export_xth_in_xg
example_nurbs_volume calls create, export_xth_in_xg
example_plate_hole_1_3d calls create, export_xth_in_xg
example_plate_hole_2_3d calls create, export_xth_in_xg
example_plate_hole_4_3d calls create, export_xth_in_xg
example_put_to_nurbs calls put_to_nurbs
example_toroidal_pipe calls create, export_xth_in_xg
example_twist_taper calls create, export_xth_in_xg
fdm_test_volume calls create
lsq_fit_bspline_3d calls create, export_xth_in_xg
lsq_fit_nurbs_3d calls create, export_xth_in_xg
nearest_point_3d calls create, nearest_point2
poisson_iga_solver_3d calls create
shape_c_3d calls create
shape_half_ring_3d calls create
shape_hexahedron calls create
shape_ring_3d calls create
test_nurbs_volume calls create, nearest_point2