compute_d2Tgc – ForCAD
compute_d2Tgc Interface
BSD 3-Clause
6 statements
Source File
private interface compute_d2Tgc
Calls
Called by
Module Procedures
private pure subroutine compute_d2Tgc_nurbs_3d_vector(Xt, knot1, knot2, knot3, degree, nc, ng, Wc, d2Tgc, dTgc, Tgc)
Author
Seyed Ali Ghasemi
License
BSD 3-Clause
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: Xt(:,:)
real(kind=rk), intent(in), contiguous :: knot1(:)
real(kind=rk), intent(in), contiguous :: knot2(:)
real(kind=rk), intent(in), contiguous :: knot3(:)
integer, intent(in) :: degree(3)
integer, intent(in) :: nc(3)
integer, intent(in) :: ng(3)
real(kind=rk), intent(in), contiguous :: Wc(:)
real(kind=rk), intent(out), allocatable :: d2Tgc(:,:,:)
real(kind=rk), intent(out), allocatable :: dTgc(:,:,:)
real(kind=rk), intent(out), allocatable :: Tgc(:,:)
private pure subroutine compute_d2Tgc_bspline_3d_vector(Xt, knot1, knot2, knot3, degree, nc, ng, d2Tgc, dTgc, Tgc)
Author
Seyed Ali Ghasemi
License
BSD 3-Clause
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: Xt(:,:)
real(kind=rk), intent(in), contiguous :: knot1(:)
real(kind=rk), intent(in), contiguous :: knot2(:)
real(kind=rk), intent(in), contiguous :: knot3(:)
integer, intent(in) :: degree(3)
integer, intent(in) :: nc(3)
integer, intent(in) :: ng(3)
real(kind=rk), intent(out), allocatable :: d2Tgc(:,:,:)
real(kind=rk), intent(out), allocatable :: dTgc(:,:,:)
real(kind=rk), intent(out), allocatable :: Tgc(:,:)
private pure subroutine compute_d2Tgc_nurbs_3d_scalar(Xt, knot1, knot2, knot3, degree, nc, Wc, d2Tgc, dTgc, Tgc)
Author
Seyed Ali Ghasemi
License
BSD 3-Clause
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: Xt(:)
real(kind=rk), intent(in), contiguous :: knot1(:)
real(kind=rk), intent(in), contiguous :: knot2(:)
real(kind=rk), intent(in), contiguous :: knot3(:)
integer, intent(in) :: degree(3)
integer, intent(in) :: nc(3)
real(kind=rk), intent(in), contiguous :: Wc(:)
real(kind=rk), intent(out), allocatable :: d2Tgc(:,:)
real(kind=rk), intent(out), allocatable :: dTgc(:,:)
real(kind=rk), intent(out), allocatable :: Tgc(:)
private pure subroutine compute_d2Tgc_bspline_3d_scalar(Xt, knot1, knot2, knot3, degree, nc, d2Tgc, dTgc, Tgc)
Author
Seyed Ali Ghasemi
License
BSD 3-Clause
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: Xt(:)
real(kind=rk), intent(in), contiguous :: knot1(:)
real(kind=rk), intent(in), contiguous :: knot2(:)
real(kind=rk), intent(in), contiguous :: knot3(:)
integer, intent(in) :: degree(3)
integer, intent(in) :: nc(3)
real(kind=rk), intent(out), allocatable :: d2Tgc(:,:)
real(kind=rk), intent(out), allocatable :: dTgc(:,:)
real(kind=rk), intent(out), allocatable :: Tgc(:)
Call graph
compute_d2tgc calls compute_d2tgc_bspline_3d_scalar, compute_d2tgc_bspline_3d_vector, compute_d2tgc_nurbs_3d_scalar, compute_d2tgc_nurbs_3d_vector
compute_d2tgc_bspline_3d_scalar calls basis_bspline_2der, kron
compute_d2tgc_bspline_3d_vector calls basis_bspline_2der, kron
compute_d2tgc_nurbs_3d_scalar calls basis_bspline_2der, kron
compute_d2tgc_nurbs_3d_vector calls basis_bspline_2der, kron
basis_bspline_2der calls basis_bspline_2der_a, basis_bspline_2der_b, basis_bspline_2der_c
derivative2_scalar calls compute_d2tgc
derivative2_vector calls compute_d2tgc
nearest_point2 calls derivative2
fdm_test_volume calls derivative2
test_nurbs_volume calls derivative2, nearest_point2
nearest_point_3d calls nearest_point2