compute_dTgc – ForCAD
compute_dTgc Interface
BSD 3-Clause
6 statements
Source File
public interface compute_dTgc
Calls
Called by
Module Procedures
private pure subroutine compute_dTgc_nurbs_3d_vector(Xt, knot1, knot2, knot3, degree, nc, ng, Wc, dTgc, Tgc)
Author
Seyed Ali Ghasemi
License
BSD 3-Clause
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: Xt(:,:)
real(kind=rk), intent(in), contiguous :: knot1(:)
real(kind=rk), intent(in), contiguous :: knot2(:)
real(kind=rk), intent(in), contiguous :: knot3(:)
integer, intent(in) :: degree(3)
integer, intent(in) :: nc(3)
integer, intent(in) :: ng(3)
real(kind=rk), intent(in), contiguous :: Wc(:)
real(kind=rk), intent(out), allocatable :: dTgc(:,:,:)
real(kind=rk), intent(out), allocatable :: Tgc(:,:)
private pure subroutine compute_dTgc_bspline_3d_vector(Xt, knot1, knot2, knot3, degree, nc, ng, dTgc, Tgc)
Author
Seyed Ali Ghasemi
License
BSD 3-Clause
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: Xt(:,:)
real(kind=rk), intent(in), contiguous :: knot1(:)
real(kind=rk), intent(in), contiguous :: knot2(:)
real(kind=rk), intent(in), contiguous :: knot3(:)
integer, intent(in) :: degree(3)
integer, intent(in) :: nc(3)
integer, intent(in) :: ng(3)
real(kind=rk), intent(out), allocatable :: dTgc(:,:,:)
real(kind=rk), intent(out), allocatable :: Tgc(:,:)
private pure subroutine compute_dTgc_nurbs_3d_scalar(Xt, knot1, knot2, knot3, degree, nc, Wc, dTgc, Tgc, elem)
Author
Seyed Ali Ghasemi
License
BSD 3-Clause
If elem is not present: Wc refers to the full weight vector. If elem is present: Wc refers to the element-local weight vector (Wce).
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: Xt(:)
real(kind=rk), intent(in), contiguous :: knot1(:)
real(kind=rk), intent(in), contiguous :: knot2(:)
real(kind=rk), intent(in), contiguous :: knot3(:)
integer, intent(in) :: degree(3)
integer, intent(in) :: nc(3)
real(kind=rk), intent(in), contiguous :: Wc(:)
real(kind=rk), intent(out), allocatable :: dTgc(:,:)
real(kind=rk), intent(out), allocatable :: Tgc(:)
integer, intent(in), optional :: elem(:)
private pure subroutine compute_dTgc_bspline_3d_scalar(Xt, knot1, knot2, knot3, degree, nc, dTgc, Tgc, elem)
Author
Seyed Ali Ghasemi
License
BSD 3-Clause
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: Xt(:)
real(kind=rk), intent(in), contiguous :: knot1(:)
real(kind=rk), intent(in), contiguous :: knot2(:)
real(kind=rk), intent(in), contiguous :: knot3(:)
integer, intent(in) :: degree(3)
integer, intent(in) :: nc(3)
real(kind=rk), intent(out), allocatable :: dTgc(:,:)
real(kind=rk), intent(out), allocatable :: Tgc(:)
integer, intent(in), optional :: elem(:)
Call graph
compute_dtgc calls compute_dtgc_bspline_3d_scalar, compute_dtgc_bspline_3d_vector, compute_dtgc_nurbs_3d_scalar, compute_dtgc_nurbs_3d_vector
compute_dtgc_bspline_3d_scalar calls basis_bspline_der, kron
compute_dtgc_bspline_3d_vector calls basis_bspline_der, kron
compute_dtgc_nurbs_3d_scalar calls basis_bspline_der, kron
compute_dtgc_nurbs_3d_vector calls basis_bspline_der, kron
basis_bspline_der calls basis_bspline_der_a, basis_bspline_der_b
kron calls kron3, kron_t1_t1, kron_t1_t2
derivative_scalar calls compute_dtgc
derivative_vector calls compute_dtgc
ansatz calls derivative
test_nurbs_volume calls derivative, cmp_volume
cmp_volume calls ansatz
poisson_iga_solver_3d calls ansatz
compute_volume calls cmp_volume