compute_dTgc – ForCAD
compute_dTgc Interface
BSD 3-Clause
6 statements
Source File
private interface compute_dTgc
Calls
Called by
Module Procedures
private pure subroutine compute_dTgc_nurbs_1d_vector(Xt, knot, degree, nc, ng, Wc, dTgc, Tgc)
Author
Seyed Ali Ghasemi
License
BSD 3-Clause
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: Xt(:)
real(kind=rk), intent(in), contiguous :: knot(:)
integer, intent(in) :: degree
integer, intent(in) :: nc
integer, intent(in) :: ng
real(kind=rk), intent(in), contiguous :: Wc(:)
real(kind=rk), intent(out), allocatable :: dTgc(:,:)
real(kind=rk), intent(out), allocatable :: Tgc(:,:)
private pure subroutine compute_dTgc_bspline_1d_vector(Xt, knot, degree, nc, ng, dTgc, Tgc)
Author
Seyed Ali Ghasemi
License
BSD 3-Clause
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: Xt(:)
real(kind=rk), intent(in), contiguous :: knot(:)
integer, intent(in) :: degree
integer, intent(in) :: nc
integer, intent(in) :: ng
real(kind=rk), intent(out), allocatable :: dTgc(:,:)
real(kind=rk), intent(out), allocatable :: Tgc(:,:)
private pure subroutine compute_dTgc_nurbs_1d_scalar(Xt, knot, degree, nc, Wc, dTgc, Tgc, elem)
Author
Seyed Ali Ghasemi
License
BSD 3-Clause
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: Xt
real(kind=rk), intent(in), contiguous :: knot(:)
integer, intent(in) :: degree
integer, intent(in) :: nc
real(kind=rk), intent(in), contiguous :: Wc(:)
real(kind=rk), intent(out), allocatable :: dTgc(:)
real(kind=rk), intent(out), allocatable :: Tgc(:)
integer, intent(in), optional :: elem(:)
private pure subroutine compute_dTgc_bspline_1d_scalar(Xt, knot, degree, nc, dTgc, Tgc, elem)
Author
Seyed Ali Ghasemi
License
BSD 3-Clause
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: Xt
real(kind=rk), intent(in), contiguous :: knot(:)
integer, intent(in) :: degree
integer, intent(in) :: nc
real(kind=rk), intent(out), allocatable :: dTgc(:)
real(kind=rk), intent(out), allocatable :: Tgc(:)
integer, intent(in), optional :: elem(:)
Call graph
compute_dtgc calls compute_dtgc_bspline_1d_scalar, compute_dtgc_bspline_1d_vector, compute_dtgc_nurbs_1d_scalar, compute_dtgc_nurbs_1d_vector
compute_dtgc_bspline_1d_scalar calls basis_bspline_der
compute_dtgc_bspline_1d_vector calls basis_bspline_der
compute_dtgc_nurbs_1d_scalar calls basis_bspline_der
compute_dtgc_nurbs_1d_vector calls basis_bspline_der
derivative_scalar calls compute_dtgc
derivative_vector calls compute_dtgc
ansatz calls derivative
test_nurbs_curve calls derivative, cmp_length
cmp_length calls ansatz
compute_length calls cmp_length