compute_dTgc – ForCAD
compute_dTgc Interface
BSD 3-Clause
44 statements
Source File
private interface compute_dTgc
Called by
Subroutines
private pure subroutine compute_dTgc_bspline_3d_scalar(f_Xt, f_knot1, f_knot2, f_knot3, f_degree, f_nc, f_dTgc, f_Tgc, f_elem)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: f_Xt(:)
real(kind=rk), intent(in), contiguous :: f_knot1(:)
real(kind=rk), intent(in), contiguous :: f_knot2(:)
real(kind=rk), intent(in), contiguous :: f_knot3(:)
integer, intent(in) :: f_degree(3)
integer, intent(in) :: f_nc(3)
real(kind=rk), intent(out), allocatable :: f_dTgc(:,:)
real(kind=rk), intent(out), allocatable :: f_Tgc(:)
integer, intent(in), optional :: f_elem(:)
private pure subroutine compute_dTgc_bspline_3d_vector(f_Xt, f_knot1, f_knot2, f_knot3, f_degree, f_nc, f_ng, f_dTgc, f_Tgc)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: f_Xt(:,:)
real(kind=rk), intent(in), contiguous :: f_knot1(:)
real(kind=rk), intent(in), contiguous :: f_knot2(:)
real(kind=rk), intent(in), contiguous :: f_knot3(:)
integer, intent(in) :: f_degree(3)
integer, intent(in) :: f_nc(3)
integer, intent(in) :: f_ng(3)
real(kind=rk), intent(out), allocatable :: f_dTgc(:,:,:)
real(kind=rk), intent(out), allocatable :: f_Tgc(:,:)
private pure subroutine compute_dTgc_nurbs_3d_scalar(f_Xt, f_knot1, f_knot2, f_knot3, f_degree, f_nc, f_Wc, f_dTgc, f_Tgc, f_elem)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: f_Xt(:)
real(kind=rk), intent(in), contiguous :: f_knot1(:)
real(kind=rk), intent(in), contiguous :: f_knot2(:)
real(kind=rk), intent(in), contiguous :: f_knot3(:)
integer, intent(in) :: f_degree(3)
integer, intent(in) :: f_nc(3)
real(kind=rk), intent(in), contiguous :: f_Wc(:)
real(kind=rk), intent(out), allocatable :: f_dTgc(:,:)
real(kind=rk), intent(out), allocatable :: f_Tgc(:)
integer, intent(in), optional :: f_elem(:)
private pure subroutine compute_dTgc_nurbs_3d_vector(f_Xt, f_knot1, f_knot2, f_knot3, f_degree, f_nc, f_ng, f_Wc, f_dTgc, f_Tgc)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: f_Xt(:,:)
real(kind=rk), intent(in), contiguous :: f_knot1(:)
real(kind=rk), intent(in), contiguous :: f_knot2(:)
real(kind=rk), intent(in), contiguous :: f_knot3(:)
integer, intent(in) :: f_degree(3)
integer, intent(in) :: f_nc(3)
integer, intent(in) :: f_ng(3)
real(kind=rk), intent(in), contiguous :: f_Wc(:)
real(kind=rk), intent(out), allocatable :: f_dTgc(:,:,:)
real(kind=rk), intent(out), allocatable :: f_Tgc(:,:)
Call graph
derivative_scalar calls compute_dtgc
derivative_vector calls compute_dtgc
ansatz calls derivative
test_nurbs_volume calls derivative, cmp_volume
cmp_volume calls ansatz
compute_volume calls cmp_volume