dyad – ForCAD
dyad Interface
BSD 3-Clause
3 statements
Source File
public interface dyad
Calls
Called by
Module Procedures
private pure function dyad_t1_t1(a, b) result(c)
Author
Seyed Ali Ghasemi
License
BSD 3-Clause
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: a(:)
real(kind=rk), intent(in), contiguous :: b(:)
Return Value real(kind=rk), allocatable, (:,:)
Call graph
dyad calls dyad_t1_t1
ansatz calls dyad
test_forcad_utils calls dyad
cmp_length calls ansatz
compute_length calls cmp_length
test_nurbs_curve calls cmp_length