elemConn_Cn – ForCAD
elemConn_Cn Interface
BSD 3-Clause
5 statements
Source File
public interface elemConn_Cn
Calls
Called by
Module Procedures
private pure subroutine cmp_elemConn_Cn_L(nnode, p, Xth, vecKnot_mul, elemConn)
Author
Seyed Ali Ghasemi
License
BSD 3-Clause
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nnode
integer, intent(in) :: p
real(kind=rk), intent(in), contiguous :: Xth(:)
integer, intent(in), contiguous :: vecKnot_mul(:)
integer, intent(out), allocatable :: elemConn(:,:)
private pure subroutine cmp_elemConn_Cn_S(nnode1, nnode2, p1, p2, Xth1, Xth2, vecKnot_mul1, vecKnot_mul2, elemConn)
Author
Seyed Ali Ghasemi
License
BSD 3-Clause
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nnode1
integer, intent(in) :: nnode2
integer, intent(in) :: p1
integer, intent(in) :: p2
real(kind=rk), intent(in), contiguous :: Xth1(:)
real(kind=rk), intent(in), contiguous :: Xth2(:)
integer, intent(in), contiguous :: vecKnot_mul1(:)
integer, intent(in), contiguous :: vecKnot_mul2(:)
integer, intent(out), allocatable :: elemConn(:,:)
private pure subroutine cmp_elemConn_Cn_V(nnode1, nnode2, nnode3, p1, p2, p3, Xth1, Xth2, Xth3, vecKnot_mul1, vecKnot_mul2, vecKnot_mul3, elemConn)
Author
Seyed Ali Ghasemi
License
BSD 3-Clause
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nnode1
integer, intent(in) :: nnode2
integer, intent(in) :: nnode3
integer, intent(in) :: p1
integer, intent(in) :: p2
integer, intent(in) :: p3
real(kind=rk), intent(in), contiguous :: Xth1(:)
real(kind=rk), intent(in), contiguous :: Xth2(:)
real(kind=rk), intent(in), contiguous :: Xth3(:)
integer, intent(in), contiguous :: vecKnot_mul1(:)
integer, intent(in), contiguous :: vecKnot_mul2(:)
integer, intent(in), contiguous :: vecKnot_mul3(:)
integer, intent(out), allocatable :: elemConn(:,:)
Call graph
elemconn_cn calls cmp_elemconn_cn_l, cmp_elemconn_cn_s, cmp_elemconn_cn_v
cmp_elem calls elemconn_cn
ansatz calls cmp_elem
cmp_area calls cmp_elem, ansatz
cmp_length calls cmp_elem, ansatz
cmp_volume calls cmp_elem, ansatz
export_xth calls cmp_elem
example3_volume calls cmp_elem, export_xth
poisson_iga_solver_2d calls cmp_elem, ansatz
poisson_iga_solver_3d calls cmp_elem, ansatz
test_nurbs_curve calls cmp_elem, cmp_length, export_xth
test_nurbs_surface calls cmp_elem, cmp_area, export_xth
test_nurbs_volume calls cmp_elem, cmp_volume, export_xth
compute_area calls cmp_area
compute_length calls cmp_length
compute_volume calls cmp_volume
example1_curve calls export_xth
example3_surface calls export_xth