elemConn_C0 – ForCAD
elemConn_C0 Interface
BSD 3-Clause
5 statements
Source File
public interface elemConn_C0
Calls
Called by
Module Procedures
private pure function cmp_elemConn_C0_L(nnode, p) result(elemConn)
Author
Seyed Ali Ghasemi
License
BSD 3-Clause
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nnode
integer, intent(in) :: p
Return Value integer, allocatable, (:,:)
private pure function cmp_elemConn_C0_S(nnode1, nnode2, p1, p2) result(elemConn)
Author
Seyed Ali Ghasemi
License
BSD 3-Clause
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nnode1
integer, intent(in) :: nnode2
integer, intent(in) :: p1
integer, intent(in) :: p2
Return Value integer, allocatable, (:,:)
private pure function cmp_elemConn_C0_V(nnode1, nnode2, nnode3, p1, p2, p3) result(elemConn)
Author
Seyed Ali Ghasemi
License
BSD 3-Clause
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nnode1
integer, intent(in) :: nnode2
integer, intent(in) :: nnode3
integer, intent(in) :: p1
integer, intent(in) :: p2
integer, intent(in) :: p3
Return Value integer, allocatable, (:,:)
Call graph
elemconn_c0 calls cmp_elemconn_c0_l, cmp_elemconn_c0_s, cmp_elemconn_c0_v
cmp_elem_xc_vis calls elemconn_c0
cmp_elem_xg_vis calls elemconn_c0
cmp_elem_xth calls elemconn_c0
test_forcad_utils calls elemconn_c0
export_xc calls cmp_elem_xc_vis
export_xg calls cmp_elem_xg_vis
export_xth calls cmp_elem_xth
test_nurbs_curve calls cmp_elem_xc_vis, cmp_elem_xg_vis, export_xc, export_xg, export_xth
test_nurbs_surface calls cmp_elem_xc_vis, cmp_elem_xg_vis, export_xc, export_xg, export_xth
test_nurbs_volume calls cmp_elem_xc_vis, cmp_elem_xg_vis, export_xc, export_xg, export_xth
example1_curve calls export_xc, export_xg, export_xth
example3_surface calls export_xc, export_xg, export_xth
example3_volume calls export_xc, export_xg, export_xth
example_bend_pipe calls export_xc, export_xg
example_helix_pipe calls export_xc, export_xg
example_nurbs_curve calls export_xc, export_xg
example_nurbs_surface calls export_xc, export_xg
example_nurbs_volume calls export_xc, export_xg
example_plate_hole_1_2d calls export_xc, export_xg
example_plate_hole_1_3d calls export_xc, export_xg
example_plate_hole_2_2d calls export_xc, export_xg
example_plate_hole_2_3d calls export_xc, export_xg
example_plate_hole_4_2d calls export_xc, export_xg
example_plate_hole_4_3d calls export_xc, export_xg
example_put_to_nurbs calls export_xc, export_xg
example_toroidal_pipe calls export_xc, export_xg
example_twist_taper calls export_xc, export_xg
lsq_fit_bspline_1d calls export_xc, export_xg
lsq_fit_bspline_2d calls export_xc, export_xg
lsq_fit_bspline_3d calls export_xc, export_xg
lsq_fit_nurbs_1d calls export_xc, export_xg
lsq_fit_nurbs_2d calls export_xc, export_xg
lsq_fit_nurbs_3d calls export_xc, export_xg
poisson_iga_solver_2d calls export_xc, export_xg
poisson_iga_solver_3d calls export_xc, export_xg
shape_c_1d calls export_xc, export_xg
shape_c_2d calls export_xc, export_xg
shape_c_3d calls export_xc, export_xg
shape_circle calls export_xc, export_xg
shape_half_circle calls export_xc, export_xg
shape_half_ring_2d calls export_xc, export_xg
shape_half_ring_3d calls export_xc, export_xg
shape_hexahedron calls export_xc, export_xg
shape_ring_2d calls export_xc, export_xg
shape_ring_3d calls export_xc, export_xg
shape_tetragon calls export_xc, export_xg