gauss_leg – ForCAD
gauss_leg Interface
BSD 3-Clause
5 statements
Source File
public interface gauss_leg
Calls
Called by
Module Procedures
private pure subroutine gauss_legendre_1D(interval, degree, Xksi, Wksi)
Author
Seyed Ali Ghasemi
License
BSD 3-Clause
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: interval(:)
integer, intent(in) :: degree
real(kind=rk), intent(out), allocatable :: Xksi(:)
real(kind=rk), intent(out), allocatable :: Wksi(:)
private pure subroutine gauss_legendre_2D(interval1, interval2, degree, Xksi, Wksi)
Author
Seyed Ali Ghasemi
License
BSD 3-Clause
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: interval1(:)
real(kind=rk), intent(in), contiguous :: interval2(:)
integer, intent(in), contiguous :: degree(:)
real(kind=rk), intent(out), allocatable :: Xksi(:,:)
real(kind=rk), intent(out), allocatable :: Wksi(:)
private pure subroutine gauss_legendre_3D(interval1, interval2, interval3, degree, Xksi, Wksi)
Author
Seyed Ali Ghasemi
License
BSD 3-Clause
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: interval1(:)
real(kind=rk), intent(in), contiguous :: interval2(:)
real(kind=rk), intent(in), contiguous :: interval3(:)
integer, intent(in), contiguous :: degree(:)
real(kind=rk), intent(out), allocatable :: Xksi(:,:)
real(kind=rk), intent(out), allocatable :: Wksi(:)
Call graph
gauss_leg calls gauss_legendre_1d, gauss_legendre_2d, gauss_legendre_3d
gauss_legendre_1d calls gauss_legendre
gauss_legendre_2d calls kron, ndgrid, gauss_legendre
gauss_legendre_3d calls kron, ndgrid, gauss_legendre
kron calls kron3, kron_t1_t1, kron_t1_t2
ndgrid calls ndgrid2, ndgrid3
ansatz calls gauss_leg
test_forcad_utils calls gauss_leg
cmp_area calls ansatz
cmp_length calls ansatz
cmp_volume calls ansatz
poisson_iga_solver_2d calls ansatz
poisson_iga_solver_3d calls ansatz
compute_area calls cmp_area
compute_length calls cmp_length
compute_volume calls cmp_volume
test_nurbs_curve calls cmp_length
test_nurbs_surface calls cmp_area
test_nurbs_volume calls cmp_volume