kron – ForCAD
kron Interface
BSD 3-Clause
5 statements
Source File
public interface kron
Calls
Called by
Module Procedures
private pure function kron_t1_t1(u, v) result(w)
Author
Seyed Ali Ghasemi
License
BSD 3-Clause
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: u(:)
real(kind=rk), intent(in), contiguous :: v(:)
Return Value real(kind=rk), (size(u)*size(v))
private pure function kron_t1_t2(u, A) result(B)
Author
Seyed Ali Ghasemi
License
BSD 3-Clause
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: u(:)
real(kind=rk), intent(in), contiguous :: A(:,:)
Return Value real(kind=rk), (size(u)*size(A,1),size(A,2))
private pure function kron3(u, v, w) result(out)
Author
Seyed Ali Ghasemi
License
BSD 3-Clause
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: u(:)
real(kind=rk), intent(in), contiguous :: v(:)
real(kind=rk), intent(in), contiguous :: w(:)
Return Value real(kind=rk), (size(u)*size(v)*size(w))
Call graph
kron calls kron3, kron_t1_t1, kron_t1_t2
cmp_tgc_2d calls kron
cmp_tgc_3d calls kron
compute_d2tgc_bspline_2d_scalar calls kron
compute_d2tgc_bspline_2d_vector calls kron
compute_d2tgc_bspline_3d_scalar calls kron
compute_d2tgc_bspline_3d_vector calls kron
compute_d2tgc_nurbs_2d_scalar calls kron
compute_d2tgc_nurbs_2d_vector calls kron
compute_d2tgc_nurbs_3d_scalar calls kron
compute_d2tgc_nurbs_3d_vector calls kron
compute_dtgc_bspline_2d_scalar calls kron
compute_dtgc_bspline_2d_vector calls kron
compute_dtgc_bspline_3d_scalar calls kron
compute_dtgc_bspline_3d_vector calls kron
compute_dtgc_nurbs_2d_scalar calls kron
compute_dtgc_nurbs_2d_vector calls kron
compute_dtgc_nurbs_3d_scalar calls kron
compute_dtgc_nurbs_3d_vector calls kron
compute_tgc_bspline_2d_scalar calls kron
compute_tgc_bspline_2d_vector calls kron
compute_tgc_bspline_3d_scalar calls kron
compute_tgc_bspline_3d_vector calls kron
compute_tgc_nurbs_2d_scalar calls kron
compute_tgc_nurbs_2d_vector calls kron
compute_tgc_nurbs_3d_scalar calls kron
compute_tgc_nurbs_3d_vector calls kron
compute_xg_bspline_2d calls kron
compute_xg_bspline_2d_1point calls kron
compute_xg_bspline_3d calls kron
compute_xg_bspline_3d_1point calls kron
compute_xg_nurbs_2d_1point calls kron
compute_xg_nurbs_3d_1point calls kron
gauss_legendre_2d calls kron
gauss_legendre_3d calls kron
lsq_fit_bspline calls kron
test_forcad_utils calls kron, gauss_leg
compute_d2tgc calls compute_d2tgc_bspline_3d_scalar, compute_d2tgc_bspline_3d_vector, compute_d2tgc_nurbs_3d_scalar, compute_d2tgc_nurbs_3d_vector, compute_d2tgc_bspline_2d_scalar, compute_d2tgc_bspline_2d_vector, compute_d2tgc_nurbs_2d_scalar, compute_d2tgc_nurbs_2d_vector
compute_dtgc calls compute_dtgc_bspline_3d_scalar, compute_dtgc_bspline_3d_vector, compute_dtgc_nurbs_3d_scalar, compute_dtgc_nurbs_3d_vector, compute_dtgc_bspline_2d_scalar, compute_dtgc_bspline_2d_vector, compute_dtgc_nurbs_2d_scalar, compute_dtgc_nurbs_2d_vector
compute_tgc calls compute_tgc_bspline_3d_scalar, compute_tgc_bspline_3d_vector, compute_tgc_nurbs_3d_scalar, compute_tgc_nurbs_3d_vector, compute_tgc_bspline_2d_scalar, compute_tgc_bspline_2d_vector, compute_tgc_nurbs_2d_scalar, compute_tgc_nurbs_2d_vector
compute_xg calls compute_xg_bspline_3d, compute_xg_bspline_3d_1point, compute_xg_nurbs_3d_1point, compute_xg_nurbs_3d, compute_xg_bspline_2d, compute_xg_bspline_2d_1point, compute_xg_nurbs_2d_1point, compute_xg_nurbs_2d
gauss_leg calls gauss_legendre_2d, gauss_legendre_3d
compute_xg_nurbs_2d calls cmp_tgc_2d
compute_xg_nurbs_3d calls cmp_tgc_3d
lsq_fit_bspline_2d calls lsq_fit_bspline, create
lsq_fit_bspline_3d calls lsq_fit_bspline, create
test_nurbs_volume calls lsq_fit_bspline, create, basis, derivative, derivative2, cmp_volume, nearest_point2
ansatz calls gauss_leg, derivative
basis_scalar calls compute_tgc
basis_vector calls compute_tgc
cmp_xg calls compute_xg
create calls compute_xg
derivative2_scalar calls compute_d2tgc
derivative2_vector calls compute_d2tgc
derivative_scalar calls compute_dtgc
derivative_vector calls compute_dtgc
export_xth_in_xg calls compute_xg
put_to_nurbs calls compute_xg
cmp_area calls ansatz
cmp_length calls ansatz
cmp_volume calls ansatz
nearest_point2 calls cmp_xg, create, derivative2
example3_surface calls create
example3_volume calls create
example_bend_pipe calls create, export_xth_in_xg
example_helix_pipe calls create, export_xth_in_xg
example_nurbs_surface calls create, export_xth_in_xg
example_nurbs_volume calls create, export_xth_in_xg
example_plate_hole_1_2d calls create, export_xth_in_xg
example_plate_hole_1_3d calls create, export_xth_in_xg
example_plate_hole_2_2d calls create, export_xth_in_xg
example_plate_hole_2_3d calls create, export_xth_in_xg
example_plate_hole_4_2d calls create, export_xth_in_xg
example_plate_hole_4_3d calls create, export_xth_in_xg
example_ppm1 calls create
example_ppm2 calls create
example_ppm3 calls create
example_put_to_nurbs calls put_to_nurbs
example_toroidal_pipe calls create, export_xth_in_xg
example_twist_taper calls create, export_xth_in_xg
fdm_test_surface calls create, derivative2
fdm_test_volume calls create, derivative2
nearest_point_2d calls create, nearest_point2
nearest_point_2d_bench calls create
nearest_point_3d calls create, nearest_point2
poisson_iga_solver_2d calls ansatz, create, basis
poisson_iga_solver_3d calls ansatz, create, basis
shape_c_2d calls create
shape_c_3d calls create
shape_half_ring_2d calls create
shape_half_ring_3d calls create
shape_hexahedron calls create
shape_ring_2d calls create
shape_ring_3d calls create
shape_tetragon calls create
test_nurbs_surface calls create, basis, derivative2, derivative, cmp_area, nearest_point2
compute_area calls cmp_area
compute_length calls cmp_length
compute_volume calls cmp_volume
test_nurbs_curve calls cmp_length