ndgrid – ForCAD
ndgrid Interface
BSD 3-Clause
4 statements
Source File
public interface ndgrid
Calls
Called by
Module Procedures
private pure subroutine ndgrid2(X_dir1, X_dir2, Xt)
Author
Seyed Ali Ghasemi
License
BSD 3-Clause
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: X_dir1(:)
real(kind=rk), intent(in), contiguous :: X_dir2(:)
real(kind=rk), intent(out), allocatable :: Xt(:,:)
private pure subroutine ndgrid3(X_dir1, X_dir2, X_dir3, Xt)
Author
Seyed Ali Ghasemi
License
BSD 3-Clause
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: X_dir1(:)
real(kind=rk), intent(in), contiguous :: X_dir2(:)
real(kind=rk), intent(in), contiguous :: X_dir3(:)
real(kind=rk), intent(out), allocatable :: Xt(:,:)
Call graph
ndgrid calls ndgrid2, ndgrid3
ansatz calls ndgrid, gauss_leg, derivative
basis_vector calls ndgrid
create calls ndgrid
derivative2_vector calls ndgrid
derivative_vector calls ndgrid
export_xth calls ndgrid
gauss_legendre_2d calls ndgrid
gauss_legendre_3d calls ndgrid
lsq_fit_bspline_2d calls ndgrid, create
lsq_fit_bspline_3d calls ndgrid, create
test_forcad_utils calls ndgrid, gauss_leg
test_nurbs_surface calls ndgrid, create, export_xth, basis, derivative, derivative2, cmp_area, nearest_point2
test_nurbs_volume calls ndgrid, create, export_xth, basis, derivative2, derivative, cmp_volume, nearest_point2
gauss_leg calls gauss_legendre_2d, gauss_legendre_3d
cmp_area calls ansatz
cmp_volume calls ansatz
nearest_point2 calls create, derivative2
example1_curve calls export_xth
example3_surface calls create, export_xth
example3_volume calls create, export_xth
example_bend_pipe calls create
example_helix_pipe calls create
example_nurbs_surface calls create
example_nurbs_volume calls create
example_ppm1 calls create
example_ppm2 calls create
example_ppm3 calls create
example_toroidal_pipe calls create
example_twist_taper calls create
fdm_test_surface calls create, derivative2
fdm_test_volume calls create, derivative2
nearest_point_2d calls create, nearest_point2
nearest_point_2d_bench calls create
nearest_point_3d calls create, nearest_point2
poisson_iga_solver_2d calls ansatz, create, basis
poisson_iga_solver_3d calls ansatz, create, basis
shape_c_2d calls create
shape_c_3d calls create
shape_half_ring_2d calls create
shape_half_ring_3d calls create
shape_hexahedron calls create
shape_ring_2d calls create
shape_ring_3d calls create
shape_tetragon calls create
test_nurbs_curve calls export_xth, cmp_length
compute_area calls cmp_area
compute_volume calls cmp_volume
cmp_length calls ansatz
compute_length calls cmp_length