nearest_point_help_1d – ForCAD
nearest_point_help_1d Interface
BSD 3-Clause
10 statements
Source File
interface
Called by
private pure function nearest_point_help_1d(f_ng, f_Xg, f_point_Xg) result(f_distances)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: f_ng
real(kind=rk), intent(in), contiguous :: f_Xg(:,:)
real(kind=rk), intent(in), contiguous :: f_point_Xg(:)
Return Value real(kind=rk),allocatable,(:)
Call graph
nearest_point calls nearest_point_help_1d
nearest_point2 calls nearest_point
nearest_point_1d calls nearest_point, nearest_point2
test_nurbs_curve calls nearest_point, nearest_point2