nearest_point_help_2d – ForCAD
nearest_point_help_2d Interface
BSD 3-Clause
9 statements
Source File
interface
Called by
private pure function nearest_point_help_2d(f_ng, f_Xg, f_point_Xg) result(f_distances)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: f_ng(2)
real(kind=rk), intent(in), contiguous :: f_Xg(:,:)
real(kind=rk), intent(in), contiguous :: f_point_Xg(:)
Return Value real(kind=rk),allocatable,(:)
Call graph
nearest_point calls nearest_point_help_2d
nearest_point2 calls nearest_point_help_2d
nearest_point_2d calls nearest_point, nearest_point2
nearest_point_2d_bench calls nearest_point