unique – ForCAD
unique Interface
BSD 3-Clause
4 statements
Source File
public interface unique
Calls
Called by
Module Procedures
private pure function unique_integer(vec) result(output)
Author
Seyed Ali Ghasemi
License
BSD 3-Clause
Arguments
Type Intent Optional Attributes Name
integer, intent(in), contiguous :: vec(:)
Return Value integer, allocatable, (:)
private pure function unique_real(vec) result(output)
Author
Seyed Ali Ghasemi
License
BSD 3-Clause
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: vec(:)
Return Value real(kind=rk), allocatable, (:)
Call graph
unique calls unique_integer, unique_real
ansatz calls unique, cmp_elem
cmp_elem calls unique
cmp_elem_xth calls unique
export_xth calls unique, cmp_elem_xth
export_xth_in_xg calls unique
test_forcad_utils calls unique
cmp_area calls ansatz, cmp_elem
cmp_length calls ansatz, cmp_elem
cmp_volume calls ansatz, cmp_elem
example1_curve calls export_xth
example3_surface calls export_xth
example3_volume calls cmp_elem, export_xth
example_bend_pipe calls export_xth_in_xg
example_helix_pipe calls export_xth_in_xg
example_nurbs_surface calls export_xth_in_xg
example_nurbs_volume calls export_xth_in_xg
example_plate_hole_1_2d calls export_xth_in_xg
example_plate_hole_1_3d calls export_xth_in_xg
example_plate_hole_2_2d calls export_xth_in_xg
example_plate_hole_2_3d calls export_xth_in_xg
example_plate_hole_4_2d calls export_xth_in_xg
example_plate_hole_4_3d calls export_xth_in_xg
example_toroidal_pipe calls export_xth_in_xg
example_twist_taper calls export_xth_in_xg
lsq_fit_bspline_2d calls export_xth_in_xg
lsq_fit_bspline_3d calls export_xth_in_xg
lsq_fit_nurbs_2d calls export_xth_in_xg
lsq_fit_nurbs_3d calls export_xth_in_xg
poisson_iga_solver_2d calls ansatz, cmp_elem
poisson_iga_solver_3d calls ansatz, cmp_elem
test_nurbs_curve calls cmp_elem, export_xth, cmp_length
test_nurbs_surface calls cmp_elem, export_xth, cmp_area
test_nurbs_volume calls cmp_elem, export_xth, cmp_volume
compute_area calls cmp_area
compute_length calls cmp_length
compute_volume calls cmp_volume