compute_volume – ForCAD
compute_volume Program
BSD 3-Clause
18 statements
Source File
Uses
forcad
Calls
Variables
Type Attributes Name Initial
real(kind=rk) :: Xc(8,3)
type(nurbs_volume) :: shape
real(kind=rk) :: volume
Call graph
compute_volume calls set, cmp_volume
cmp_volume calls ansatz, cmp_elem, reduce
ansatz calls set, cmp_elem, gauss_leg, ndgrid, unique, derivative, det, inv
cmp_elem calls elemconn_cn, unique, get_multiplicity
set1 calls cmp_degree, cmp_nc, set
set2 calls cmp_nc, compute_knot_vector, set
set3 calls cmp_degree, set
set4 calls set
elemconn_cn calls cmp_elemconn_cn_l, cmp_elemconn_cn_s, cmp_elemconn_cn_v
gauss_leg calls gauss_legendre_1d, gauss_legendre_2d, gauss_legendre_3d
ndgrid calls ndgrid2, ndgrid3
unique calls unique_integer, unique_real
cmp_degree calls get_multiplicity, set
cmp_nc calls set, compute_multiplicity
compute_knot_vector calls repelem
get_multiplicity calls compute_multiplicity
inv calls det, inv, eye, solve
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
derivative_scalar calls compute_dtgc, is_rational
derivative_vector calls ndgrid, compute_dtgc, is_rational
gauss_legendre_1d calls gauss_legendre
gauss_legendre_2d calls ndgrid, kron, gauss_legendre
gauss_legendre_3d calls ndgrid, kron, gauss_legendre
compute_dtgc calls compute_dtgc_bspline_3d_scalar, compute_dtgc_bspline_3d_vector, compute_dtgc_nurbs_3d_scalar, compute_dtgc_nurbs_3d_vector
kron calls kron3, kron_t1_t1, kron_t1_t2
compute_dtgc_bspline_3d_scalar calls kron, basis_bspline_der
compute_dtgc_bspline_3d_vector calls kron, basis_bspline_der
compute_dtgc_nurbs_3d_scalar calls kron, basis_bspline_der
compute_dtgc_nurbs_3d_vector calls kron, basis_bspline_der
basis_bspline_der calls basis_bspline_der_a, basis_bspline_der_b