example3_surface – ForCAD
example3_surface Program
BSD 3-Clause
73 statements
Source File
Uses
forcad
This program demonstrates the usage of a NURBS (Non-Uniform Rational B-Spline) surface object to create and finalize a NURBS surface. It sets up control points, weights, and knot vectors for all three dimensions, generates the surface, and exports the control points and the surface to VTK files.
Define control points for the NURBS surface
Define weights for the control points Define knot vectors for both dimensions Set knot vectors, control points, and weights for the NURBS surface object
Deallocate local arrays
Export parameter space to a VTK file
Export the control points to a VTK file
Generate the NURBS surface with resolutions of 30 in both dimensions
Export the generated surface to a VTK file
Export the NURBS surface to an IGES file
Show the control geometry and geometry using PyVista
Print size of the knot vectors Insert knots 0.25, twice and 0.75, once in both directions Print size of the knot vectors after inserting knots Print the degrees
Elevate degree by 2 in both directions Print the degrees after elevating
Print size of the knot vectors Remove knots 0.25, twice and 0.75, once in both directions Print size of the knot vectors after removing knots Generate the refined NURBS surface with resolutions of 30 in both dimensions
Export refined parameter space to a VTK file
Export updated control points to a VTK file
Export the refined generated surface to a VTK file
Export the NURBS surface to an IGES file
Show the control geometry and geometry using PyVista
Rotate the control points
Rotate the generated curve
Translate the control points
Translate the generated curve
Export parameter space to a VTK file
Export the transformed control points to a VTK file
Export the transformed generated volume to a VTK file
Export the transformed NURBS surface to an IGES file
Show the control geometry and geometry using PyVista
Finalize the NURBS surface object
Calls
Variables
Type Attributes Name Initial
real(kind=rk), allocatable :: Wc(:)
Arrays for control points and weights
real(kind=rk), allocatable :: Xc(:,:)
Arrays for control points and weights
real(kind=rk) :: knot1(6)
Arrays for knot vectors in both dimensions
real(kind=rk) :: knot2(6)
Arrays for knot vectors in both dimensions
type(nurbs_surface) :: nurbs
Declare a NURBS surface object
Functions
function generate_Xc(num_rows, num_cols, peak_height) result(control_points)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: num_rows
integer, intent(in) :: num_cols
real(kind=rk), intent(in) :: peak_height
Return Value real(kind=rk), allocatable, (:,:)
Source Code
program example3_surface
    use forcad, only: rk, nurbs_surface
    implicit none
    type(nurbs_surface) :: nurbs            !! Declare a NURBS surface object
    real(rk), allocatable :: Xc(:,:), Wc(:) !! Arrays for control points and weights
    real(rk) :: knot1(6), knot2(6)          !! Arrays for knot vectors in both dimensions
    !-----------------------------------------------------------------------------
    ! Setting up the NURBS surface
    !-----------------------------------------------------------------------------
    !> Define control points for the NURBS surface
    Xc = generate_Xc(3, 3, 1.0_rk)
    !> Define weights for the control points
    allocate(Wc(size(Xc, 1)))
    Wc = 1.0_rk
    Wc(2) = 2.0_rk
    !> Define knot vectors for both dimensions
    knot1 = [0.0_rk, 0.0_rk, 0.0_rk, 1.0_rk, 1.0_rk, 1.0_rk]
    knot2 = [0.0_rk, 0.0_rk, 0.0_rk, 1.0_rk, 1.0_rk, 1.0_rk]
    !> Set knot vectors, control points, and weights for the NURBS surface object
    call nurbs%set(knot1, knot2, Xc, Wc)
    !> Deallocate local arrays
    deallocate(Xc, Wc)
    !> Export parameter space to a VTK file
    call nurbs%export_Xth('vtk/nurbs_surface_Xth.vtk')
    !> Export the control points to a VTK file
    call nurbs%export_Xc('vtk/nurbs_surface_Xc.vtk')
    !-----------------------------------------------------------------------------
    ! Creating the NURBS surface
    !-----------------------------------------------------------------------------
    !> Generate the NURBS surface with resolutions of 30 in both dimensions
    call nurbs%create(30, 30)
    !> Export the generated surface to a VTK file
    call nurbs%export_Xg('vtk/nurbs_surface_Xg.vtk')
    !> Export the NURBS surface to an IGES file
    call nurbs%export_iges('iges/nurbs_surface.iges')
    !-----------------------------------------------------------------------------
    ! Visualization using PyVista
    ! Note: PyVista is required for visualization. Install it using `pip install pyvista`
    !-----------------------------------------------------------------------------
    !> Show the control geometry and geometry using PyVista
    call nurbs%show('vtk/nurbs_surface_Xc.vtk','vtk/nurbs_surface_Xg.vtk')
    !-----------------------------------------------------------------------------
    ! Refinements
    !-----------------------------------------------------------------------------
    !> Print size of the knot vectors
    print*, size(nurbs%get_knot(1))
    print*, size(nurbs%get_knot(2))
    !> Insert knots 0.25, twice and 0.75, once in both directions
    call nurbs%insert_knots(1, [0.25_rk, 0.75_rk], [2,1]) ! direction 1
    call nurbs%insert_knots(2, [0.25_rk, 0.75_rk], [2,1]) ! direction 2
    !> Print size of the knot vectors after inserting knots
    print*, size(nurbs%get_knot(1))
    print*, size(nurbs%get_knot(2))
    !> Print the degrees
    print*, nurbs%get_degree()
    !> Elevate degree by 2 in both directions
    call nurbs%elevate_degree(1, 2) ! direction 1
    call nurbs%elevate_degree(2, 2) ! direction 2
    !> Print the degrees after elevating
    print*, nurbs%get_degree()
    !> Print size of the knot vectors
    print*, size(nurbs%get_knot(1))
    print*, size(nurbs%get_knot(2))
    !> Remove knots 0.25, twice and 0.75, once in both directions
    call nurbs%remove_knots(1, [0.25_rk, 0.75_rk], [2,1]) ! direction 1
    call nurbs%remove_knots(2, [0.25_rk, 0.75_rk], [2,1]) ! direction 2
    !> Print size of the knot vectors after removing knots
    print*, size(nurbs%get_knot(1))
    print*, size(nurbs%get_knot(2))
    !> Generate the refined NURBS surface with resolutions of 30 in both dimensions
    call nurbs%create()
    !> Export refined parameter space to a VTK file
    call nurbs%export_Xth('vtk/nurbs_surface_Xth2.vtk')
    !> Export updated control points to a VTK file
    call nurbs%export_Xc('vtk/nurbs_surface_Xc2.vtk')
    !> Export the refined generated surface to a VTK file
    call nurbs%export_Xg('vtk/nurbs_surface_Xg2.vtk')
    !> Export the NURBS surface to an IGES file
    call nurbs%export_iges('iges/nurbs_surface2.iges')
    !-----------------------------------------------------------------------------
    ! Visualization using PyVista
    ! Note: PyVista is required for visualization. Install it using `pip install pyvista`
    !-----------------------------------------------------------------------------
    !> Show the control geometry and geometry using PyVista
    call nurbs%show('vtk/nurbs_surface_Xc2.vtk','vtk/nurbs_surface_Xg2.vtk')
    !-----------------------------------------------------------------------------
    ! Transformations
    !-----------------------------------------------------------------------------
    !> Rotate the control points
    call nurbs%rotate_Xc(alpha=45.0_rk, beta=0.0_rk, theta=90.0_rk)
    !> Rotate the generated curve
    call nurbs%rotate_Xg(alpha=-45.0_rk, beta=0.0_rk, theta=-90.0_rk)
    !> Translate the control points
    call nurbs%translate_Xc([1.0_rk, 2.0_rk, -3.0_rk])
    !> Translate the generated curve
    call nurbs%translate_Xg([-1.0_rk, -2.0_rk, 3.0_rk])
    !> Export parameter space to a VTK file
    call nurbs%export_Xth('vtk/nurbs_surface_Xth3.vtk')
    !> Export the transformed control points to a VTK file
    call nurbs%export_Xc('vtk/nurbs_surface_Xc3.vtk')
    !> Export the transformed generated volume to a VTK file
    call nurbs%export_Xg('vtk/nurbs_surface_Xg3.vtk')
    !> Export the transformed NURBS surface to an IGES file
    call nurbs%export_iges('iges/nurbs_surface3.iges')
    !-----------------------------------------------------------------------------
    ! Visualization using PyVista
    ! Note: PyVista is required for visualization. Install it using `pip install pyvista`
    !-----------------------------------------------------------------------------
    !> Show the control geometry and geometry using PyVista
    call nurbs%show('vtk/nurbs_surface_Xc3.vtk','vtk/nurbs_surface_Xg3.vtk')
    !-----------------------------------------------------------------------------
    ! Finalizing
    !-----------------------------------------------------------------------------
    !> Finalize the NURBS surface object
    call nurbs%finalize()
contains
    !-----------------------------------------------------------------------------
    function generate_Xc(num_rows, num_cols, peak_height) result(control_points)
        integer, intent(in) :: num_rows, num_cols
        real(rk), intent(in) :: peak_height
        real(rk), allocatable :: control_points(:,:)
        integer :: i, j
        real(rk) :: x_spacing, y_spacing, x_offset, y_offset
        x_spacing = 1.0_rk / real(num_cols - 1, rk)
        y_spacing = 1.0_rk / real(num_rows - 1, rk)
        x_offset = -0.5_rk
        y_offset = -0.5_rk
        allocate(control_points(num_rows * num_cols, 3))
        do i = 1, num_rows
            do j = 1, num_cols
                control_points((i - 1) * num_cols + j, 1) = x_offset + real(j - 1, rk) * x_spacing
                control_points((i - 1) * num_cols + j, 2) = y_offset + real(i - 1, rk) * y_spacing
                control_points((i - 1) * num_cols + j, 3) = &
                    peak_height * exp(-((control_points((i - 1) * num_cols + j, 1) ** 2) &
                    + (control_points((i - 1) * num_cols + j, 2) ** 2))) + 0.5_rk * peak_height * 0.2_rk
            end do
        end do
    end function
    !-----------------------------------------------------------------------------
end program example3_surface
Call graph
example3_surface calls get_degree, get_knot, set, create, elevate_degree, export_iges, export_xc, export_xg, export_xth, finalize, generate_xc, insert_knots, remove_knots, rotate_xc, rotate_xg, show, translate_xc, translate_xg
create calls compute_xg, ndgrid, is_rational, set
elevate_degree calls get_knot, set, elevate_degree_a_5_9, is_rational
export_iges calls append, delete, init, makedpsections, makegsection, makessection, is_rational, writeigesfile
export_xc calls cmp_elem_xc_vis, export_vtk_legacy, set
export_xg calls cmp_elem_xg_vis, export_vtk_legacy, set
export_xth calls ndgrid, unique, cmp_elem_xth, export_vtk_legacy
insert_knots calls get_knot, compute_multiplicity, findspan, insert_knot_a_5_1, is_rational, s_loc, set
remove_knots calls get_knot, set, compute_multiplicity, findspan, is_rational, remove_knots_a_5_8
rotate_xc calls rotation
rotate_xg calls rotation
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
compute_xg calls compute_xg_bspline_2d, compute_xg_bspline_2d_1point, compute_xg_nurbs_2d, compute_xg_nurbs_2d_1point
ndgrid calls ndgrid2, ndgrid3
unique calls unique_integer, unique_real
cmp_elem_xc_vis calls elemconn_c0
cmp_elem_xg_vis calls elemconn_c0
cmp_elem_xth calls unique, elemconn_c0
elevate_degree_a_5_9 calls compute_multiplicity, bincoeff
rotation calls cosd, sind
set1 calls set, cmp_degree, cmp_nc
set2 calls set, cmp_nc, compute_knot_vector
set3 calls set, cmp_degree
set4 calls set
elemconn_c0 calls cmp_elemconn_c0_l, cmp_elemconn_c0_s, cmp_elemconn_c0_v
bincoeff calls factln
cmp_degree calls set, get_multiplicity
cmp_nc calls compute_multiplicity, set
compute_knot_vector calls repelem
compute_xg_bspline_2d calls kron, basis_bspline
compute_xg_bspline_2d_1point calls kron, basis_bspline
compute_xg_nurbs_2d calls cmp_tgc_2d
compute_xg_nurbs_2d_1point calls kron, basis_bspline
kron calls kron3, kron_t1_t1, kron_t1_t2
cmp_tgc_2d calls kron, basis_bspline
get_multiplicity calls compute_multiplicity