example_put_to_nurbs – ForCAD
example_put_to_nurbs Program
BSD 3-Clause
28 statements
Source File
Uses
forcad
forcad_utils
You can create your shape or use a predefined one Read coordinates from file Read element connectivities from file Set a control shape that will be used to put the shape into The contol shape is a hexahedron with 100x40x10 with 10x5x3 number of control points By modifying the control shape you can modify the shape
Map the shape into the shape
Deallocate local variables
Export the shape and the control shape to vtk files Show the control geometry and geometry using PyVista
Finalize the control shape
Calls
Variables
Type Attributes Name Initial
real(kind=rk), allocatable :: X(:,:)
type(nurbs_volume) :: control_shape
integer, allocatable :: elem(:,:)
integer :: i
integer :: nunit
Call graph
example_put_to_nurbs calls set, export_xc, export_xg, finalize, hexahedron_xc, put_to_nurbs, show
export_xc calls cmp_elem_xc_vis, export_vtk_legacy, set
export_xg calls cmp_elem_xg_vis, export_vtk_legacy, set
put_to_nurbs calls compute_xg, is_rational, set_elem_xg_vis
compute_xg calls compute_xg_bspline_3d, compute_xg_bspline_3d_1point, compute_xg_nurbs_3d, compute_xg_nurbs_3d_1point
cmp_elem_xc_vis calls elemconn_c0
cmp_elem_xg_vis calls elemconn_c0
set1 calls set, cmp_degree, cmp_nc
set2 calls set, cmp_nc, compute_knot_vector
set3 calls set, cmp_degree
set4 calls set
elemconn_c0 calls cmp_elemconn_c0_l, cmp_elemconn_c0_s, cmp_elemconn_c0_v
cmp_degree calls set, get_multiplicity
cmp_nc calls set, compute_multiplicity
compute_knot_vector calls repelem
compute_xg_bspline_3d calls kron, basis_bspline
compute_xg_bspline_3d_1point calls kron, basis_bspline
compute_xg_nurbs_3d calls cmp_tgc_3d
compute_xg_nurbs_3d_1point calls kron, basis_bspline
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
kron calls kron3, kron_t1_t1, kron_t1_t2
cmp_tgc_3d calls kron, basis_bspline
get_multiplicity calls compute_multiplicity