example_twist_taper – ForCAD
example_twist_taper Program
BSD 3-Clause
55 statements
Source File
Uses
forcad
Example program demonstrating how to apply a progressive twist and linear taper to a hexahedral NURBS volume along its axial (z) direction.
The program: Creates a straight hexahedral block (control points nc = [7,7,9] over a box of size L), Copies it to shape, Applies a z-dependent twist up to twist_deg and a linear taper to factor taper, Exports the resulting NURBS volume to VTK, Displays the geometry.
Calls
Variables
Type Attributes Name Initial
real(kind=rk), parameter :: L(3) = [1.0_rk, 1.0_rk, 3.0_rk]
Domain extents in .
type(nurbs_volume) :: hexa
integer, parameter :: nc(3) = [7, 7, 9]
Control point counts per direction.
type(nurbs_volume) :: shape
real(kind=rk), parameter :: taper = 0.1_rk
Target in-plane scale at the top face (0<taper1).
real(kind=rk), parameter :: twist_deg = 360.0_rk
Total twist angle (degrees) at the top face.
Subroutines
pure subroutine build_twist_taper(this, Length, nc, twist_deg, taper)
Apply a z-progressive twist and linear taper to a NURBS hexahedron.
Read more…
Arguments
Type Intent Optional Attributes Name
type(nurbs_volume), intent(inout) :: this
Volume to be transformed.
real(kind=rk), intent(in) :: Length(3)
Box lengths .
integer, intent(in) :: nc(3)
Control points sizes.
real(kind=rk), intent(in) :: twist_deg
Total twist at top face (degrees).
real(kind=rk), intent(in) :: taper
In-plane scale at top face (0<taper1).
Call graph
example_twist_taper calls build_twist_taper, create, export_xc, export_xg, export_xth_in_xg, set_hexahedron, show
build_twist_taper calls get_knot, get_wc, get_xc, set, is_rational
create calls compute_xg, ndgrid, is_rational, set
export_xc calls cmp_elem_xc_vis, export_vtk_legacy, set
export_xg calls cmp_elem_xg_vis, export_vtk_legacy, set
export_xth_in_xg calls compute_xg, unique, export_vtk_legacy, is_rational, set
set_hexahedron calls set, hexahedron_xc
compute_xg calls compute_xg_bspline_3d, compute_xg_bspline_3d_1point, compute_xg_nurbs_3d, compute_xg_nurbs_3d_1point
ndgrid calls ndgrid2, ndgrid3
unique calls unique_integer, unique_real
cmp_elem_xc_vis calls elemconn_c0
cmp_elem_xg_vis calls elemconn_c0
elemconn_c0 calls cmp_elemconn_c0_l, cmp_elemconn_c0_s, cmp_elemconn_c0_v
compute_xg_bspline_3d calls kron, basis_bspline
compute_xg_bspline_3d_1point calls kron, basis_bspline
compute_xg_nurbs_3d calls cmp_tgc_3d
compute_xg_nurbs_3d_1point calls kron, basis_bspline
set1 calls set, cmp_degree, cmp_nc
set2 calls set, cmp_nc, compute_knot_vector
set3 calls set, cmp_degree
set4 calls set
kron calls kron3, kron_t1_t1, kron_t1_t2
cmp_degree calls set, get_multiplicity
cmp_nc calls set, compute_multiplicity
cmp_tgc_3d calls kron, basis_bspline
compute_knot_vector calls repelem
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
get_multiplicity calls compute_multiplicity