example_bend_pipe – ForCAD
example_bend_pipe Program
BSD 3-Clause
77 statements
Source File
Uses
forcad
Example program demonstrating how to bend a straight pipe-like NURBS volume into a circular arc.
The program: Creates a straight pipe segment (as a ring extruded in), Refines the shape, Applies bending with different bend angles (90°, 270°, 360°), Exports the resulting NURBS volumes to VTK, Displays the geometry.
Calls
Variables
Type Attributes Name Initial
real(kind=rk), parameter :: a(3) = [90.0_rk, 270.0_rk, 360.0_rk]
Bend angles (degrees).
real(kind=rk), parameter :: c(3) = [0.0_rk, 0.0_rk, 0.0_rk]
Center of the ring.
real(kind=rk), parameter :: l = 1.0_rk
Length of the straight segment.
real(kind=rk), parameter :: r1 = 0.3_rk
Inner radius of the pipe.
real(kind=rk), parameter :: r2 = 0.5_rk
Outer radius of the pipe.
real(kind=rk), parameter :: rb = 1.5_rk
Bend radius.
type(nurbs_volume) :: ring
Straight pipe ring
type(nurbs_volume) :: shape
Bent pipe shape
Subroutines
pure subroutine bend_pipe(this, center, length, rbend, angle_deg)
Bend a straight pipe-like NURBS volume into a circular arc. Each control point is transformed relative to the center . Let the total bend angle in degrees be (input), and define the total bend angle in radians For each control point: Mapping: Knots and weights are preserved; only the control lattice is updated.
Arguments
Type Intent Optional Attributes Name
type(nurbs_volume), intent(inout) :: this
NURBS volume to be bent.
real(kind=rk), intent(in) :: center(3)
Pipe center coordinates .
real(kind=rk), intent(in) :: length
Length of the straight pipe segment before bending.
real(kind=rk), intent(in) :: rbend
Bend radius , i.e. distance from the bend centerline.
real(kind=rk), intent(in) :: angle_deg
Bend angle in degrees .
Call graph
example_bend_pipe calls bend_pipe, create, elevate_degree, export_xc, export_xg, export_xth_in_xg, insert_knots, set_ring, show
bend_pipe calls get_knot, get_nc, get_wc, get_xc, set, is_rational
create calls compute_xg, ndgrid, is_rational, set
elevate_degree calls get_knot, set, elevate_degree_a_5_9, is_rational
export_xc calls cmp_elem_xc_vis, export_vtk_legacy, set
export_xg calls cmp_elem_xg_vis, export_vtk_legacy, set
export_xth_in_xg calls compute_xg, unique, export_vtk_legacy, is_rational, set
insert_knots calls compute_multiplicity, get_knot, findspan, insert_knot_a_5_1, is_rational, s_loc, set
set_ring calls set
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
compute_xg calls compute_xg_bspline_3d, compute_xg_bspline_3d_1point, compute_xg_nurbs_3d, compute_xg_nurbs_3d_1point
ndgrid calls ndgrid2, ndgrid3
unique calls unique_integer, unique_real
cmp_elem_xc_vis calls elemconn_c0
cmp_elem_xg_vis calls elemconn_c0
elevate_degree_a_5_9 calls compute_multiplicity, bincoeff
elemconn_c0 calls cmp_elemconn_c0_l, cmp_elemconn_c0_s, cmp_elemconn_c0_v
bincoeff calls factln
compute_xg_bspline_3d calls kron, basis_bspline
compute_xg_bspline_3d_1point calls kron, basis_bspline
compute_xg_nurbs_3d calls cmp_tgc_3d
compute_xg_nurbs_3d_1point calls kron, basis_bspline
get_nc_dir calls compute_multiplicity
set1 calls set, cmp_degree, cmp_nc
set2 calls set, cmp_nc, compute_knot_vector
set3 calls set, cmp_degree
set4 calls set
kron calls kron3, kron_t1_t1, kron_t1_t2
cmp_degree calls set, get_multiplicity
cmp_nc calls compute_multiplicity, set
cmp_tgc_3d calls kron, basis_bspline
compute_knot_vector calls repelem
get_multiplicity calls compute_multiplicity