example_plate_hole_2_3d – ForCAD
example_plate_hole_2_3d Program
BSD 3-Clause
105 statements
Source File
Uses
forcad
Calls
Variables
Type Attributes Name Initial
real(kind=rk), allocatable :: Wc(:)
real(kind=rk), allocatable :: Xc(:,:)
real(kind=rk), parameter :: height = 5.0_rk
real(kind=rk), parameter :: length = 5.0_rk
type(nurbs_volume) :: plate_hole
real(kind=rk), parameter :: radius1 = 2.5_rk
real(kind=rk), parameter :: radius2 = 3.5_rk
real(kind=rk), parameter :: width = 0.5_rk
Subroutines
pure subroutine set_Xc_Wc(type, params, X_c, W_c)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: type
real(kind=rk), intent(in), contiguous :: params(:)
real(kind=rk), intent(out), allocatable :: X_c(:,:)
real(kind=rk), intent(out), allocatable :: W_c(:)
Call graph
example_plate_hole_2_3d calls set, create, export_xc, export_xg, export_xth_in_xg, set_xc_wc, show
create calls compute_xg, ndgrid, is_rational, set
export_xc calls cmp_elem_xc_vis, export_vtk_legacy, set
export_xg calls cmp_elem_xg_vis, export_vtk_legacy, set
export_xth_in_xg calls compute_xg, unique, export_vtk_legacy, is_rational, set
set_xc_wc calls cosd, tand
compute_xg calls compute_xg_bspline_3d, compute_xg_bspline_3d_1point, compute_xg_nurbs_3d, compute_xg_nurbs_3d_1point
ndgrid calls ndgrid2, ndgrid3
unique calls unique_integer, unique_real
cmp_elem_xc_vis calls elemconn_c0
cmp_elem_xg_vis calls elemconn_c0
set1 calls set, cmp_degree, cmp_nc
set2 calls set, cmp_nc, compute_knot_vector
set3 calls set, cmp_degree
set4 calls set
elemconn_c0 calls cmp_elemconn_c0_l, cmp_elemconn_c0_s, cmp_elemconn_c0_v
cmp_degree calls set, get_multiplicity
cmp_nc calls set, compute_multiplicity
compute_knot_vector calls repelem
compute_xg_bspline_3d calls kron, basis_bspline
compute_xg_bspline_3d_1point calls kron, basis_bspline
compute_xg_nurbs_3d calls cmp_tgc_3d
compute_xg_nurbs_3d_1point calls kron, basis_bspline
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
kron calls kron3, kron_t1_t1, kron_t1_t2
cmp_tgc_3d calls kron, basis_bspline
get_multiplicity calls compute_multiplicity