example_nurbs_volume – ForCAD
example_nurbs_volume Program
BSD 3-Clause
39 statements
Source File
Uses
forcad
This program demonstrates the usage of a NURBS volume object to create, and finalize a NURBS volume. It sets up control points and weights, generates the volume, and exports the control points and the volume to VTK files at various stages.
Define control points for the NURBS volume
Define weights for the control points
Set control points and weights for the NURBS volume object
Deallocate local arrays
Elevate the degree of the NURBS volume in the first, second and third directions Insert knots into the NURBS volume in the first, second and third directions Export initial control points to a VTK file
Generate the NURBS volume with a resolution of 15X15X15
Export the generated volume to a VTK file
Export the parameter space to a VTK file
Show the control geometry, geometry and parameters using PyVista
Finalize the NURBS volume object
Calls
Variables
Type Attributes Name Initial
real(kind=rk), allocatable :: Wc(:)
Arrays for control points and weights
real(kind=rk), allocatable :: Xc(:,:)
Arrays for control points and weights
type(nurbs_volume) :: nurbs
Declare a NURBS volume object
Functions
pure function generate_Xc(L) result(control_points)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: L
Return Value real(kind=rk), allocatable, (:,:)
Source Code
program example_nurbs_volume
    use forcad, only: rk, nurbs_volume
    implicit none
    type(nurbs_volume) :: nurbs              !! Declare a NURBS volume object
    real(rk), allocatable :: Xc(:,:), Wc(:)  !! Arrays for control points and weights
    !-----------------------------------------------------------------------------
    ! Setting up the NURBS volume
    !-----------------------------------------------------------------------------
    !> Define control points for the NURBS volume
    Xc = generate_Xc(1.0_rk)
    !> Define weights for the control points
    allocate(Wc(size(Xc, 1)), source=1.0_rk)
    !> Set control points and weights for the NURBS volume object
    call nurbs%set([2,2,2], Xc, Wc)
    !> Deallocate local arrays
    deallocate(Xc, Wc)
    !-----------------------------------------------------------------------------
    ! Refinement
    !-----------------------------------------------------------------------------
    !> Elevate the degree of the NURBS volume in the first, second and third directions
    call nurbs%elevate_degree(1,2)
    call nurbs%elevate_degree(2,2)
    call nurbs%elevate_degree(3,2)
    !> Insert knots into the NURBS volume in the first, second and third directions
    call nurbs%insert_knots(1,[0.5_rk], [1])
    call nurbs%insert_knots(2,[0.5_rk], [1])
    call nurbs%insert_knots(3,[0.5_rk], [1])
    !> Export initial control points to a VTK file
    call nurbs%export_Xc('vtk/demo_volume_Xc.vtk')
    !-----------------------------------------------------------------------------
    ! Creating the NURBS volume
    !-----------------------------------------------------------------------------
    !> Generate the NURBS volume with a resolution of 15X15X15
    call nurbs%create(15, 15, 15)
    !> Export the generated volume to a VTK file
    call nurbs%export_Xg('vtk/demo_volume_Xg.vtk')
    !> Export the parameter space to a VTK file
    call nurbs%export_Xth_in_Xg('vtk/demo_volume_Xth_in_Xg.vtk')
    !-----------------------------------------------------------------------------
    ! Visualization using PyVista
    ! Note: PyVista is required for visualization. Install it using `pip install pyvista`
    !-----------------------------------------------------------------------------
    !> Show the control geometry, geometry and parameters using PyVista
    call nurbs%show('vtk/demo_volume_Xc.vtk', 'vtk/demo_volume_Xg.vtk', 'vtk/demo_volume_Xth_in_Xg.vtk')
    !-----------------------------------------------------------------------------
    ! Finalizing
    !-----------------------------------------------------------------------------
    !> Finalize the NURBS volume object
    call nurbs%finalize()
contains
    !-----------------------------------------------------------------------------
    pure function generate_Xc(L) result(control_points)
        implicit none
        real(rk), intent(in) :: L
        real(rk), allocatable :: control_points(:,:)
        real(rk) :: L2
        L2 = L / 2.0_rk
        allocate(control_points(8, 3))
        control_points(1,:) = [ L2, -L2,  L2]
        control_points(2,:) = [ L2, -L2, -L2]
        control_points(3,:) = [-L2, -L2,  L2]
        control_points(4,:) = [-L2, -L2, -L2]
        control_points(5,:) = [ L2,  L2,  L2]
        control_points(6,:) = [ L2,  L2, -L2]
        control_points(7,:) = [-L2,  L2,  L2]
        control_points(8,:) = [-L2,  L2, -L2]
    end function
    !-----------------------------------------------------------------------------
end program example_nurbs_volume
Call graph
example_nurbs_volume calls set, create, elevate_degree, export_xc, export_xg, export_xth_in_xg, finalize, generate_xc, insert_knots, show
create calls compute_xg, ndgrid, is_rational, set
elevate_degree calls set, get_knot, elevate_degree_a_5_9, is_rational
export_xc calls cmp_elem_xc_vis, export_vtk_legacy, set
export_xg calls cmp_elem_xg_vis, export_vtk_legacy, set
export_xth_in_xg calls compute_xg, unique, export_vtk_legacy, is_rational, set
insert_knots calls compute_multiplicity, get_knot, findspan, insert_knot_a_5_1, is_rational, s_loc, set
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
compute_xg calls compute_xg_bspline_3d, compute_xg_bspline_3d_1point, compute_xg_nurbs_3d, compute_xg_nurbs_3d_1point
ndgrid calls ndgrid2, ndgrid3
unique calls unique_integer, unique_real
cmp_elem_xc_vis calls elemconn_c0
cmp_elem_xg_vis calls elemconn_c0
elevate_degree_a_5_9 calls compute_multiplicity, bincoeff
set1 calls set, cmp_degree, cmp_nc
set2 calls set, cmp_nc, compute_knot_vector
set3 calls set, cmp_degree
set4 calls set
elemconn_c0 calls cmp_elemconn_c0_l, cmp_elemconn_c0_s, cmp_elemconn_c0_v
bincoeff calls factln
cmp_degree calls set, get_multiplicity
cmp_nc calls compute_multiplicity, set
compute_knot_vector calls repelem
compute_xg_bspline_3d calls kron, basis_bspline
compute_xg_bspline_3d_1point calls kron, basis_bspline
compute_xg_nurbs_3d calls cmp_tgc_3d
compute_xg_nurbs_3d_1point calls kron, basis_bspline
kron calls kron3, kron_t1_t1, kron_t1_t2
cmp_tgc_3d calls kron, basis_bspline
get_multiplicity calls compute_multiplicity