example_toroidal_pipe – ForCAD
example_toroidal_pipe Program
BSD 3-Clause
68 statements
Source File
Uses
forcad
Example program demonstrating how to sweep a straight, pipe-like NURBS volume onto a toroidal pipe (donut) with an optional progressive cross-section twist and a sinusoidal wobble in the global z-direction as it travels around the torus.
The program: Creates a straight pipe segment (ring extruded along), Refines it along the axial direction (knot insertion + degree elevation), Maps the control points onto a torus of major radius R, Applies a cross-section twist of twist_turns full rotations over one loop, Superimposes a vertical wobble , Exports the resulting NURBS volume to VTK and displays it, Prints the approximate enclosed volume (Gaussian integration).
Calls
Variables
Type Attributes Name Initial
real(kind=rk), parameter :: Az = 0.1_rk
amplitude of vertical wobble
integer, parameter :: Nref = 30
real(kind=rk), parameter :: R = 1.00_rk
major radius
real(kind=rk), parameter :: center(3) = [0.0_rk, 0.0_rk, 0.0_rk]
center of the ring
integer :: i
real(kind=rk), parameter :: length = 1.0_rk
length of the pipe
integer, parameter :: nwaves_z = 6
number of sine waves per full loop
real(kind=rk), parameter :: phase_z = 0.1_rk
phase shift (radians)
real(kind=rk), parameter :: r1 = 0.12_rk
inner radius
real(kind=rk), parameter :: r2 = 0.20_rk
outer radius
type(nurbs_volume) :: ring
straight pipe segment
type(nurbs_volume) :: sh
toroidal pipe shape
real(kind=rk), parameter :: twist_turns = 1.0_rk
cross-section twist (turns over full loop)
Subroutines
pure subroutine map_to_torus_sineZ(this, c, R, twist_turns, Az, nwaves_z, phase_z)
Map a straight pipe (ring extruded in) onto a toroidal pipe with: cross-section twist: , vertical wobble: .
Read more…
Arguments
Type Intent Optional Attributes Name
type(nurbs_volume), intent(inout) :: this
real(kind=rk), intent(in) :: c(3)
real(kind=rk), intent(in) :: R
real(kind=rk), intent(in) :: twist_turns
real(kind=rk), intent(in) :: Az
integer, intent(in) :: nwaves_z
real(kind=rk), intent(in) :: phase_z
Call graph
example_toroidal_pipe calls create, elevate_degree, export_xc, export_xg, export_xth_in_xg, insert_knots, map_to_torus_sinez, set_ring, show
create calls compute_xg, ndgrid, is_rational, set
elevate_degree calls get_knot, set, elevate_degree_a_5_9, is_rational
export_xc calls cmp_elem_xc_vis, export_vtk_legacy, set
export_xg calls cmp_elem_xg_vis, export_vtk_legacy, set
export_xth_in_xg calls compute_xg, unique, export_vtk_legacy, is_rational, set
insert_knots calls compute_multiplicity, get_knot, findspan, insert_knot_a_5_1, is_rational, s_loc, set
map_to_torus_sinez calls get_knot, get_nc, get_wc, get_xc, set, is_rational
set_ring calls set
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
compute_xg calls compute_xg_bspline_3d, compute_xg_bspline_3d_1point, compute_xg_nurbs_3d, compute_xg_nurbs_3d_1point
ndgrid calls ndgrid2, ndgrid3
unique calls unique_integer, unique_real
cmp_elem_xc_vis calls elemconn_c0
cmp_elem_xg_vis calls elemconn_c0
elevate_degree_a_5_9 calls compute_multiplicity, bincoeff
elemconn_c0 calls cmp_elemconn_c0_l, cmp_elemconn_c0_s, cmp_elemconn_c0_v
bincoeff calls factln
compute_xg_bspline_3d calls kron, basis_bspline
compute_xg_bspline_3d_1point calls kron, basis_bspline
compute_xg_nurbs_3d calls cmp_tgc_3d
compute_xg_nurbs_3d_1point calls kron, basis_bspline
get_nc_dir calls compute_multiplicity
set1 calls set, cmp_degree, cmp_nc
set2 calls set, cmp_nc, compute_knot_vector
set3 calls set, cmp_degree
set4 calls set
kron calls kron3, kron_t1_t1, kron_t1_t2
cmp_degree calls set, get_multiplicity
cmp_nc calls compute_multiplicity, set
cmp_tgc_3d calls kron, basis_bspline
compute_knot_vector calls repelem
get_multiplicity calls compute_multiplicity