example_helix_pipe – ForCAD
example_helix_pipe Program
BSD 3-Clause
63 statements
Source File
Uses
forcad
Example program demonstrating how to sweep a straight, pipe-like NURBS volume into a cylindrical helix with a prescribed radius, pitch, and number of turns.
The program: Creates a straight ring extruded along (a pipe segment), Refines it along the axial direction (knot insertion + degree elevation), Maps the control points onto a helix of radius rh, pitch pitch, with nturns turns, Exports the resulting NURBS volume to VTK, Displays the geometry.
Calls
Variables
Type Attributes Name Initial
integer, parameter :: N = 50
interior knots to insert along .
real(kind=rk), parameter :: center(3) = [0.0_rk, 0.0_rk, 0.0_rk]
Pipe center .
integer :: i
real(kind=rk), parameter :: length = 1.0_rk
Length of the straight segment.
integer, parameter :: nturns = 3
Number of full turns.
real(kind=rk), parameter :: pitch = 1.5_rk
Helix pitch (axial rise per full turn).
real(kind=rk), parameter :: r1 = 0.1_rk
Inner radius of the pipe.
real(kind=rk), parameter :: r2 = 0.2_rk
Outer radius of the pipe.
real(kind=rk), parameter :: rh = 1.0_rk
Helix radius.
type(nurbs_volume) :: ring
Straight pipe ring.
type(nurbs_volume) :: shape
Helical pipe shape.
Subroutines
pure subroutine build_helix(this, c, rh, p, n)
Map a straight pipe-like NURBS volume onto a cylindrical helix.
Read more…
Arguments
Type Intent Optional Attributes Name
type(nurbs_volume), intent(inout) :: this
NURBS volume to be helicalized.
real(kind=rk), intent(in) :: c(3)
Center , helix radius , pitch .
real(kind=rk), intent(in) :: rh
Center , helix radius , pitch .
real(kind=rk), intent(in) :: p
Center , helix radius , pitch .
integer, intent(in) :: n
Number of turns.
Call graph
example_helix_pipe calls build_helix, create, elevate_degree, export_xc, export_xg, export_xth_in_xg, insert_knots, set_ring, show
build_helix calls get_knot, get_nc, get_wc, get_xc, set, is_rational
create calls compute_xg, ndgrid, is_rational, set
elevate_degree calls get_knot, set, elevate_degree_a_5_9, is_rational
export_xc calls cmp_elem_xc_vis, export_vtk_legacy, set
export_xg calls cmp_elem_xg_vis, export_vtk_legacy, set
export_xth_in_xg calls compute_xg, unique, export_vtk_legacy, is_rational, set
insert_knots calls compute_multiplicity, get_knot, findspan, insert_knot_a_5_1, is_rational, s_loc, set
set_ring calls set
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
compute_xg calls compute_xg_bspline_3d, compute_xg_bspline_3d_1point, compute_xg_nurbs_3d, compute_xg_nurbs_3d_1point
ndgrid calls ndgrid2, ndgrid3
unique calls unique_integer, unique_real
cmp_elem_xc_vis calls elemconn_c0
cmp_elem_xg_vis calls elemconn_c0
elevate_degree_a_5_9 calls compute_multiplicity, bincoeff
elemconn_c0 calls cmp_elemconn_c0_l, cmp_elemconn_c0_s, cmp_elemconn_c0_v
bincoeff calls factln
compute_xg_bspline_3d calls kron, basis_bspline
compute_xg_bspline_3d_1point calls kron, basis_bspline
compute_xg_nurbs_3d calls cmp_tgc_3d
compute_xg_nurbs_3d_1point calls kron, basis_bspline
get_nc_dir calls compute_multiplicity
set1 calls set, cmp_degree, cmp_nc
set2 calls set, cmp_nc, compute_knot_vector
set3 calls set, cmp_degree
set4 calls set
kron calls kron3, kron_t1_t1, kron_t1_t2
cmp_degree calls set, get_multiplicity
cmp_nc calls compute_multiplicity, set
cmp_tgc_3d calls kron, basis_bspline
compute_knot_vector calls repelem
get_multiplicity calls compute_multiplicity