example_nurbs_surface – ForCAD
example_nurbs_surface Program
BSD 3-Clause
42 statements
Source File
Uses
forcad
This program demonstrates the usage of a NURBS (Non-Uniform Rational B-Spline) surface object to create and finalize a NURBS surface. It sets up control points, weights, and knot vectors for all three dimensions, generates the surface, and exports the control points and the surface to VTK files.
Define control points for the NURBS surface
Define weights for the control points Define knot vectors for both dimensions Set knot vectors, control points, and weights for the NURBS surface object
Export the control points to a VTK file
Generate the NURBS surface with resolutions of 30 in both dimensions
Export the generated surface to a VTK file
Finalize the NURBS surface object
Calls
Variables
Type Attributes Name Initial
real(kind=rk), allocatable :: Wc(:)
Arrays for control points and weights
real(kind=rk), allocatable :: Xc(:,:)
Arrays for control points and weights
real(kind=rk) :: knot1(6)
Arrays for knot vectors in both dimensions
real(kind=rk) :: knot2(6)
Arrays for knot vectors in both dimensions
type(nurbs_surface) :: nurbs
Declare a NURBS surface object
Functions
function generate_Xc(num_rows, num_cols, peak_height) result(control_points)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: num_rows
integer, intent(in) :: num_cols
real(kind=rk), intent(in) :: peak_height
Return Value real(kind=rk), dimension(:,:), allocatable
Source Code
program example_nurbs_surface
    use forcad
    implicit none
    type(nurbs_surface) :: nurbs            !! Declare a NURBS surface object
    real(rk), allocatable :: Xc(:,:), Wc(:) !! Arrays for control points and weights
    real(rk) :: knot1(6), knot2(6)          !! Arrays for knot vectors in both dimensions
    !-----------------------------------------------------------------------------
    ! Setting up the NURBS surface
    !-----------------------------------------------------------------------------
    !> Define control points for the NURBS surface
    Xc = generate_Xc(3, 3, 1.0_rk)
    !> Define weights for the control points
    allocate(Wc(size(Xc, 1)))
    Wc = 1.0_rk
    Wc(2) = 5.0_rk
    !> Define knot vectors for both dimensions
    knot1 = [0.0_rk, 0.0_rk, 0.0_rk, 1.0_rk, 1.0_rk, 1.0_rk]
    knot2 = [0.0_rk, 0.0_rk, 0.0_rk, 1.0_rk, 1.0_rk, 1.0_rk]
    !> Set knot vectors, control points, and weights for the NURBS surface object
    call nurbs%set(knot1, knot2, Xc, Wc)
    !> Export the control points to a VTK file
    call nurbs%export_Xc('vtk/nurbs_surface_Xc.vtk')
    !-----------------------------------------------------------------------------
    ! Creating the NURBS surface
    !-----------------------------------------------------------------------------
    !> Generate the NURBS surface with resolutions of 30 in both dimensions
    call nurbs%create(30, 30)
    !> Export the generated surface to a VTK file
    call nurbs%export_Xg('vtk/nurbs_surface_Xg.vtk')
    !-----------------------------------------------------------------------------
    ! Refinements
    !-----------------------------------------------------------------------------
    ! Insert knots 0.25, twice and 0.75, once
    call nurbs%insert_knots(1, [0.25_rk, 0.75_rk], [2,1]) ! direction 1
    call nurbs%insert_knots(2, [0.25_rk, 0.75_rk], [2,1]) ! direction 2
    ! Export updated control points to a VTK file
    call nurbs%export_Xc('vtk/nurbs_surface_Xc2.vtk')
    ! Export the refined generated surface to a VTK file
    call nurbs%export_Xg('vtk/nurbs_surface_Xg2.vtk')
    !-----------------------------------------------------------------------------
    ! Finalizing
    !-----------------------------------------------------------------------------
    !> Finalize the NURBS surface object
    call nurbs%finalize()
contains
    !-----------------------------------------------------------------------------
    function generate_Xc(num_rows, num_cols, peak_height) result(control_points)
        integer, intent(in) :: num_rows, num_cols
        real(rk), intent(in) :: peak_height
        real(rk), dimension(:,:), allocatable :: control_points
        integer :: i, j
        real(rk) :: x_spacing, y_spacing, x_offset, y_offset
        x_spacing = 1.0_rk / real(num_cols - 1)
        y_spacing = 1.0_rk / real(num_rows - 1)
        x_offset = -0.5_rk
        y_offset = -0.5_rk
        allocate(control_points(num_rows * num_cols, 3))
        do i = 1, num_rows
            do j = 1, num_cols
                control_points((i - 1) * num_cols + j, 1) = x_offset + real(j - 1) * x_spacing
                control_points((i - 1) * num_cols + j, 2) = y_offset + real(i - 1) * y_spacing
                control_points((i - 1) * num_cols + j, 3) = &
                    peak_height * exp(-((control_points((i - 1) * num_cols + j, 1) ** 2) &
                    + (control_points((i - 1) * num_cols + j, 2) ** 2))) + 0.5_rk * peak_height * 0.2_rk
            end do
        end do
    end function
    !-----------------------------------------------------------------------------
end program example_nurbs_surface
Call graph
example_nurbs_surface calls set, create, export_xc, export_xg, finalize, generate_xc, insert_knots
create calls ndgrid, basis_bspline, kron
export_xc calls get_elem_xc
export_xg calls get_elem_xg
insert_knots calls set, create, compute_multiplicity, findspan, insert_knot_a_5_1
ndgrid calls ndgrid2, ndgrid3
get_elem_xc calls elemconn_c0
get_elem_xg calls elemconn_c0
set1 calls get_nc, get_order
set2 calls compute_knot_vector, get_nc
elemconn_c0 calls cmp_elemconn_c0_l, cmp_elemconn_c0_s, cmp_elemconn_c0_v
compute_knot_vector calls repelem
get_nc calls compute_multiplicity
get_order calls get_multiplicity
get_multiplicity calls compute_multiplicity