example_morph – ForCAD
example_morph Program
BSD 3-Clause
26 statements
Source File
Uses
forcad
forcad_utils
You can create your shape or use a predefined one Read coordinates from file Read element connectivities from file Set a control shape that will be used to put the shape into The contol shape is a hexahedron with 100x40x10 with 10x5x3 number of control points By modifying the control shape you can modify the shape
Map the shape into the shape
Export the shape and the control shape to vtk files Show the control geometry and geometry using PyVista
Calls
Variables
Type Attributes Name Initial
real(kind=rk), allocatable :: X(:,:)
type(nurbs_volume) :: control_shape
integer, allocatable :: elem(:,:)
integer :: i
integer :: nunit
Call graph
example_morph calls set, export_xc, export_xg, hexahedron_xc, put_to_nurbs, show
export_xc calls cmp_elem_xc_vis
export_xg calls cmp_elem_xg_vis
put_to_nurbs calls basis_bspline, kron, set_elem_xg_vis
cmp_elem_xc_vis calls elemconn_c0
cmp_elem_xg_vis calls elemconn_c0
set1 calls cmp_degree, cmp_nc
set2 calls cmp_nc, compute_knot_vector
set3 calls cmp_degree
elemconn_c0 calls cmp_elemconn_c0_l, cmp_elemconn_c0_s, cmp_elemconn_c0_v
cmp_degree calls get_multiplicity
cmp_nc calls compute_multiplicity
compute_knot_vector calls repelem
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
get_multiplicity calls compute_multiplicity