example_ppm2 – ForCAD
example_ppm2 Program
BSD 3-Clause
181 statements
Source File
Uses
forcad
forcolormap
forimage
fortime
Visualization of NURBS surfaces using ForCAD, ForImage and ForColorMap libraries This example converts NURBS surfaces (vector) to an image (raster) using ForCAD, ForImage and ForColorMap libraries.
Set the shape parameters for a tetragon Set the shape parameters for a ring Set the shape parameters for a ring Set the shape parameters for a ring Set the shape parameters for a ring
Calls
Variables
Type Attributes Name Initial
real(kind=rk), allocatable :: Xg(:,:)
real(kind=rk) :: aspect_ratio
type(color) :: background_color
integer :: blue
real(kind=rk) :: center(3)
type(colormap) :: cmap
integer :: green
integer :: height
integer :: i
integer, allocatable :: idx(:,:)
type(format_pnm) :: image
real(kind=rk) :: inner_radius
integer :: ng(2)
real(kind=rk) :: outer_radius
integer(kind=ik), allocatable :: px(:,:)
integer :: red
integer :: res1
integer :: res2
type(nurbs_surface) :: shape
type(timer) :: t
integer :: width
real(kind=rk), allocatable :: z_values(:)
Call graph
example_ppm2 calls compute_rgb, export_pnm, get_b, get_g, get_r, get_xg, create, finalize, get_ng, rotate_xc, set_half_ring, set_tetragon, translate_xc, set, set_pnm, timer_start, timer_stop
create calls set, compute_xg, ndgrid, is_rational
rotate_xc calls rotation
set_half_ring calls set
set_tetragon calls set, tetragon_xc
compute_xg calls compute_xg_bspline_2d, compute_xg_bspline_2d_1point, compute_xg_nurbs_2d, compute_xg_nurbs_2d_1point
ndgrid calls ndgrid2, ndgrid3
rotation calls cosd, sind
compute_xg_bspline_2d calls kron, basis_bspline
compute_xg_bspline_2d_1point calls kron, basis_bspline
compute_xg_nurbs_2d calls cmp_tgc_2d
compute_xg_nurbs_2d_1point calls kron, basis_bspline
set1 calls set, cmp_degree, cmp_nc
set2 calls set, cmp_nc, compute_knot_vector
set3 calls set, cmp_degree
set4 calls set
kron calls kron3, kron_t1_t1, kron_t1_t2
cmp_degree calls set, get_multiplicity
cmp_nc calls set, compute_multiplicity
cmp_tgc_2d calls kron, basis_bspline
compute_knot_vector calls repelem
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
get_multiplicity calls compute_multiplicity