fdm_elevate_and_insert_3d – ForCAD
fdm_elevate_and_insert_3d Program
BSD 3-Clause
114 statements
Source File
Uses
fortime
forcad_utils
forcad
set control points
set weights set knot vectors set NURBS volume
deallocate temporary arrays
copy initial NURBS volume (before refinement)
get initial control points, dimension, number of control points and degrees of freedom elevate degree in three directions and get sensitivities (Bs: in compact form, memory efficient) set knot vectors to insert multiplicities of knots to insert insert knots in three directions and get sensitivities (Bs: in compact form, memory efficient) compute global sensitivities (dXc_old/dXc_new) get new degrees of freedom (after refinement)
start finite difference computations compute relative error between finite difference and analytical sensitivities
finalize
Calls
Variables
Type Attributes Name Initial
real(kind=rk), allocatable :: B(:,:)
real(kind=rk), allocatable :: Bfd(:,:)
real(kind=rk), allocatable :: Bs(:,:)
real(kind=rk), allocatable :: S1(:,:)
real(kind=rk), allocatable :: S2(:,:)
real(kind=rk), allocatable :: S3(:,:)
real(kind=rk), allocatable :: S4(:,:)
real(kind=rk), allocatable :: S5(:,:)
real(kind=rk), allocatable :: S6(:,:)
real(kind=rk), allocatable :: Wc(:)
real(kind=rk), allocatable :: Xc(:,:)
real(kind=rk), allocatable :: Xc0(:,:)
real(kind=rk), allocatable :: Xcm_vec(:)
real(kind=rk), allocatable :: Xcp_vec(:)
real(kind=rk), allocatable :: Xm(:,:)
real(kind=rk), allocatable :: Xp(:,:)
integer :: d
integer, parameter :: dg1 = 4
degrees to elevate
integer, parameter :: dg2 = 3
degrees to elevate
integer, parameter :: dg3 = 2
degrees to elevate
integer :: dim
integer :: i
integer :: idx
real(kind=rk), allocatable :: knot1(:)
real(kind=rk), allocatable :: knot2(:)
real(kind=rk), allocatable :: knot3(:)
integer, parameter :: n1 = 2
number of knots to insert
integer, parameter :: n2 = 3
number of knots to insert
integer, parameter :: n3 = 4
number of knots to insert
integer :: nc0
integer :: ndof_new
integer :: ndof_old
integer, allocatable :: r1(:)
integer, allocatable :: r2(:)
integer, allocatable :: r3(:)
real(kind=rk) :: rel_err
type(nurbs_volume) :: sh0
type(nurbs_volume) :: shfd
type(nurbs_volume) :: shr
type(timer) :: t
real(kind=rk), parameter :: tol = 1e-5_rk
tolerance of finite differences
real(kind=rk), allocatable :: u1(:)
real(kind=rk), allocatable :: u2(:)
real(kind=rk), allocatable :: u3(:)
Functions
pure function generate_Xc(L) result(control_points)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: L
Return Value real(kind=rk), allocatable, (:,:)
Call graph
fdm_elevate_and_insert_3d calls get_knot, get_wc, get_xc, set, elevate_degree, finalize, generate_xc, insert_knots, kron_eye, linspace, timer_start, timer_stop
elevate_degree calls get_knot, set, elevate_degree_a_5_9, is_rational
insert_knots calls get_knot, compute_multiplicity, findspan, insert_knot_a_5_1, is_rational, s_loc, set
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
elevate_degree_a_5_9 calls compute_multiplicity, bincoeff
set1 calls set, cmp_degree, cmp_nc
set2 calls set, cmp_nc, compute_knot_vector
set3 calls set, cmp_degree
set4 calls set
bincoeff calls factln
cmp_degree calls set, get_multiplicity
cmp_nc calls compute_multiplicity, set
compute_knot_vector calls repelem
get_multiplicity calls compute_multiplicity