fdm_test_curve – ForCAD
fdm_test_curve Program
BSD 3-Clause
57 statements
Source File
Uses
forcad
Define control points for the NURBS curve Define weights for the control points (optional) Define knot vector
Set knot vector, control points, and weights for the NURBS curve object. Wc is optional
Generate the NURBS curve with a resolution of 20
Finalize the NURBS curve object Define control points for the NURBS curve Define knot vector
Set knot vector, control points for the NURBS curve object. Wc is optional
Generate the NURBS curve with a resolution of 20
Finalize the NURBS curve object
Calls
Variables
Type Attributes Name Initial
real(kind=rk), allocatable :: Tgc(:)
real(kind=rk), allocatable :: Tgcm(:)
real(kind=rk), allocatable :: Tgcp(:)
real(kind=rk), allocatable :: Wc(:)
Arrays for control points and weights
real(kind=rk), allocatable :: Xc(:,:)
Arrays for control points and weights
real(kind=rk) :: Xt
real(kind=rk) :: Xtm
real(kind=rk) :: Xtp
type(nurbs_curve) :: curve
Declare a NURBS curve object
real(kind=rk), allocatable :: d2Tgc(:)
real(kind=rk), allocatable :: d2Tgcm(:)
real(kind=rk), allocatable :: d2Tgcp(:)
real(kind=rk), allocatable :: dTgc(:)
real(kind=rk), allocatable :: dTgcm(:)
real(kind=rk), allocatable :: dTgcp(:)
real(kind=rk) :: knot(6)
Array for knot vector
real(kind=rk) :: tol
Call graph
fdm_test_curve calls derivative2, set, create, finalize
create calls compute_xg, is_rational, set
compute_xg calls compute_xg_bspline_1d, compute_xg_bspline_1d_1point, compute_xg_nurbs_1d, compute_xg_nurbs_1d_1point
derivative2_scalar calls is_rational, compute_d2tgc
derivative2_vector calls is_rational, compute_d2tgc
set1a calls set, cmp_degree
set1 calls set, cmp_degree
set2 calls set, cmp_nc, compute_knot_vector
set3 calls set, cmp_degree
set4 calls set
compute_d2tgc calls compute_d2tgc_bspline_1d_scalar, compute_d2tgc_bspline_1d_vector, compute_d2tgc_nurbs_1d_scalar, compute_d2tgc_nurbs_1d_vector
cmp_degree calls get_multiplicity
cmp_nc calls compute_multiplicity
compute_knot_vector calls repelem
compute_xg_bspline_1d calls basis_bspline
compute_xg_bspline_1d_1point calls basis_bspline
compute_xg_nurbs_1d calls cmp_tgc_1d
compute_xg_nurbs_1d_1point calls basis_bspline
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
cmp_tgc_1d calls basis_bspline
compute_d2tgc_bspline_1d_scalar calls basis_bspline_2der
compute_d2tgc_bspline_1d_vector calls basis_bspline_2der
compute_d2tgc_nurbs_1d_scalar calls basis_bspline_2der
compute_d2tgc_nurbs_1d_vector calls basis_bspline_2der
get_multiplicity calls compute_multiplicity
basis_bspline_2der calls basis_bspline_2der_a, basis_bspline_2der_b, basis_bspline_2der_c