fdm_elevate_and_insert_1d – ForCAD
fdm_elevate_and_insert_1d Program
BSD 3-Clause
87 statements
Source File
Uses
forcad_utils
forcad
fortime
set control points
set weights set knot vector
set NURBS curve
deallocate temporary arrays
copy initial NURBS curve (before refinement)
get initial control points, dimension, number of control points and degrees of freedom elevate degree and get sensitivities (Bs: in compact form, memory efficient) set knot vectors to insert multiplicities of knots to insert
insert knots and get sensitivities (Bs: in compact form, memory efficient) compute global sensitivities (dXc_old/dXc_new) get new degrees of freedom (after refinement)
start finite difference computations compute relative error between finite difference and analytical sensitivities
finalize
Calls
Variables
Type Attributes Name Initial
real(kind=rk), allocatable :: B(:,:)
real(kind=rk), allocatable :: Bfd(:,:)
real(kind=rk), allocatable :: Bs(:,:)
real(kind=rk), allocatable :: S1(:,:)
real(kind=rk), allocatable :: S2(:,:)
real(kind=rk), allocatable :: Wc(:)
real(kind=rk), allocatable :: Xc(:,:)
real(kind=rk), allocatable :: Xc0(:,:)
real(kind=rk), allocatable :: Xcm_vec(:)
real(kind=rk), allocatable :: Xcp_vec(:)
real(kind=rk), allocatable :: Xm(:,:)
real(kind=rk), allocatable :: Xp(:,:)
integer :: d
integer :: dim
integer :: i
integer :: idx
real(kind=rk), allocatable :: knot(:)
integer :: nc0
integer :: ndof_new
integer :: ndof_old
integer, parameter :: nins = 5
number of knots to insert
integer, allocatable :: r(:)
real(kind=rk) :: rel_err
type(nurbs_curve) :: sh0
type(nurbs_curve) :: shfd
type(nurbs_curve) :: shr
type(timer) :: t
integer, parameter :: tdeg = 3
degrees to elevate
real(kind=rk), parameter :: tol = 1e-5_rk
tolerance of finite differences
real(kind=rk), allocatable :: u(:)
Functions
pure function generate_Xc(L) result(control_points)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: L
Return Value real(kind=rk), allocatable, (:,:)
Call graph
fdm_elevate_and_insert_1d calls get_knot, get_wc, get_xc, set, elevate_degree, finalize, generate_xc, insert_knots, kron_eye, linspace, timer_start, timer_stop
elevate_degree calls set, elevate_degree_a_5_9, is_rational
insert_knots calls set, compute_multiplicity, findspan, insert_knot_a_5_1, is_rational
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
elevate_degree_a_5_9 calls compute_multiplicity, bincoeff
set1 calls cmp_degree, set
set1a calls cmp_degree, set
set2 calls cmp_nc, compute_knot_vector, set
set3 calls cmp_degree, set
set4 calls set
bincoeff calls factln
cmp_degree calls get_multiplicity
cmp_nc calls compute_multiplicity
compute_knot_vector calls repelem
get_multiplicity calls compute_multiplicity