fdm_test_surface – ForCAD
fdm_test_surface Program
BSD 3-Clause
73 statements
Source File
Uses
forcad
Generate the NURBS surface with a resolution of 20
Finalize the NURBS surface object Generate the NURBS surface with a resolution of 20
Finalize the NURBS surface object
Calls
Variables
Type Attributes Name Initial
real(kind=rk), allocatable :: BFD(:,:)
real(kind=rk), allocatable :: BFD2(:,:)
real(kind=rk), allocatable :: CFD(:,:)
real(kind=rk), allocatable :: CFD2(:,:)
real(kind=rk), allocatable :: FFD(:,:)
real(kind=rk), allocatable :: FFD2(:,:)
real(kind=rk), allocatable :: Tgc(:)
real(kind=rk), allocatable :: Tgcm(:)
real(kind=rk), allocatable :: Tgcp(:)
real(kind=rk), allocatable :: Wc(:)
Declare the control points weights
real(kind=rk) :: Xt(2)
real(kind=rk) :: Xtm(2)
real(kind=rk) :: Xtp(2)
real(kind=rk), allocatable :: d2Tgc(:,:)
real(kind=rk), allocatable :: d2Tgcm(:,:)
real(kind=rk), allocatable :: d2Tgcp(:,:)
real(kind=rk), allocatable :: dTgc(:,:)
real(kind=rk), allocatable :: dTgcm(:,:)
real(kind=rk), allocatable :: dTgcp(:,:)
integer :: i
type(nurbs_surface) :: surface
Declare a NURBS surface object
real(kind=rk) :: tol
Call graph
fdm_test_surface calls derivative2, create, finalize, set_tetragon
create calls compute_xg, ndgrid, is_rational, set
set_tetragon calls set, tetragon_xc
compute_xg calls compute_xg_bspline_2d, compute_xg_bspline_2d_1point, compute_xg_nurbs_2d, compute_xg_nurbs_2d_1point
ndgrid calls ndgrid2, ndgrid3
derivative2_scalar calls is_rational, compute_d2tgc
derivative2_vector calls ndgrid, is_rational, compute_d2tgc
compute_d2tgc calls compute_d2tgc_bspline_2d_scalar, compute_d2tgc_bspline_2d_vector, compute_d2tgc_nurbs_2d_scalar, compute_d2tgc_nurbs_2d_vector
compute_xg_bspline_2d calls kron, basis_bspline
compute_xg_bspline_2d_1point calls kron, basis_bspline
compute_xg_nurbs_2d calls cmp_tgc_2d
compute_xg_nurbs_2d_1point calls kron, basis_bspline
set1 calls set, cmp_degree, cmp_nc
set2 calls set, cmp_nc, compute_knot_vector
set3 calls set, cmp_degree
set4 calls set
kron calls kron3, kron_t1_t1, kron_t1_t2
cmp_degree calls set, get_multiplicity
cmp_nc calls set, compute_multiplicity
cmp_tgc_2d calls kron, basis_bspline
compute_d2tgc_bspline_2d_scalar calls kron, basis_bspline_2der
compute_d2tgc_bspline_2d_vector calls kron, basis_bspline_2der
compute_d2tgc_nurbs_2d_scalar calls kron, basis_bspline_2der
compute_d2tgc_nurbs_2d_vector calls kron, basis_bspline_2der
compute_knot_vector calls repelem
basis_bspline_2der calls basis_bspline_2der_a, basis_bspline_2der_b, basis_bspline_2der_c
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
get_multiplicity calls compute_multiplicity