lsq_fit_bspline_2d – ForCAD
lsq_fit_bspline_2d Program
BSD 3-Clause
65 statements
Source File
Uses
forcad
forcad_utils
Calls
Variables
Type Attributes Name Initial
real(kind=rk), allocatable :: Xdata(:,:)
real(kind=rk), allocatable :: Xg_eval(:,:)
real(kind=rk), allocatable :: Xt(:,:)
real(kind=rk), allocatable :: Xt1(:)
real(kind=rk), allocatable :: Xt2(:)
type(nurbs_surface) :: bsp
real(kind=rk) :: err1
real(kind=rk) :: err2
real(kind=rk) :: err3
integer :: i
integer :: n(2)
integer :: ndata
real(kind=rk), parameter :: pi = acos(-1.0_rk)
real(kind=rk) :: rms
Call graph
lsq_fit_bspline_2d calls ndgrid, get_degree, get_knot, get_nc, get_xg, set, create, export_xc, export_xg, export_xth_in_xg, get_continuity, lsq_fit_bspline, show
ndgrid calls ndgrid2, ndgrid3
create calls ndgrid, compute_xg, is_rational, set
export_xc calls cmp_elem_xc_vis, export_vtk_legacy, set
export_xg calls cmp_elem_xg_vis, export_vtk_legacy, set
export_xth_in_xg calls compute_xg, unique, export_vtk_legacy, is_rational, set
get_continuity calls compute_multiplicity
lsq_fit_bspline calls kron, basis_bspline, solve, set
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
compute_xg calls compute_xg_bspline_2d, compute_xg_bspline_2d_1point, compute_xg_nurbs_2d, compute_xg_nurbs_2d_1point
kron calls kron3, kron_t1_t1, kron_t1_t2
unique calls unique_integer, unique_real
cmp_elem_xc_vis calls elemconn_c0
cmp_elem_xg_vis calls elemconn_c0
get_nc_dir calls compute_multiplicity
set1 calls set, cmp_degree, cmp_nc
set2 calls set, cmp_nc, compute_knot_vector
set3 calls set, cmp_degree
set4 calls set
elemconn_c0 calls cmp_elemconn_c0_l, cmp_elemconn_c0_s, cmp_elemconn_c0_v
cmp_degree calls set, get_multiplicity
cmp_nc calls compute_multiplicity, set
compute_knot_vector calls repelem
compute_xg_bspline_2d calls kron, basis_bspline
compute_xg_bspline_2d_1point calls kron, basis_bspline
compute_xg_nurbs_2d calls cmp_tgc_2d
compute_xg_nurbs_2d_1point calls kron, basis_bspline
cmp_tgc_2d calls kron, basis_bspline
get_multiplicity calls compute_multiplicity