lsq_fit_bspline_1d – ForCAD
lsq_fit_bspline_1d Program
BSD 3-Clause
56 statements
Source File
Uses
forcad
Calls
Variables
Type Attributes Name Initial
real(kind=rk), allocatable :: Xdata(:,:)
real(kind=rk), allocatable :: Xg_eval(:,:)
real(kind=rk), allocatable :: Xt(:)
type(nurbs_curve) :: bsp
real(kind=rk) :: err1
real(kind=rk) :: err2
real(kind=rk) :: err3
integer :: i
integer :: n
real(kind=rk), parameter :: pi = acos(-1.0_rk)
real(kind=rk) :: rms
Call graph
lsq_fit_bspline_1d calls get_knot, get_xg, set, create, export_xc, export_xg, get_continuity, get_degree, get_nc, lsq_fit_bspline, show
create calls compute_xg, is_rational, set
export_xc calls cmp_elem_xc_vis, export_vtk_legacy, set
export_xg calls cmp_elem_xg_vis, export_vtk_legacy, set
get_continuity calls compute_multiplicity
lsq_fit_bspline calls basis_bspline, solve, set
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
compute_xg calls compute_xg_bspline_1d, compute_xg_bspline_1d_1point, compute_xg_nurbs_1d, compute_xg_nurbs_1d_1point
cmp_elem_xc_vis calls elemconn_c0
cmp_elem_xg_vis calls elemconn_c0
set1a calls set, cmp_degree
set1 calls set, cmp_degree
set2 calls set, cmp_nc, compute_knot_vector
set3 calls set, cmp_degree
set4 calls set
elemconn_c0 calls cmp_elemconn_c0_l, cmp_elemconn_c0_s, cmp_elemconn_c0_v
cmp_degree calls get_multiplicity
cmp_nc calls compute_multiplicity
compute_knot_vector calls repelem
compute_xg_bspline_1d calls basis_bspline
compute_xg_bspline_1d_1point calls basis_bspline
compute_xg_nurbs_1d calls cmp_tgc_1d
compute_xg_nurbs_1d_1point calls basis_bspline
cmp_tgc_1d calls basis_bspline
get_multiplicity calls compute_multiplicity