nearest_point_1d – ForCAD
nearest_point_1d Program
BSD 3-Clause
25 statements
Source File
Uses
forcad
Define control points for the NURBS curve Define weights for the control points (optional) Define knot vector
Set knot vector, control points, and weights for the NURBS curve object. Wc is optional
Generate the NURBS curve with a resolution of 20
Find the nearest point on the curve to a given point Find the nearest point on the curve to a given point The optimization method is used to find the nearest point The optimization method is based on the Newton-Raphson method Finalize the NURBS curve object
Calls
Variables
Type Attributes Name Initial
real(kind=rk), allocatable :: Wc(:)
Arrays for control points and weights
real(kind=rk), allocatable :: Xc(:,:)
Arrays for control points and weights
integer :: id
Variable for the id of the nearest point
real(kind=rk) :: knot(6)
Array for knot vector
real(kind=rk), allocatable :: nearest_Xg(:)
Array for the nearest point on the curve
real(kind=rk) :: nearest_Xt
Array for the parametric coordinates of the nearest point
type(nurbs_curve) :: shape
Declare a NURBS curve object
Call graph
nearest_point_1d calls set, create, finalize, nearest_point, nearest_point2
create calls compute_xg, is_rational
nearest_point calls nearest_point_help_1d
nearest_point2 calls create, finalize, nearest_point, derivative2, cmp_xg
compute_xg calls compute_xg_bspline_1d, compute_xg_bspline_1d_1point, compute_xg_nurbs_1d, compute_xg_nurbs_1d_1point
cmp_xg calls compute_xg, is_rational
set1 calls cmp_degree
set1a calls cmp_degree
set2 calls cmp_nc, compute_knot_vector
set3 calls cmp_degree
cmp_degree calls get_multiplicity
cmp_nc calls compute_multiplicity
compute_knot_vector calls repelem
compute_xg_bspline_1d calls basis_bspline
compute_xg_bspline_1d_1point calls basis_bspline
compute_xg_nurbs_1d calls cmp_tgc_1d
compute_xg_nurbs_1d_1point calls basis_bspline
derivative2_scalar calls is_rational, compute_d2tgc
derivative2_vector calls is_rational, compute_d2tgc
compute_d2tgc calls compute_d2tgc_bspline_1d_scalar, compute_d2tgc_bspline_1d_vector, compute_d2tgc_nurbs_1d_scalar, compute_d2tgc_nurbs_1d_vector
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
cmp_tgc_1d calls basis_bspline
get_multiplicity calls compute_multiplicity
compute_d2tgc_bspline_1d_scalar calls basis_bspline_2der
compute_d2tgc_bspline_1d_vector calls basis_bspline_2der
compute_d2tgc_nurbs_1d_scalar calls basis_bspline_2der
compute_d2tgc_nurbs_1d_vector calls basis_bspline_2der
basis_bspline_2der calls basis_bspline_2der_a, basis_bspline_2der_b, basis_bspline_2der_c