nearest_point_2d – ForCAD
nearest_point_2d Program
BSD 3-Clause
22 statements
Source File
Uses
forcad
Set a surface with 4 control points The weights of the control points (Wc) are optional.
Generate the NURBS surface with resolutions of 30 in both dimensions
Find the nearest point on the surface to a given point Find the nearest point on the surface to a given point The optimization method is used to find the nearest point The optimization method is based on the Newton-Raphson method Finalize the NURBS surface object
Calls
Variables
Type Attributes Name Initial
real(kind=rk) :: Wc(4)
Weights of the control points
real(kind=rk) :: Xc(4,3)
Control points
integer :: id
id of the nearest point
real(kind=rk), allocatable :: nearest_Xg(:)
Coordinates of the nearest point on the surface
real(kind=rk), allocatable :: nearest_Xt(:)
Corresponding parametric coordinates of the nearest point
type(nurbs_surface) :: shape
Declare a NURBS surface object
Call graph
nearest_point_2d calls set, create, finalize, nearest_point2, nearest_point
create calls compute_xg, ndgrid, is_rational
nearest_point2 calls create, finalize, nearest_point, derivative2, cmp_xg, inv
nearest_point calls nearest_point_help_2d
compute_xg calls compute_xg_bspline_2d, compute_xg_bspline_2d_1point, compute_xg_nurbs_2d, compute_xg_nurbs_2d_1point
ndgrid calls ndgrid2, ndgrid3
cmp_xg calls compute_xg, is_rational
inv calls inv, det
set1 calls cmp_degree, cmp_nc
set2 calls cmp_nc, compute_knot_vector
set3 calls cmp_degree
cmp_degree calls get_multiplicity
cmp_nc calls compute_multiplicity
compute_knot_vector calls repelem
compute_xg_bspline_2d calls basis_bspline, kron
compute_xg_bspline_2d_1point calls basis_bspline, kron
compute_xg_nurbs_2d calls cmp_tgc_2d
compute_xg_nurbs_2d_1point calls basis_bspline, kron
derivative2_scalar calls is_rational, compute_d2tgc
derivative2_vector calls ndgrid, is_rational, compute_d2tgc
compute_d2tgc calls compute_d2tgc_bspline_2d_scalar, compute_d2tgc_bspline_2d_vector, compute_d2tgc_nurbs_2d_scalar, compute_d2tgc_nurbs_2d_vector
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
cmp_tgc_2d calls basis_bspline, kron
get_multiplicity calls compute_multiplicity
compute_d2tgc_bspline_2d_scalar calls kron, basis_bspline_2der
compute_d2tgc_bspline_2d_vector calls kron, basis_bspline_2der
compute_d2tgc_nurbs_2d_scalar calls kron, basis_bspline_2der
compute_d2tgc_nurbs_2d_vector calls kron, basis_bspline_2der