nearest_point_2d_bench – ForCAD
nearest_point_2d_bench Program
BSD 3-Clause
28 statements
Source File
Uses
fortime
forcad
Set a tetragon with lengths of 2.0 and 3.0 and 3 and 4 control points in each direction The weights of the control points (Wc) are optional.
Generate the NURBS surface with resolutions of 30 in both dimensions
Find the nearest point on the surface to a given point Finalize the NURBS surface object
Calls
Variables
Type Attributes Name Initial
integer :: i
integer :: id
id of the nearest point
integer :: j
real(kind=rk) :: nearest_Xg(3)
Coordinates of the nearest point on the surface
real(kind=rk) :: nearest_Xt(2)
Corresponding parametric coordinates of the nearest point
real(kind=rk), allocatable :: points(:,:)
real(kind=rk) :: pointsi(3)
type(nurbs_surface) :: shape
Declare a NURBS surface object
type(timer) :: t
Call graph
nearest_point_2d_bench calls create, finalize, nearest_point, set_tetragon, timer_start, timer_stop
create calls compute_xg, ndgrid, is_rational, set
set_tetragon calls set, tetragon_xc
compute_xg calls compute_xg_bspline_2d, compute_xg_bspline_2d_1point, compute_xg_nurbs_2d, compute_xg_nurbs_2d_1point
ndgrid calls ndgrid2, ndgrid3
compute_xg_bspline_2d calls kron, basis_bspline
compute_xg_bspline_2d_1point calls kron, basis_bspline
compute_xg_nurbs_2d calls cmp_tgc_2d
compute_xg_nurbs_2d_1point calls kron, basis_bspline
set1 calls set, cmp_degree, cmp_nc
set2 calls set, cmp_nc, compute_knot_vector
set3 calls set, cmp_degree
set4 calls set
kron calls kron3, kron_t1_t1, kron_t1_t2
cmp_degree calls set, get_multiplicity
cmp_nc calls set, compute_multiplicity
cmp_tgc_2d calls kron, basis_bspline
compute_knot_vector calls repelem
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
get_multiplicity calls compute_multiplicity