nearest_point_3d – ForCAD
nearest_point_3d Program
BSD 3-Clause
26 statements
Source File
Uses
forcad
The weights of the control points (Wc) are optional.
Generate the NURBS volume with resolutions of 20, 20, 20
Find the nearest point on the volume to a given point Find the nearest point on the volume to a given point The optimization method is used to find the nearest point The optimization method is based on the Newton-Raphson method Finalize the NURBS volume object
Calls
Variables
Type Attributes Name Initial
real(kind=rk) :: Wc(8)
Weights of the control points
real(kind=rk) :: Xc(8,3)
Control points
integer :: id
id of the nearest point
real(kind=rk) :: nearest_Xg(3)
Coordinates of the nearest point on the volume
real(kind=rk) :: nearest_Xt(3)
Corresponding parametric coordinates of the nearest point
type(nurbs_volume) :: shape
Declare a NURBS volume object
Call graph
nearest_point_3d calls set, create, finalize, nearest_point2, nearest_point
create calls compute_xg, ndgrid, is_rational, set
nearest_point2 calls create, finalize, nearest_point, derivative2, cmp_xg, inv
compute_xg calls compute_xg_bspline_3d, compute_xg_bspline_3d_1point, compute_xg_nurbs_3d, compute_xg_nurbs_3d_1point
ndgrid calls ndgrid2, ndgrid3
cmp_xg calls compute_xg, is_rational
inv calls inv, det, eye, solve
set1 calls set, cmp_degree, cmp_nc
set2 calls set, cmp_nc, compute_knot_vector
set3 calls set, cmp_degree
set4 calls set
cmp_degree calls set, get_multiplicity
cmp_nc calls set, compute_multiplicity
compute_knot_vector calls repelem
compute_xg_bspline_3d calls kron, basis_bspline
compute_xg_bspline_3d_1point calls kron, basis_bspline
compute_xg_nurbs_3d calls cmp_tgc_3d
compute_xg_nurbs_3d_1point calls kron, basis_bspline
derivative2_scalar calls is_rational, compute_d2tgc
derivative2_vector calls ndgrid, is_rational, compute_d2tgc
compute_d2tgc calls compute_d2tgc_bspline_3d_scalar, compute_d2tgc_bspline_3d_vector, compute_d2tgc_nurbs_3d_scalar, compute_d2tgc_nurbs_3d_vector
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
kron calls kron3, kron_t1_t1, kron_t1_t2
cmp_tgc_3d calls kron, basis_bspline
get_multiplicity calls compute_multiplicity
compute_d2tgc_bspline_3d_scalar calls kron, basis_bspline_2der
compute_d2tgc_bspline_3d_vector calls kron, basis_bspline_2der
compute_d2tgc_nurbs_3d_scalar calls kron, basis_bspline_2der
compute_d2tgc_nurbs_3d_vector calls kron, basis_bspline_2der
basis_bspline_2der calls basis_bspline_2der_a, basis_bspline_2der_b, basis_bspline_2der_c