poisson_iga_solver_3d – ForCAD
poisson_iga_solver_3d Program
BSD 3-Clause
126 statements
Source File
Uses
fortime
forcad
forcad_utils
Solves the 3D Poisson problem using Isogeometric Analysis (IGA).
This code solves the equation: using a B-spline volume on a rectangular domain.
The solution is discretized using tensor-product B-spline basis functions over a structured control net. The global linear system is assembled and solved using a basic internal Cholesky solver.
The resulting solution is exported to VTK format for visualization.
The L2 error norm with respect to the exact solution is computed and printed.
Note
This implementation uses B-spline geometry (no rational weights), hence the volume is not a full NURBS.
Warning
"Slow solver" The solver uses an internal Cholesky factorization which is not optimized. For large systems, consider replacing it with a more scalable external solver.
Domain size and number of control points Number knots to insert in each direction Mode numbers for the source term and exact solution Resolution of the visualization grid filename for VTK export
Construct the NURBS volume For simplicity, set_hexahedron creates a rectangular volume with uniform knot spacing For more complex geometries, use vol%set() with knots, continuity,...
Insert knots in the first and second directions Extract geometry and mesh structure Assemble global stiffness matrix and load vector Apply homogeneous Dirichlet boundary conditions Solve the linear system K·X = b Export solution at control points to VTK
Interpolate solution and export field Compute the L2 error norm
Calls
Variables
Type Attributes Name Initial
real(kind=rk), allocatable :: K(:,:)
Global stiffness matrix
real(kind=rk) :: L(3)
Domain size
real(kind=rk), allocatable :: T(:)
Basis function values at quadrature point
real(kind=rk), allocatable :: X(:,:)
Global solution vector
real(kind=rk), allocatable :: Xc(:,:)
Control point coordinates
real(kind=rk), allocatable :: Xg(:)
Physical coordinates at quadrature point
real(kind=rk), allocatable :: b(:)
Global right-hand side vector
real(kind=rk), allocatable :: dT(:,:)
Derivatives of basis functions at quadrature point
real(kind=rk) :: dV
Differential element volume
integer, allocatable :: dirichlet_id(:)
Indices for Dirichlet boundary conditions
integer :: dof
Degrees of freedom per control point (1 for scalar field)
integer, allocatable :: elem(:,:)
Element connectivity matrix
integer, allocatable :: elem_e(:)
Local connectivity of current element
character(len=256) :: filename
Filename for VTK export
integer :: i
Generic loop index
integer :: ie
Element index
integer :: ig
Quadrature (Gauss) point index
integer :: ki(3)
Number of knots to insert in each direction
real(kind=rk) :: l2_error
L2 error norm accumulator
integer :: m(3)
Mode numbers for source and exact solution
integer :: nc(3)
Number of control points in each direction
integer :: nct
Total number of control points
integer :: ndof
Total degrees of freedom
integer :: nelem
Number of elements
integer :: nnelem
Number of local nodes per element
real(kind=rk), parameter :: pi = acos(-1.0_rk)
Constant
integer :: res(3)
Visualization resolution
type(timer) :: ti
Timer object for performance measurement
real(kind=rk), allocatable :: u_h(:,:)
Interpolated solution field on grid
type(nurbs_volume) :: vol
NURBS volume object
Functions
pure function exact_solution(p, d, n) result(u)
Computes the exact solution corresponding to the source term
Read more…
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: p(3)
Coordinates (x, y, z)
real(kind=rk), intent(in) :: d(3)
Domain size (L1, L2, L3)
integer, intent(in) :: n(3)
Mode numbers (m1, m2, m3)
Return Value real(kind=rk)
pure function source_term(p, d, n) result(f)
Computes the source function
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: p(3)
Coordinates (x, y, z)
real(kind=rk), intent(in) :: d(3)
Domain size (L1, L2, L3)
integer, intent(in) :: n(3)
Mode numbers (m1, m2, m3)
Return Value real(kind=rk)
Call graph
poisson_iga_solver_3d calls basis, get_degree, get_nc, get_xc, ansatz, cmp_elem, create, exact_solution, export_xc, export_xg, finalize, insert_knots, set_hexahedron, solve, source_term, timer_start, timer_stop
ansatz calls cmp_elem, gauss_leg, ndgrid, unique, derivative, set, det, inv
cmp_elem calls elemconn_cn, unique, get_multiplicity
create calls compute_xg, ndgrid, is_rational, set
export_xc calls cmp_elem_xc_vis, export_vtk_legacy, set
export_xg calls cmp_elem_xg_vis, export_vtk_legacy, set
insert_knots calls compute_multiplicity, get_knot, findspan, insert_knot_a_5_1, is_rational, s_loc, set
set_hexahedron calls set, hexahedron_xc
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
compute_xg calls compute_xg_bspline_3d, compute_xg_bspline_3d_1point, compute_xg_nurbs_3d, compute_xg_nurbs_3d_1point
elemconn_cn calls cmp_elemconn_cn_l, cmp_elemconn_cn_s, cmp_elemconn_cn_v
gauss_leg calls gauss_legendre_1d, gauss_legendre_2d, gauss_legendre_3d
ndgrid calls ndgrid2, ndgrid3
unique calls unique_integer, unique_real
basis_scalar calls is_rational, compute_tgc
basis_vector calls ndgrid, is_rational, compute_tgc
cmp_elem_xc_vis calls elemconn_c0
cmp_elem_xg_vis calls elemconn_c0
get_multiplicity calls compute_multiplicity
get_nc_dir calls compute_multiplicity
inv calls solve, det, inv, eye
compute_tgc calls compute_tgc_bspline_3d_scalar, compute_tgc_bspline_3d_vector, compute_tgc_nurbs_3d_scalar, compute_tgc_nurbs_3d_vector
elemconn_c0 calls cmp_elemconn_c0_l, cmp_elemconn_c0_s, cmp_elemconn_c0_v
compute_xg_bspline_3d calls kron, basis_bspline
compute_xg_bspline_3d_1point calls kron, basis_bspline
compute_xg_nurbs_3d calls cmp_tgc_3d
compute_xg_nurbs_3d_1point calls kron, basis_bspline
derivative_scalar calls is_rational, compute_dtgc
derivative_vector calls ndgrid, is_rational, compute_dtgc
gauss_legendre_1d calls gauss_legendre
gauss_legendre_2d calls ndgrid, kron, gauss_legendre
gauss_legendre_3d calls ndgrid, kron, gauss_legendre
set1 calls set, cmp_degree, cmp_nc
set2 calls set, cmp_nc, compute_knot_vector
set3 calls set, cmp_degree
set4 calls set
compute_dtgc calls compute_dtgc_bspline_3d_scalar, compute_dtgc_bspline_3d_vector, compute_dtgc_nurbs_3d_scalar, compute_dtgc_nurbs_3d_vector
kron calls kron3, kron_t1_t1, kron_t1_t2
cmp_degree calls get_multiplicity, set
cmp_nc calls compute_multiplicity, set
cmp_tgc_3d calls kron, basis_bspline
compute_knot_vector calls repelem
compute_tgc_bspline_3d_scalar calls kron, basis_bspline
compute_tgc_bspline_3d_vector calls kron, basis_bspline
compute_tgc_nurbs_3d_scalar calls kron, basis_bspline
compute_tgc_nurbs_3d_vector calls kron, basis_bspline
compute_dtgc_bspline_3d_scalar calls kron, basis_bspline_der
compute_dtgc_bspline_3d_vector calls kron, basis_bspline_der
compute_dtgc_nurbs_3d_scalar calls kron, basis_bspline_der
compute_dtgc_nurbs_3d_vector calls kron, basis_bspline_der
basis_bspline_der calls basis_bspline_der_a, basis_bspline_der_b