shape_half_circle – ForCAD
shape_half_circle Program
BSD 3-Clause
11 statements
Source File
Uses
forcad
Set up a half circle shape centered at the 0,0,0 with a radius of 1
Export the control points to a VTK file for visualization.
Create the shape using the specified number of elements in each direction.
Export the geometry to a VTK file for visualization.
Show the control geometry and geometry using PyVista
Finalize and clean up the shape object.
Calls
Variables
Type Attributes Name Initial
type(nurbs_curve) :: shape
Call graph
shape_half_circle calls create, export_xc, export_xg, finalize, set_half_circle, show
create calls compute_xg, is_rational, set
export_xc calls cmp_elem_xc_vis, export_vtk_legacy, set
export_xg calls cmp_elem_xg_vis, export_vtk_legacy, set
set_half_circle calls set
compute_xg calls compute_xg_bspline_1d, compute_xg_bspline_1d_1point, compute_xg_nurbs_1d, compute_xg_nurbs_1d_1point
cmp_elem_xc_vis calls elemconn_c0
cmp_elem_xg_vis calls elemconn_c0
elemconn_c0 calls cmp_elemconn_c0_l, cmp_elemconn_c0_s, cmp_elemconn_c0_v
compute_xg_bspline_1d calls basis_bspline
compute_xg_bspline_1d_1point calls basis_bspline
compute_xg_nurbs_1d calls cmp_tgc_1d
compute_xg_nurbs_1d_1point calls basis_bspline
set1a calls set, cmp_degree
set1 calls set, cmp_degree
set2 calls set, cmp_nc, compute_knot_vector
set3 calls set, cmp_degree
set4 calls set
cmp_degree calls get_multiplicity
cmp_nc calls compute_multiplicity
cmp_tgc_1d calls basis_bspline
compute_knot_vector calls repelem
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
get_multiplicity calls compute_multiplicity