shape_tetragon – ForCAD
shape_tetragon Program
BSD 3-Clause
11 statements
Source File
Uses
forcad
Set a tetragon with lengths of 2.0 and 3.0 and 3 and 4 control points in each direction The weights of the control points (Wc) are optional.
Export the control points to a VTK file
Generate the NURBS surface with resolutions of 30 in both dimensions
Export the generated surface to a VTK file
Show the control geometry and geometry using PyVista
Finalize the NURBS surface object
Calls
Variables
Type Attributes Name Initial
type(nurbs_surface) :: shape
Declare a NURBS surface object
Call graph
shape_tetragon calls create, export_xc, export_xg, finalize, set_tetragon, show
create calls compute_xg, ndgrid, is_rational, set
export_xc calls cmp_elem_xc_vis, export_vtk_legacy, set
export_xg calls cmp_elem_xg_vis, export_vtk_legacy, set
set_tetragon calls set, tetragon_xc
compute_xg calls compute_xg_bspline_2d, compute_xg_bspline_2d_1point, compute_xg_nurbs_2d, compute_xg_nurbs_2d_1point
ndgrid calls ndgrid2, ndgrid3
cmp_elem_xc_vis calls elemconn_c0
cmp_elem_xg_vis calls elemconn_c0
elemconn_c0 calls cmp_elemconn_c0_l, cmp_elemconn_c0_s, cmp_elemconn_c0_v
compute_xg_bspline_2d calls kron, basis_bspline
compute_xg_bspline_2d_1point calls kron, basis_bspline
compute_xg_nurbs_2d calls cmp_tgc_2d
compute_xg_nurbs_2d_1point calls kron, basis_bspline
set1 calls set, cmp_degree, cmp_nc
set2 calls set, cmp_nc, compute_knot_vector
set3 calls set, cmp_degree
set4 calls set
kron calls kron3, kron_t1_t1, kron_t1_t2
cmp_degree calls set, get_multiplicity
cmp_nc calls set, compute_multiplicity
cmp_tgc_2d calls kron, basis_bspline
compute_knot_vector calls repelem
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
get_multiplicity calls compute_multiplicity