shape_hexahedron – ForCAD
shape_hexahedron Program
BSD 3-Clause
11 statements
Source File
Uses
forcad
Set up a hexahedron shape with dimensions L = [2.0, 4.0, 8.0] and a specified number of control points nc = [4, 6, 8]. The weights of the control points (Wc) are optional.
Export the control points to a VTK file for visualization.
Create the shape using the specified number of elements in each direction.
Export the geometry to a VTK file for visualization.
Show the control geometry and geometry using PyVista
Finalize and clean up the shape object.
Calls
Variables
Type Attributes Name Initial
type(nurbs_volume) :: shape
Call graph
shape_hexahedron calls create, export_xc, export_xg, finalize, set_hexahedron, show
create calls compute_xg, ndgrid, is_rational, set
export_xc calls cmp_elem_xc_vis, export_vtk_legacy, set
export_xg calls cmp_elem_xg_vis, export_vtk_legacy, set
set_hexahedron calls set, hexahedron_xc
compute_xg calls compute_xg_bspline_3d, compute_xg_bspline_3d_1point, compute_xg_nurbs_3d, compute_xg_nurbs_3d_1point
ndgrid calls ndgrid2, ndgrid3
cmp_elem_xc_vis calls elemconn_c0
cmp_elem_xg_vis calls elemconn_c0
elemconn_c0 calls cmp_elemconn_c0_l, cmp_elemconn_c0_s, cmp_elemconn_c0_v
compute_xg_bspline_3d calls kron, basis_bspline
compute_xg_bspline_3d_1point calls kron, basis_bspline
compute_xg_nurbs_3d calls cmp_tgc_3d
compute_xg_nurbs_3d_1point calls kron, basis_bspline
set1 calls set, cmp_degree, cmp_nc
set2 calls set, cmp_nc, compute_knot_vector
set3 calls set, cmp_degree
set4 calls set
kron calls kron3, kron_t1_t1, kron_t1_t2
cmp_degree calls set, get_multiplicity
cmp_nc calls set, compute_multiplicity
cmp_tgc_3d calls kron, basis_bspline
compute_knot_vector calls repelem
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
get_multiplicity calls compute_multiplicity