test_nurbs_surface – ForCAD
test_nurbs_surface Program
BSD 3-Clause
325 statements
Source File
Uses
forcad
forunittest
forcad_utils
Calls
Variables
Type Attributes Name Initial
real(kind=rk), allocatable :: Tgc(:,:)
real(kind=rk), allocatable :: Tgc1(:)
real(kind=rk), allocatable :: Tgc1b(:)
real(kind=rk), allocatable :: Tgcb(:,:)
real(kind=rk), allocatable :: Wc(:)
real(kind=rk), allocatable :: Xc(:,:)
real(kind=rk), allocatable :: Xg(:,:)
real(kind=rk), allocatable :: Xgb(:,:)
real(kind=rk) :: area
real(kind=rk) :: areab
type(nurbs_surface) :: bsp
real(kind=rk), allocatable :: d2Tgc(:,:,:)
real(kind=rk), allocatable :: d2Tgc1(:,:)
real(kind=rk), allocatable :: d2Tgc1b(:,:)
real(kind=rk), allocatable :: d2Tgcb(:,:,:)
real(kind=rk), allocatable :: dTgc(:,:,:)
real(kind=rk), allocatable :: dTgc1(:,:)
real(kind=rk), allocatable :: dTgc1b(:,:)
real(kind=rk), allocatable :: dTgcb(:,:,:)
integer, allocatable :: elemConn(:,:)
integer :: i
integer :: id
real(kind=rk) :: knot1(4)
real(kind=rk) :: knot2(4)
real(kind=rk) :: nearest_Xg(3)
real(kind=rk) :: nearest_Xt(2)
type(nurbs_surface) :: nurbs
type(unit_test) :: ut
Call graph
test_nurbs_surface calls check, ndgrid, lsq_fit_bspline, n, basis, derivative2, derivative, get_degree, get_knot, get_nc, get_wc, get_xc, get_xg, set, cmp_area, cmp_elem_xc_vis, cmp_elem_xg_vis, cmp_elem, cmp_nc, create, elevate_degree, export_iges, export_xc, export_xg, export_xth, finalize, get_continuity, get_elem_xc_vis, get_elem_xg_vis, get_elem, get_multiplicity, get_xt, insert_knots, modify_wc, modify_xc, nearest_point2, nearest_point, remove_knots, rotate_xc, rotate_xg, set_c, set_elem_xc_vis, set_elem_xg_vis, set_elem, set_half_ring, set_ring, set_tetragon, translate_xc, translate_xg, xdata, xg_eval, xt, xt1, xt2
ndgrid calls ndgrid2, ndgrid3
cmp_area calls cmp_elem, ansatz, reduce
cmp_elem_xc_vis calls elemconn_c0
cmp_elem_xg_vis calls elemconn_c0
cmp_elem calls get_multiplicity, elemconn_cn, unique
cmp_nc calls compute_multiplicity, set
create calls ndgrid, compute_xg, is_rational, set
elevate_degree calls get_knot, set, elevate_degree_a_5_9, is_rational
export_iges calls append, delete, init, makedpsections, makegsection, makessection, is_rational, writeigesfile
export_xc calls cmp_elem_xc_vis, export_vtk_legacy, set
export_xg calls cmp_elem_xg_vis, export_vtk_legacy, set
export_xth calls ndgrid, unique, cmp_elem_xth, export_vtk_legacy
get_continuity calls compute_multiplicity
get_multiplicity calls compute_multiplicity
insert_knots calls get_knot, compute_multiplicity, findspan, insert_knot_a_5_1, is_rational, s_loc, set
modify_wc calls get_knot, get_wc, get_xc, set
modify_xc calls get_knot, get_wc, get_xc, set
nearest_point2 calls derivative2, create, finalize, nearest_point, cmp_xg, inv
remove_knots calls get_knot, set, compute_multiplicity, findspan, is_rational, remove_knots_a_5_8
rotate_xc calls rotation
rotate_xg calls rotation
set_c calls set
set_half_ring calls set
set_ring calls set
set_tetragon calls set, tetragon_xc
compute_multiplicity calls compute_multiplicity1, compute_multiplicity2
compute_xg calls compute_xg_bspline_2d, compute_xg_bspline_2d_1point, compute_xg_nurbs_2d, compute_xg_nurbs_2d_1point
elemconn_c0 calls cmp_elemconn_c0_l, cmp_elemconn_c0_s, cmp_elemconn_c0_v
elemconn_cn calls cmp_elemconn_cn_l, cmp_elemconn_cn_s, cmp_elemconn_cn_v
unique calls unique_integer, unique_real
ansatz calls ndgrid, derivative, set, cmp_elem, unique, inv, gauss_leg, det
basis_scalar calls is_rational, compute_tgc
basis_vector calls ndgrid, is_rational, compute_tgc
cmp_elem_xth calls elemconn_c0, unique
cmp_xg calls compute_xg, is_rational
derivative2_scalar calls is_rational, compute_d2tgc
derivative2_vector calls ndgrid, is_rational, compute_d2tgc
derivative_scalar calls is_rational, compute_dtgc
derivative_vector calls ndgrid, is_rational, compute_dtgc
elevate_degree_a_5_9 calls compute_multiplicity, bincoeff
get_nc_dir calls compute_multiplicity
inv calls inv, det, eye, solve
rotation calls cosd, sind
set1 calls cmp_nc, set, cmp_degree
set2 calls cmp_nc, set, compute_knot_vector
set3 calls set, cmp_degree
set4 calls set
compute_d2tgc calls compute_d2tgc_bspline_2d_scalar, compute_d2tgc_bspline_2d_vector, compute_d2tgc_nurbs_2d_scalar, compute_d2tgc_nurbs_2d_vector
compute_dtgc calls compute_dtgc_bspline_2d_scalar, compute_dtgc_bspline_2d_vector, compute_dtgc_nurbs_2d_scalar, compute_dtgc_nurbs_2d_vector
compute_tgc calls compute_tgc_bspline_2d_scalar, compute_tgc_bspline_2d_vector, compute_tgc_nurbs_2d_scalar, compute_tgc_nurbs_2d_vector
gauss_leg calls gauss_legendre_1d, gauss_legendre_2d, gauss_legendre_3d
bincoeff calls factln
cmp_degree calls get_multiplicity, set
compute_knot_vector calls repelem
compute_xg_bspline_2d calls kron, basis_bspline
compute_xg_bspline_2d_1point calls kron, basis_bspline
compute_xg_nurbs_2d calls cmp_tgc_2d
compute_xg_nurbs_2d_1point calls kron, basis_bspline
kron calls kron3, kron_t1_t1, kron_t1_t2
cmp_tgc_2d calls kron, basis_bspline
compute_d2tgc_bspline_2d_scalar calls kron, basis_bspline_2der
compute_d2tgc_bspline_2d_vector calls kron, basis_bspline_2der
compute_d2tgc_nurbs_2d_scalar calls kron, basis_bspline_2der
compute_d2tgc_nurbs_2d_vector calls kron, basis_bspline_2der
compute_dtgc_bspline_2d_scalar calls kron, basis_bspline_der
compute_dtgc_bspline_2d_vector calls kron, basis_bspline_der
compute_dtgc_nurbs_2d_scalar calls kron, basis_bspline_der
compute_dtgc_nurbs_2d_vector calls kron, basis_bspline_der
compute_tgc_bspline_2d_scalar calls kron, basis_bspline
compute_tgc_bspline_2d_vector calls kron, basis_bspline
compute_tgc_nurbs_2d_scalar calls kron, basis_bspline
compute_tgc_nurbs_2d_vector calls kron, basis_bspline
gauss_legendre_1d calls gauss_legendre
gauss_legendre_2d calls ndgrid, kron, gauss_legendre
gauss_legendre_3d calls ndgrid, kron, gauss_legendre
basis_bspline_2der calls basis_bspline_2der_a, basis_bspline_2der_b, basis_bspline_2der_c
basis_bspline_der calls basis_bspline_der_a, basis_bspline_der_b