name: codecov
on:
  push:
    branches: [main, master]
jobs:

  Build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        compiler: [gfortran]

    steps:
    - name: Setup Fortran
      uses: gha3mi/setup-fortran-conda@latest
      with:
        compiler: ${{ matrix.compiler }}
        platform: ${{ matrix.os }}
        extra-packages: ""

    - name: Run Tests
      run: |
        fpm test --profile debug --compiler ${{ matrix.compiler }} --flag "--coverage -g -O0" --verbose

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true