name: Release via PR
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm ci

      # Semantic-release will now only prepare changes locally
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      # Explicitly create Pull Request from changes
      - name: Create Release PR
        uses: peter-evans/create-pull-request@v6
        with:
          branch: release/${{ github.run_id }}
          title: 'chore(release): automated release PR'
          commit-message: 'chore(release): prepare release [skip ci]'
          body: 'Automated release PR created by semantic-release.'
          token: ${{ secrets.GH_TOKEN }}
