name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - run: npm install

      # Configure Git user for commits
      - run: git config --global user.name "GitHub Actions"
      - run: git config --global user.email "actions@github.com"

      # Run semantic-release, preparing but not pushing
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      # Create a Pull Request after semantic-release prepares changes
      - name: Create Release PR
        uses: peter-evans/create-pull-request@v6
        with:
          branch: release/${{ github.run_id }}
          title: 'chore: Release'
          commit-message: 'chore: prepare release [skip ci]'
          body: 'Automated release PR created by semantic-release.'
          token: ${{ secrets.GH_TOKEN }}